package wdb

import (
	"github.com/Emyrk/chronicle/database"
	"github.com/jackc/pgx/v5/pgtype"
)

// ItemToWorldTemplate converts a parsed WDB Item to a database WorldItemTemplate.
// Server-only fields (buy_count, spellppmrate, disenchant_id, food_type,
// money loot, wrapped_gift, extra_flags, other_team_entry, script_name, patch)
// are left at their zero values and will not be overwritten during upsert.
func ItemToWorldTemplate(it Item) database.WorldItemTemplate {
	return database.WorldItemTemplate{
		Entry:                     int32(it.Entry),
		Class:                     int32(it.Class),
		Subclass:                  int32(it.SubClass),
		Name:                      it.Name,
		Description:               it.Description,
		DisplayID:                 int32(it.DisplayID),
		Quality:                   int32(it.Quality),
		Flags:                     int32(it.Flags),
		BuyPrice:                  int32(it.BuyPrice),
		SellPrice:                 int32(it.SellPrice),
		InventoryType:             int32(it.InventoryType),
		AllowableClass:            it.AllowableClass,
		AllowableRace:             it.AllowableRace,
		ItemLevel:                 int32(it.ItemLevel),
		RequiredLevel:             int32(it.RequiredLevel),
		RequiredSkill:             int32(it.RequiredSkill),
		RequiredSkillRank:         int32(it.RequiredSkillRank),
		RequiredSpell:             int32(it.RequiredSpell),
		RequiredHonorRank:         int32(it.RequiredHonorRank),
		RequiredCityRank:          int32(it.RequiredCityRank),
		RequiredReputationFaction: int32(it.RequiredRepFaction),
		RequiredReputationRank:    int32(it.RequiredRepRank),
		MaxCount:                  it.MaxCount,
		Stackable:                 it.Stackable,
		ContainerSlots:            int32(it.ContainerSlots),
		StatType1:                 int32(it.StatType[0]),
		StatValue1:                it.StatValue[0],
		StatType2:                 int32(it.StatType[1]),
		StatValue2:                it.StatValue[1],
		StatType3:                 int32(it.StatType[2]),
		StatValue3:                it.StatValue[2],
		StatType4:                 int32(it.StatType[3]),
		StatValue4:                it.StatValue[3],
		StatType5:                 int32(it.StatType[4]),
		StatValue5:                it.StatValue[4],
		StatType6:                 int32(it.StatType[5]),
		StatValue6:                it.StatValue[5],
		StatType7:                 int32(it.StatType[6]),
		StatValue7:                it.StatValue[6],
		StatType8:                 int32(it.StatType[7]),
		StatValue8:                it.StatValue[7],
		StatType9:                 int32(it.StatType[8]),
		StatValue9:                it.StatValue[8],
		StatType10:                int32(it.StatType[9]),
		StatValue10:               it.StatValue[9],
		Delay:                     int32(it.Delay),
		RangeMod:                  float64(it.RangedModRange),
		AmmoType:                  int32(it.AmmoType),
		DmgMin1:                   float64(it.DmgMin[0]),
		DmgMax1:                   float64(it.DmgMax[0]),
		DmgType1:                  int32(it.DmgType[0]),
		DmgMin2:                   float64(it.DmgMin[1]),
		DmgMax2:                   float64(it.DmgMax[1]),
		DmgType2:                  int32(it.DmgType[1]),
		// DmgMin3-5 stay zero — vanilla WDB has 5 slots but DB only stores 2.
		Block:                  int32(it.Block),
		Armor:                  int32(it.Armor),
		HolyRes:                int32(it.HolyRes),
		FireRes:                int32(it.FireRes),
		NatureRes:              int32(it.NatureRes),
		FrostRes:               int32(it.FrostRes),
		ShadowRes:              int32(it.ShadowRes),
		ArcaneRes:              int32(it.ArcaneRes),
		Spellid1:               it.SpellID[0],
		Spelltrigger1:          int32(it.SpellTrigger[0]),
		Spellcharges1:          it.SpellCharges[0],
		Spellcooldown1:         it.SpellCooldown[0],
		Spellcategory1:         int32(it.SpellCategory[0]),
		Spellcategorycooldown1: it.SpellCategoryCooldown[0],
		Spellid2:               it.SpellID[1],
		Spelltrigger2:          int32(it.SpellTrigger[1]),
		Spellcharges2:          it.SpellCharges[1],
		Spellcooldown2:         it.SpellCooldown[1],
		Spellcategory2:         int32(it.SpellCategory[1]),
		Spellcategorycooldown2: it.SpellCategoryCooldown[1],
		Spellid3:               it.SpellID[2],
		Spelltrigger3:          int32(it.SpellTrigger[2]),
		Spellcharges3:          it.SpellCharges[2],
		Spellcooldown3:         it.SpellCooldown[2],
		Spellcategory3:         int32(it.SpellCategory[2]),
		Spellcategorycooldown3: it.SpellCategoryCooldown[2],
		Spellid4:               it.SpellID[3],
		Spelltrigger4:          int32(it.SpellTrigger[3]),
		Spellcharges4:          it.SpellCharges[3],
		Spellcooldown4:         it.SpellCooldown[3],
		Spellcategory4:         int32(it.SpellCategory[3]),
		Spellcategorycooldown4: it.SpellCategoryCooldown[3],
		Spellid5:               it.SpellID[4],
		Spelltrigger5:          int32(it.SpellTrigger[4]),
		Spellcharges5:          it.SpellCharges[4],
		Spellcooldown5:         it.SpellCooldown[4],
		Spellcategory5:         int32(it.SpellCategory[4]),
		Spellcategorycooldown5: it.SpellCategoryCooldown[4],
		Bonding:                int32(it.Bonding),
		PageText:               int32(it.PageText),
		PageLanguage:           int32(it.LanguageID),
		PageMaterial:           int32(it.PageMaterial),
		StartQuest:             int32(it.StartQuest),
		LockID:                 int32(it.LockID),
		Material:               it.Material,
		Sheath:                 int32(it.Sheath),
		RandomProperty:         it.RandomProperty,
		SetID:                  int32(it.ItemSet),
		MaxDurability:          int32(it.MaxDurability),
		AreaBound:              int32(it.Area),
		MapBound:               int32(it.Map),
		Duration:               int32(it.Duration),
		BagFamily:              int32(it.BagFamily),
		TotemCategory:          int32(it.TotemCategory),
		SocketColor1:           int32(it.SocketColor[0]),
		SocketContent1:         int32(it.SocketContent[0]),
		SocketColor2:           int32(it.SocketColor[1]),
		SocketContent2:         int32(it.SocketContent[1]),
		SocketColor3:           int32(it.SocketColor[2]),
		SocketContent3:         int32(it.SocketContent[2]),
		SocketBonus:            int32(it.SocketBonus),
		GemProperties:          int32(it.GemProperties),
		RequiredDisenchantSkill: it.RequiredDisenchantSkill,
		ArmorDamageModifier:    float64(it.ArmorDamageModifier),
		ScalingStatDistribution: it.ScalingStatDistribution,
		ScalingStatValue:       it.ScalingStatValue,
		ItemLimitCategory:      it.ItemLimitCategory,
		HolidayID:              it.HolidayID,
		RandomSuffix:           int32(it.RandomSuffix),
	}
}

// CreatureToWorldTemplate converts a parsed WDB Creature to a database WorldCreatureTemplate.
// The creature cache only contains name, subname, and display IDs from fields
// that overlap with the DB schema. Combat stats (health, damage, armor, resistances)
// are server-side only and not present in the WDB cache.
func CreatureToWorldTemplate(c Creature) database.WorldCreatureTemplate {
	sub := pgtype.Text{}
	if c.SubName != "" {
		sub = pgtype.Text{String: c.SubName, Valid: true}
	}
	return database.WorldCreatureTemplate{
		Entry:      int32(c.Entry),
		Name:       c.Name,
		Subname:    sub,
		DisplayId1: int32(c.DisplayID[0]),
		DisplayId2: int32(c.DisplayID[1]),
		DisplayId3: int32(c.DisplayID[2]),
		DisplayId4: int32(c.DisplayID[3]),
	}
}
