# Version info: can be overridden via environment variables (for Docker builds)
GIT_TAG ?= $(shell git describe --tags --abbrev=0 2>/dev/null || echo "unknown")
GIT_COMMIT ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_TIME ?= $(shell TZ='America/Chicago' date +"%m-%d-%y_%H:%M")
LD_BUILD_FLAGS=-ldflags=-X=github.com/Emyrk/chronicle/internal/version.GitTag=$(GIT_TAG)\ -X=github.com/Emyrk/chronicle/internal/version.GitCommit=$(GIT_COMMIT)\ -X=github.com/Emyrk/chronicle/internal/version.BuildTime=$(BUILD_TIME)

.PHONY: install
install:
	go install ./cmd/chronicle
	go install ./cmd/chronicled

database/querier.go: database/sqlc.yaml database/dump.sql $(wildcard database/queries/*.sql)
	./database/generate.sh

.PHONY: test
test:
	gotestsum --format testname -- -tags $(SERVER) -race $$(go list -tags $(SERVER) ./...)

.PHONY: lint
lint:
	golangci-lint run --build-tags $(SERVER)

frontend/chronicle/dist: $(wildcard frontend/**)
	(cd frontend/chronicle; pnpm install; SERVER=$(SERVER) pnpm build)

# SERVER controls which WoW server DBC data to compile in (turtle, epoch, etc.)
SERVER ?= warmane
DB_NAME := $(if $(filter turtle,$(SERVER)),chronicle,$(SERVER))

.PHONY: develop
develop: frontend/chronicle/dist create-db
	go run --tags "static $(SERVER)" $(LD_BUILD_FLAGS) ./cmd/chronicled server --dev-auth --jwt-secret-pem="dev" --ocr-url="http://localhost:8730" --disable-discord-bot=true

develop-backend-fresh:
	docker rm -f chronicle-db-fresh 2>/dev/null || true
	docker run -d --name chronicle-db-fresh -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres -p 5533:5432 postgres:17
	@echo "Waiting for postgres to be ready..."
	@until docker exec chronicle-db-fresh pg_isready -U postgres >/dev/null 2>&1; do sleep 0.5; done
	go run --tags "static $(SERVER)" $(LD_BUILD_FLAGS) ./cmd/chronicled server --dev-auth --jwt-secret-pem="dev" --log-parse-worker-count=4 --ocr-url="http://localhost:8730" --emit-parse-logs --postgres-url="postgres://postgres:postgres@127.0.0.1:5533/postgres?sslmode=disable"

develop-backend: create-db
	go run --tags "$(SERVER)" $(LD_BUILD_FLAGS) ./cmd/chronicled server --dev-auth --jwt-secret-pem="dev" --log-parse-worker-count=4 --ocr-url="http://localhost:8730" --emit-parse-logs --disable-discord-bot=true

.PHONY: build
build: build-backend-static

.PHONY: build-backend
build-backend:
	go build --tags "$(SERVER)" $(LD_BUILD_FLAGS) -o bin/chronicled ./cmd/chronicled

.PHONY: build-backend-static
build-backend-static: frontend/chronicle/dist
	go build --tags "static $(SERVER)" $(LD_BUILD_FLAGS) -o bin/chronicled ./cmd/chronicled

# Docker Compose targets for local development services
COMPOSE_FILE := scripts/development/docker-compose.yml

.PHONY: services-up
services-up:
	docker compose -f $(COMPOSE_FILE) up -d

.PHONY: services-down
services-down:
	docker compose -f $(COMPOSE_FILE) down

.PHONY: services-logs
services-logs:
	docker compose -f $(COMPOSE_FILE) logs -f

.PHONY: services-clean
services-clean:
	docker compose -f $(COMPOSE_FILE) down -v

# Default postgres port for docker-compose setup (5433)
POSTGRES_PORT ?= 5433

.PHONY: create-db
create-db:
	@set -e; \
	if command -v createdb >/dev/null 2>&1; then \
		output="$$(PGPASSWORD='postgres' createdb -U postgres -h localhost -p $(POSTGRES_PORT) $(DB_NAME) 2>&1)" || status=$$?; \
	elif docker compose -f $(COMPOSE_FILE) ps postgres >/dev/null 2>&1; then \
		output="$$(docker compose -f $(COMPOSE_FILE) exec -T postgres psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c 'CREATE DATABASE $(DB_NAME);' 2>&1)" || status=$$?; \
	else \
		echo "createdb not found and dockerized Postgres is unavailable. Install PostgreSQL client tools or run 'make services-up'." >&2; \
		exit 1; \
	fi; \
	if [ -z "$${status:-}" ]; then \
		:; \
	elif printf '%s\n' "$$output" | grep -q "already exists"; then \
		:; \
	else \
		printf '%s\n' "$$output" >&2; \
		exit "$$status"; \
	fi

frontend/chronicle/src/api/typesGenerated.ts: gen/go $(wildcard scripts/apitypings/*) $(shell find ./api/chroniclesdk $(FIND_EXCLUSIONS) -type f -name '*.go') go.mod go.sum
	# -C sets the directory for the go run command
	go run -C ./scripts/apitypings main.go > $@
	#(cd frontend/chronicle/ && pnpm exec biome format --write src/api/typesGenerated.ts)
	touch "$@"

# All files generated by the database should be added here, and this can be used
# as a target for jobs that need to run after the database is generated.
DB_GEN_FILES := \
	database/dump.sql \
	database/querier.go

database/dump.sql: $(wildcard database/migrations/*.sql)
	go run ./database/gen/dump/*.go

gen/db: $(DB_GEN_FILES)
.PHONY: gen/db


.PHONY: gen/static
gen/static:
	go generate ./database/gamedb/chrondbc/dbcmem

# Icon pipeline: extract BLPs from WoW client, convert to WebP, generate manifest
# Helper: run a command in nix-shell if cwebp/rclone are missing, plain shell otherwise.
IMAGECACHE_NIX = frontend/imagecache/shell.nix
define run-imagecache
	if command -v cwebp >/dev/null 2>&1 && command -v rclone >/dev/null 2>&1; then \
		cd frontend/imagecache && SERVER=$(SERVER) $(1); \
	else \
		cd frontend/imagecache && nix-shell shell.nix --run 'SERVER=$(SERVER) $(1)'; \
	fi
endef

.PHONY: icons/convert
icons/convert:
	$(call run-imagecache,./convert-blp.sh)

.PHONY: icons/manifest
icons/manifest: icons/convert
	go run ./scripts/dbstaticgen --icons-dir=frontend/imagecache/$(SERVER)/icons --out=frontend/imagecache/$(SERVER)/icon-list.json

.PHONY: icons/upload
icons/upload:
	$(call run-imagecache,./upload-r2.sh)
	$(call run-imagecache,./upload-icon-list-r2.sh)

# Full pipeline: convert → manifest → upload
.PHONY: icons
icons: icons/convert icons/manifest icons/upload

.PHONY: gen/go
gen/go:
	go generate ./...

.PHONY: gen
gen: gen/db gen/go database/unique_constraint.go frontend/chronicle/src/api/typesGenerated.ts

POSTGRES_VERSION ?= 17
POSTGRES_IMAGE   ?= us-docker.pkg.dev/coder-v2-images-public/public/postgres:$(POSTGRES_VERSION)
.PHONY: test-postgres-docker
test-postgres-docker:
	docker rm -f test-postgres-docker-${POSTGRES_VERSION} || true

	docker pull ${POSTGRES_IMAGE}

	# Make sure to not overallocate work_mem and max_connections as each
	# connection will be allowed to use this much memory. Try adjusting
	# shared_buffers instead, if needed.
	#
	# - work_mem=8MB * max_connections=1000 = 8GB
	# - shared_buffers=2GB + effective_cache_size=1GB = 3GB
	#
	# This leaves 5GB for the rest of the system _and_ storing the
	# database in memory (--tmpfs).
	#
	# https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-WORK-MEM
	docker run \
		--env POSTGRES_PASSWORD=postgres \
		--env POSTGRES_USER=postgres \
		--env POSTGRES_DB=postgres \
		--env PGDATA=/tmp \
		--tmpfs /tmp \
		--publish 5432:5432 \
		--name test-postgres-docker-${POSTGRES_VERSION} \
		--restart no \
		--detach \
		--memory 16GB \
		${POSTGRES_IMAGE} \
		-c shared_buffers=2GB \
		-c effective_cache_size=1GB \
		-c work_mem=8MB \
		-c max_connections=1000 \
		-c fsync=off \
		-c synchronous_commit=off \
		-c full_page_writes=off \
		-c log_statement=all
	while ! pg_isready -h 127.0.0.1; do \
		echo "$$(date) - waiting for database to start"; \
		sleep 0.5; \
	done

.PHONY: docs
docs:
	cd docs && pnpm dev

