// Code generated by 'guts'. DO NOT EDIT.

import type { GUID } from "@/lib/guid/guid";

// From chroniclesdk/panel_layout.go
export interface ActionBarSlotsResponse {
    readonly slot_1: string | null;
    readonly slot_2: string | null;
    readonly slot_3: string | null;
    readonly slot_4: string | null;
    readonly slot_5: string | null;
    readonly slot_6: string | null;
    readonly slot_7: string | null;
    readonly slot_8: string | null;
    readonly slot_9: string | null;
    readonly slot_0: string | null;
}

// From chroniclesdk/log.go
export interface ActivityPeriod {
    readonly start?: PeriodMoment;
    readonly end?: PeriodMoment;
    readonly last_active?: PeriodMoment;
    readonly end_state?: EndState;
}

// From chroniclesdk/guild_page.go
export interface AddGuildMemberRequest {
    readonly user_id: string;
}

// From chroniclesdk/user.go
export interface AdminBulkReparseFailure {
    readonly log_group_id: string;
    readonly name: string;
    readonly detail: string;
}

// From chroniclesdk/user.go
export interface AdminBulkReparseResponse {
    readonly matched: number;
    readonly enqueued: number;
    readonly min_version: string;
    readonly failed: readonly AdminBulkReparseFailure[];
}

// From chroniclesdk/user.go
export interface AdminLog {
    readonly id: string;
    readonly owner_id: string;
    readonly owner_name: string;
    readonly description: string;
    readonly created_at: string;
    readonly state: string;
    readonly size_bytes: number;
    readonly instance_names: readonly string[];
}

// From chroniclesdk/user.go
export interface AdminLogsResponse {
    readonly logs: readonly AdminLog[];
    readonly has_more: boolean;
    readonly total_count: number;
}

// From chroniclesdk/user.go
/**
 * AdminOutdatedInstance is an instance that is not on the latest parser version.
 */
export interface AdminOutdatedInstance {
    readonly id: string;
    readonly log_group_id: string;
    readonly name: string;
    readonly slug: string;
    readonly parser_version: string;
    readonly realm_name: string;
    readonly uploader_name: string;
    readonly uploaded_at: string;
    readonly elapsed_seconds: number | null;
}

// From chroniclesdk/user.go
/**
 * AdminOutdatedInstancesResponse is the response for listing instances with outdated parser versions.
 */
export interface AdminOutdatedInstancesResponse {
    readonly instances: readonly AdminOutdatedInstance[];
    readonly min_version: string;
}

// From chroniclesdk/user.go
/**
 * AdminSetUserRetentionRequest is the request body for setting a user's raw log retention.
 */
export interface AdminSetUserRetentionRequest {
    /**
     * RawLogRetentionHours is the number of hours to retain raw log files.
     * 0 means keep forever (sets NULL in DB).
     */
    readonly raw_log_retention_hours: number;
}

// From chroniclesdk/user.go
export interface AdminUsersResponse {
    readonly users: readonly User[];
}

// From chroniclesdk/armory.go
export interface ArmoryPlayer {
    readonly id: string;
    readonly realm_name: string;
    readonly realm_id: string;
    readonly name: string;
    readonly class: string;
    readonly race: string;
    readonly gender: string;
    readonly level: number;
    readonly guild_id?: string;
    readonly guild_name?: string;
    readonly gear: PlayerOutfit;
    readonly talents?: PlayerTalents;
    readonly updated_at: string;
    readonly updated_from_instance?: string;
}

// From chroniclesdk/armory.go
export interface ArmorySearchResponse {
    readonly players: readonly ArmorySearchResult[];
    readonly count: number;
}

// From chroniclesdk/armory.go
/**
 * ArmorySearchResult is a lightweight player result without gear data.
 */
export interface ArmorySearchResult {
    readonly id: string;
    readonly realm_name: string;
    readonly realm_id: string;
    readonly name: string;
    readonly class: string;
    readonly race: string;
    readonly gender: string;
    readonly level: number;
    readonly guild_id?: string;
    readonly guild_name?: string;
    readonly updated_at: string;
}

// From chroniclesdk/authz.go
/**
 * AuthorizationRequest is a request to check multiple authorizations at once.
 */
export interface AuthorizationRequest {
    /**
     * Checks is a map of check names to SpiceDB-style object strings.
     * Keys are arbitrary identifiers returned in the response.
     * Values are in the format "type:id#permission", e.g.:
     *   - "raid_log:550e8400-e29b-41d4-a716-446655440000#view"
     *   - "instance:550e8400-e29b-41d4-a716-446655440000#edit"
     *
     * The "lookup:" prefix uses LookupResources to check if the user has the
     * given permission on at least one resource of that type, e.g.:
     *   - "lookup:wow_server#administer" — true if user can admin any server
     */
    readonly checks: Record<string, string>;
}

// From chroniclesdk/authz.go
/**
 * AuthorizationResponse is the response to an authorization request.
 * Keys correspond to the keys in the AuthorizationRequest.Checks map.
 * Values are true if the authorization check passed, false otherwise.
 */
export type AuthorizationResponse = Record<string, boolean>;

// From chroniclesdk/azerothcore.go
export interface AzerothCorePingResponse {
    readonly realm_name: string;
    readonly status: string;
}

// From chroniclesdk/world_instance.go
/**
 * BulkUpsertWorldInstanceUnitsRequest is the request body for bulk upserting units.
 */
export interface BulkUpsertWorldInstanceUnitsRequest {
    readonly units: readonly WorldInstanceUnit[];
}

// From chroniclesdk/events.go
export interface ChronicleEncounterEvents {
    readonly encounter_id: string;
    readonly type: string;
    readonly payload: string;
    readonly start_time: string;
}

// From chroniclesdk/guild_page.go
export interface CreateJoinRequestBody {
    readonly message: string;
}

// From chroniclesdk/regression.go
export interface CreateRegressionFixtureRequest {
    readonly log_group_id: string;
    readonly note: string;
}

// From chroniclesdk/share.go
export interface CreateShareRequest {
    readonly instance_id: string;
    readonly payload: Record<string, string>;
}

// From chroniclesdk/share.go
export interface CreateShareResponse {
    readonly code: string;
    readonly url: string;
}

// From chroniclesdk/guild_page.go
export interface CreateTabRequest {
    readonly label: string;
    readonly slug: string;
}

// From chroniclesdk/azerothcore.go
export interface CreateUploadKeyRequest {
    readonly description: string;
}

// From chroniclesdk/panel_layout.go
export interface CreateUserPanelLayoutRequest {
    readonly title: string;
    readonly icon: string;
    readonly description: string;
    readonly payload: Record<string, string>;
}

// From chroniclesdk/azerothcore.go
export interface CreateWoWServerRealmRequest {
    readonly name: string;
    readonly description: string;
    readonly url?: string;
}

// From chroniclesdk/azerothcore.go
export interface CreateWoWServerRequest {
    readonly name: string;
    readonly description: string;
    readonly url?: string;
}

// From chroniclesdk/gamedata.go
/**
 * DBCUploadResponse is the response from uploading a DBC file.
 */
export interface DBCUploadResponse {
    readonly dbc_name: string;
    readonly record_count: number;
    readonly mode: string;
    readonly inserted: number;
    readonly updated: number;
    readonly unchanged: number;
}

// From chroniclesdk/user.go
/**
 * DataGrant represents a storage grant given to a user from various sources
 */
export interface DataGrant {
    readonly id: string;
    readonly source: string;
    readonly storage_bytes: number;
    readonly description?: string;
    readonly created_at: string;
    readonly expires_at?: string;
}

// From chroniclesdk/guild_page.go
export type DeviceVisibility = "all" | "desktop" | "mobile";

export const DeviceVisibilitys: DeviceVisibility[] = ["all", "desktop", "mobile"];

// From chroniclesdk/log.go
/**
 * DuplicateInstance is a sibling instance in the same duplicate group.
 */
export interface DuplicateInstance {
    readonly id: string;
    readonly slug: string;
    readonly name: string;
    readonly recorder_name: string;
    readonly uploader_name: string;
    readonly player_count: number;
    readonly duration_ms?: number;
}

// From chroniclesdk/log.go
export type Duration = number;

// From chroniclesdk/log.go
export type EndState = "reset" | "slain" | "timeout";

export const EndStates: EndState[] = ["reset", "slain", "timeout"];

// From chroniclesdk/log.go
export type GUIDString = string;

// From chroniclesdk/log.go
export interface Guild {
    readonly id: string;
    readonly name: string;
    readonly created_at: string;
}

// From chroniclesdk/guild_page.go
export interface GuildInfo {
    readonly id: string;
    readonly name: string;
    readonly realm_id: string;
    readonly realm_name: string;
    readonly has_page: boolean;
    readonly can_edit: boolean;
    readonly can_view_roster: boolean;
}

// From chroniclesdk/guild_page.go
export interface GuildJoinRequest {
    readonly id: string;
    readonly guild_id: string;
    readonly user_id: string;
    readonly username: string;
    readonly message: string;
    readonly created_at: string;
}

// From chroniclesdk/guild_page.go
export interface GuildPageConfig {
    readonly id: string;
    readonly guild_id: string;
    readonly guild: GuildInfo;
    readonly theme: GuildPageTheme;
    readonly tabs: readonly GuildPageTab[];
}

// From chroniclesdk/guild_page.go
export interface GuildPageOptionsResponse {
    readonly allowed_tags: readonly GuildTag[];
    readonly social_platforms: readonly SocialPlatform[];
}

// From chroniclesdk/guild_page.go
export interface GuildPagePanel {
    readonly id: string;
    readonly panel_type: string;
    // empty interface{} type, falling back to unknown
    readonly config: Record<string, unknown>;
    readonly position: GuildPanelPosition;
    readonly visibility: DeviceVisibility; // "all", "desktop", or "mobile"
}

// From chroniclesdk/guild_page.go
export interface GuildPageTab {
    readonly id: string;
    readonly label: string;
    readonly slug: string;
    readonly sort_order: number;
    readonly visibility: DeviceVisibility; // "all", "desktop", or "mobile"
    readonly panels: readonly GuildPagePanel[];
}

// From chroniclesdk/guild_page.go
export interface GuildPageTheme {
    readonly primary_color?: string;
    readonly banner_url?: string;
    readonly background_url?: string;
    readonly logo_url?: string;
    readonly description?: string;
    readonly tags?: readonly GuildTag[];
    readonly socials?: Record<SocialPlatform, string>; // platform key -> URL
}

// From chroniclesdk/guild_page.go
export interface GuildPanelPosition {
    readonly x: number;
    readonly y: number;
    readonly w: number;
    readonly h: number;
}

// From chroniclesdk/guild_page.go
export interface GuildRosterMember {
    readonly user_id: string;
    readonly username: string;
    readonly roles: readonly string[]; // "member", "leader", etc.
}

// From chroniclesdk/guild_page.go
export interface GuildSettings {
    readonly guild_id: string;
    readonly allow_join_requests_until: string | null;
    readonly is_member: boolean;
}

// From chroniclesdk/constants.go
export type GuildTag = "Casual" | "Chinese" | "Dungeons" | "English" | "French" | "German" | "Hardcore" | "Korean" | "Leveling" | "Portuguese" | "PvP" | "Questing" | "RP" | "Raiding" | "Russian" | "Social" | "Spanish" | "Taiwanese";

export const GuildTags: GuildTag[] = ["Casual", "Chinese", "Dungeons", "English", "French", "German", "Hardcore", "Korean", "Leveling", "Portuguese", "PvP", "Questing", "RP", "Raiding", "Russian", "Social", "Spanish", "Taiwanese"];

// From chroniclesdk/log.go
/**
 * IdentityCreature represents a creature seen during identity mode parsing.
 */
export interface IdentityCreature {
    readonly entry_id: number;
    readonly name: string;
    readonly unique_count: number;
}

// From chroniclesdk/log.go
/**
 * IdentityReport contains all creatures and spells seen in a parsed log,
 * organized by zone. Used for programming raid encounter definitions.
 */
export interface IdentityReport {
    /**
     * ZonedUnits maps zone name → list of creatures seen in that zone.
     */
    readonly zoned_units?: Record<string, IdentityCreature[]>;
    /**
     * ZoneSpells maps zone name → list of spells seen in that zone.
     */
    readonly zone_spells?: Record<string, IdentitySpell[]>;
    /**
     * UnitSpells maps creature entry ID → list of spell names that creature cast.
     */
    readonly unit_spells?: Record<number, string[]>;
    /**
     * GoCode contains generated Go source code for instance definitions.
     */
    readonly go_code?: string;
}

// From chroniclesdk/log.go
/**
 * IdentitySpell represents a spell seen during identity mode parsing.
 */
export interface IdentitySpell {
    readonly spell_id: number;
    readonly count: number;
}

// From chroniclesdk/world_instance.go
export type InstanceCategory = "dungeon" | "pvp" | "raid";

export const InstanceCategorys: InstanceCategory[] = ["dungeon", "pvp", "raid"];

// From chroniclesdk/panel_layout.go
/**
 * InstanceDefaultsResponse provides everything needed by the instance page in one request.
 */
export interface InstanceDefaultsResponse {
    readonly default_desktop_layout: UserPanelLayout | null;
    readonly default_mobile_layout: UserPanelLayout | null;
    readonly action_bar_slots: ActionBarSlotsResponse | null;
    readonly action_bar_layouts: readonly UserPanelLayout[];
}

// From chroniclesdk/loot.go
export interface InstanceLoot {
    readonly source_guid: GUID;
    readonly source_ts: string;
    readonly received_guid: GUID;
    readonly received_ts: string;
    readonly item_id: number;
    readonly item_name: string;
    readonly loot_suffix: number;
    readonly quantity: number;
    readonly quality: number;
    readonly icon: string;
}

// From chroniclesdk/log.go
export interface InstancePlayer {
    readonly name: string;
    readonly class: WoWHeroClasses;
    readonly race: WoWHeroRaces;
}

// From chroniclesdk/log.go
/**
 * InstanceReport contains timing details for a single parsed instance.
 */
export interface InstanceReport {
    readonly name: string;
    readonly finalize_duration_ms: Duration;
    readonly db_insert_duration_ms: Duration;
    readonly encounter_count: number;
    /**
     * UnknownUnits maps creature entry IDs not in the hostiles map to name and hit count.
     */
    readonly unknown_units?: Record<number, UnknownUnit>;
}

// From chroniclesdk/log.go
export interface InstanceUnit {
    readonly name: string;
    readonly owner: GUID | null;
    readonly entry: number;
}

// From chroniclesdk/tooltip.go
export interface ItemDamage {
    readonly min: number;
    readonly max: number;
    readonly school: number;
}

// From chroniclesdk/item_display.go
/**
 * ItemDisplayData contains the data needed to render a 3D model of an item.
 * It combines item identity from world_item_template with model/texture
 * references from ItemDisplayInfo.dbc.
 */
export interface ItemDisplayData {
    readonly entry: number;
    readonly name: string;
    readonly quality: number;
    readonly item_class: number;
    readonly item_subclass: number;
    readonly inventory_type: number;
    readonly sheath: number;
    readonly display_id: number;
    /**
     * From ItemDisplayInfo DBC
     */
    readonly model_name: readonly string[]; // M2 model files (typically 2: left/right hand)
    readonly model_texture: readonly string[]; // Texture files for models (typically 2)
    readonly geoset_group: readonly number[]; // Geoset group indices (typically 3)
    readonly texture: readonly string[]; // Body region textures (8: arm_upper, arm_lower, hand, torso_upper, torso_lower, leg_upper, leg_lower, foot)
    readonly inventory_icon: readonly string[]; // Icon filenames (2: normal, grey)
    readonly helmet_geoset_vis: readonly number[]; // Helmet visibility flags (typically 2)
    readonly geoset_vis_id: readonly number[]; // Helmet geoset vis IDs (typically 2)
    readonly ground_model: string; // Ground/dropped model path
    readonly item_visual: number; // Visual effect ID
    readonly flags: number; // Display flags
}

// From chroniclesdk/tooltip.go
export interface ItemResistance {
    readonly school: number;
    readonly value: number;
}

// From chroniclesdk/tooltip.go
export interface ItemSetBonus {
    readonly threshold: number; // pieces needed
    readonly spell_id: number;
}

// From chroniclesdk/tooltip.go
export interface ItemSetInfo {
    readonly id: number;
    readonly name: string;
    readonly item_ids: readonly number[]; // canonical item entries from ItemSet.dbc
    readonly items: readonly ItemSetPiece[]; // resolved canonical pieces (for tooltip display)
    /**
     * EligibleItems includes all items with this set_id (cross-tier pieces).
     * The frontend uses this to check if an equipped item counts toward the set,
     * even if it's not one of the canonical pieces (e.g. Furious piece in a Wrathful set).
     */
    readonly eligible_items: readonly ItemSetPiece[];
    readonly bonuses: readonly ItemSetBonus[];
}

// From chroniclesdk/tooltip.go
export interface ItemSetPiece {
    readonly entry: number;
    readonly name: string;
    readonly inventory_type: number;
}

// From chroniclesdk/tooltip.go
export interface ItemSpell {
    readonly spell_id: number;
    readonly trigger: number;
    readonly charges?: number;
}

// From chroniclesdk/tooltip.go
export interface ItemStat {
    readonly type: number;
    readonly value: number;
}

// From chroniclesdk/tooltip.go
export interface ItemTooltip {
    readonly entry: number;
    readonly name: string;
    readonly quality: number;
    readonly item_level: number;
    readonly icon: string;
    readonly bonding: number;
    readonly inventory_type: number;
    readonly item_class: number;
    readonly item_subclass: number;
    readonly stats?: readonly ItemStat[];
    readonly armor?: number;
    readonly block?: number;
    readonly damage_ranges?: readonly ItemDamage[];
    readonly delay?: number;
    readonly resistances?: readonly ItemResistance[];
    readonly spells?: readonly ItemSpell[];
    /**
     * Item set info (if item belongs to a set).
     */
    readonly set?: ItemSetInfo;
    /**
     * Enchantment display name (if ?enchant= provided), shown as green text.
     */
    readonly enchantment?: string;
    /**
     * Random suffix name (if ?random_property= provided), e.g. "of the Owl".
     */
    readonly suffix_name?: string;
    /**
     * Random enchantment effect lines (e.g. "+3 Intellect", "+4 Spirit").
     */
    readonly random_enchantments?: readonly string[];
    /**
     * True if item has a random_property but no ?random_property param was given.
     */
    readonly has_random_property?: boolean;
    readonly required_level?: number;
    readonly description?: string;
}

// From chroniclesdk/job.go
export interface JobStatus {
    readonly id: number;
    readonly attempt: number;
    readonly max_attempts: number;
    readonly state: RiverJobState;
    readonly created_at: string;
    readonly scheduled_at: string;
    readonly attempted_at: string | null;
    readonly finalized_at: string | null;
    readonly errors: readonly RiverAttemptError[];
    readonly kind: string;
    readonly output?: Record<string, string>;
}

// From chroniclesdk/log.go
export type KillType = "clean" | "partial" | "reset" | "wipe";

export const KillTypes: KillType[] = ["clean", "partial", "reset", "wipe"];

// From chroniclesdk/panel_layout.go
export interface LayoutDefaultsResponse {
    readonly default_desktop_layout_id: string | null;
    readonly default_mobile_layout_id: string | null;
}

// From chroniclesdk/log.go
/**
 * LeaderboardVersionRequirements holds admin-configured minimum version
 * thresholds for leaderboard filtering.
 */
export interface LeaderboardVersionRequirements {
    readonly instance_name: string;
    readonly min_parser_version: string;
    readonly min_addon_version: string;
}

// From chroniclesdk/guild_page.go
export interface ListGuildsResponse {
    readonly guilds: readonly GuildInfo[];
    readonly total: number;
}

// From chroniclesdk/panel_layout.go
export interface ListUserPanelLayoutsResponse {
    readonly layouts: readonly UserPanelLayout[];
    readonly default_desktop_layout_id: string | null;
    readonly default_mobile_layout_id: string | null;
    readonly action_bar_slots: ActionBarSlotsResponse | null;
}

// From chroniclesdk/log.go
/**
 * LogParseReport contains detailed timing breakdown for a log parse job.
 */
export interface LogParseReport {
    readonly total_duration_ms: Duration;
    readonly load_file_duration_ms: Duration;
    readonly parse_duration_ms: Duration;
    readonly finalize_duration_ms: Duration;
    readonly db_insert_duration_ms: Duration;
    readonly total_lines: number;
    /**
     * Instances contains per-instance timing breakdown.
     */
    readonly instances?: readonly InstanceReport[];
    /**
     * ConsumerTimes contains timing for each consumer (encounter detection, etc.)
     */
    readonly consumer_times?: Record<string, Duration>;
    /**
     * MissedSpells maps spell IDs not found in the DBC to their lookup count and name.
     */
    readonly missed_spells?: Record<number, MissedSpell>;
    /**
     * Identity contains all creatures/spells seen, populated only when identity_mode is enabled.
     */
    readonly identity?: IdentityReport;
}

// From chroniclesdk/response.go
export interface LogUploadResponse {
    readonly log_id: string;
    readonly file_ids: readonly string[];
}

// From chroniclesdk/guild_page.go
export const MaxDescriptionLength = 500;

// From chroniclesdk/guild_page.go
export const MaxTags = 10;

// From chroniclesdk/log.go
/**
 * MissedSpell holds the count and name of a spell not found in the DBC.
 */
export interface MissedSpell {
    readonly count: number;
    readonly name?: string;
}

// From chroniclesdk/log.go
export interface PeriodMoment {
    readonly timestamp: string;
    readonly reason: string;
    readonly message_type?: string;
    readonly message?: Record<string, string>;
}

// From chroniclesdk/armory.go
export interface PlayerGear {
    readonly item_id: number;
    readonly enchant_id?: number;
    readonly item_name?: string;
    readonly item_quality?: number;
    readonly item_icon?: string;
    readonly transmog_id?: number;
}

// From chroniclesdk/armory.go
/**
 * PlayerOutfit mirrors database.PlayerOutfit for the SDK layer.
 */
export type PlayerOutfit = [
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear,
    PlayerGear
];

// From chroniclesdk/armory.go
export interface PlayerTalentTab {
    readonly tab_name?: string;
    readonly points_spent: number;
    readonly ranks: string;
}

// From chroniclesdk/armory.go
/**
 * PlayerTalents represents a player's talent allocation across three trees.
 */
export interface PlayerTalents {
    readonly trees: [
        PlayerTalentTab,
        PlayerTalentTab,
        PlayerTalentTab
    ];
}

// From chroniclesdk/user.go
export interface Preferences {
    readonly helpful_hints: boolean;
    /**
     * RawLogRetentionHours is how long to keep raw log files in object storage
     * after upload. nil means keep forever.
     */
    readonly raw_log_retention_hours: number | null;
}

// From chroniclesdk/log.go
/**
 * RecentEncounter is a simplified encounter summary for the recent raids list.
 */
export interface RecentEncounter {
    readonly name: string;
    readonly boss: boolean;
    readonly kill_type: KillType;
}

// From chroniclesdk/log.go
/**
 * RecentInstance represents a recent raid or dungeon instance.
 */
export interface RecentInstance {
    readonly id: string;
    readonly slug: string;
    readonly name: string;
    readonly realm_id: string;
    readonly realm_name: string;
    readonly uploader_id: string;
    readonly uploader_name: string;
    readonly uploaded_at: string;
    readonly first_encounter_time: string;
    readonly player_count: number;
    readonly boss_count: number;
    readonly boss_kills: number;
    readonly duration_ms: number | null; // nullable if no encounters
    readonly guild_id?: string;
    readonly guild_name?: string;
    readonly encounters?: readonly RecentEncounter[];
    readonly has_youtube_video: boolean;
    readonly duplicate_group_id?: string;
    readonly recorder_name: string;
}

// From chroniclesdk/log.go
/**
 * RecentInstancesResponse is the response for listing recently uploaded instances.
 */
export interface RecentInstancesResponse {
    readonly instances: readonly RecentInstance[];
    readonly next_cursor?: string;
    readonly has_more: boolean;
}

// From chroniclesdk/regression.go
export interface RegressionFixture {
    readonly id: string;
    readonly log_group_id: string;
    readonly note: string;
    readonly created_at: string;
    readonly files_deleted: boolean;
}

// From chroniclesdk/regression.go
export interface RegressionJobStatus {
    readonly pending_jobs: number;
}

// From chroniclesdk/regression.go
export interface RegressionSnapshotFull extends RegressionSnapshotSummary {
    readonly snapshot: Record<string, string>;
}

// From chroniclesdk/regression.go
export interface RegressionSnapshotSummary {
    readonly id: string;
    readonly fixture_id: string;
    readonly version: string;
    readonly build_time: string;
    readonly matches_previous: boolean | null;
    readonly previous_snapshot_id: string | null;
    readonly created_at: string;
}

// From chroniclesdk/guild_page.go
export interface ReorderTabsRequest {
    readonly tab_ids: readonly string[];
}

// From chroniclesdk/regression.go
export interface RequeueVersionRequest {
    readonly version: string;
}

// From chroniclesdk/regression.go
export interface RequeueVersionResponse {
    readonly requeued_count: number;
}

// From chroniclesdk/response.go
/**
 * Response represents a generic HTTP response.
 */
export interface Response {
    /**
     * Message is an actionable message that depicts actions the request took.
     * These messages should be fully formed sentences with proper punctuation.
     * Examples:
     * - "A user has been created."
     * - "Failed to create a user."
     */
    readonly message: string;
    /**
     * CallToAction is an optional field that suggests next steps to the user
     * based on the Message. This field is intended to guide users on what to do
     */
    readonly call_to_action?: string;
    /**
     * Link if provided is a URL that the user can click on to take the suggested action in CallToAction.
     */
    readonly link?: string;
    readonly link_text?: string;
    /**
     * Detail is a debug message that provides further insight into why the
     * action failed. This information can be technical and a regular golang
     * err.Error() text.
     * - "database: too many open connections"
     * - "stat: too many open files"
     */
    readonly detail?: string;
}

// From chroniclesdk/retention.go
/**
 * RetentionPolicy is a retention policy scoped to a server or realm.
 */
export interface RetentionPolicy {
    readonly id: string;
    readonly server_id: string | null;
    readonly realm_id: string | null;
    readonly enabled: boolean;
    readonly last_run_at: string | null;
    readonly total_deleted: number;
    readonly total_kept: number;
    readonly created_at: string;
    readonly updated_at: string;
    readonly rules?: readonly RetentionRule[];
}

// From chroniclesdk/retention.go
/**
 * RetentionPreviewItem describes a single instance's retention evaluation.
 */
export interface RetentionPreviewItem {
    readonly instance_id: string;
    readonly instance_name: string;
    readonly end_time: string;
    readonly matched_rule?: string;
}

// From chroniclesdk/retention.go
/**
 * RetentionPreviewRequest triggers a dry-run of retention evaluation.
 */
export interface RetentionPreviewRequest {
    readonly realm_id?: string;
    readonly server_id?: string;
}

// From chroniclesdk/retention.go
/**
 * RetentionPreviewResponse is the result of a dry-run evaluation.
 */
export interface RetentionPreviewResponse {
    readonly total_evaluated: number;
    readonly to_delete: readonly RetentionPreviewItem[];
    readonly to_keep: readonly RetentionPreviewItem[];
    readonly no_match: readonly RetentionPreviewItem[];
}

// From chroniclesdk/retention.go
/**
 * RetentionRule is an ordered rule within a retention policy.
 */
export interface RetentionRule {
    readonly id: string;
    readonly policy_id: string;
    readonly priority: number;
    readonly action: string; // "keep" | "delete"
    readonly conditions: Record<string, string>;
    readonly description: string;
    readonly created_at: string;
}

// From chroniclesdk/retention.go
/**
 * RetentionRunRequest triggers a manual retention run.
 */
export interface RetentionRunRequest {
    readonly dry_run: boolean;
}

// From rivertype/river_type.go
/**
 * AttemptError is an error from a single job attempt that failed due to an
 * error or a panic.
 */
export interface RiverAttemptError {
    /**
     * At is the time at which the error occurred.
     */
    readonly at: string;
    /**
     * Attempt is the attempt number on which the error occurred (maps to
     * Attempt on a job row).
     */
    readonly attempt: number;
    /**
     * Error contains the stringified error of an error returned from a job or a
     * panic value in case of a panic.
     */
    readonly error: string;
    /**
     * Trace contains a stack trace from a job that panicked. The trace is
     * produced by invoking `debug.Trace()`.
     *
     * In the case of a non-panic or an error produced as a stuck job was
     * rescued, this value will be an empty string.
     */
    readonly trace: string;
}

// From rivertype/river_type.go
export type RiverJobState = string;

// From chroniclesdk/user.go
export interface Session {
    readonly user_id: string;
    readonly session_id: string;
    readonly roles: readonly string[];
    readonly max_storage_bytes: number;
    readonly consumed_storage_bytes: number;
    readonly preferences: Preferences;
    /**
     * Email is the user's email address (if available).
     */
    readonly email: string;
    /**
     * EmailVerified indicates whether the user's email has been verified.
     * Only meaningful for password-auth users.
     */
    readonly email_verified: boolean;
    /**
     * AuthProvider is the provider used for the current session (e.g. "discord", "password").
     */
    readonly auth_provider: string;
}

// From chroniclesdk/user.go
/**
 * SetUserRolesRequest is the request body for setting a user's Chronicle roles.
 */
export interface SetUserRolesRequest {
    readonly roles: readonly string[];
}

// From chroniclesdk/share.go
export interface SharedViewResponse {
    readonly instance_id: string;
    readonly instance_slug?: string;
    readonly payload: Record<string, string>;
}

// From chroniclesdk/sim.go
/**
 * SimItem contains the simulation-relevant fields from world_item_template.
 * This is a purpose-built type for the DPS sim — unlike ItemTooltip which
 * serves display/rendering needs.
 */
export interface SimItem {
    readonly entry: number;
    readonly name: string;
    readonly class: number;
    readonly subclass: number;
    readonly item_level: number;
    readonly inventory_type: number;
    readonly delay: number;
    readonly armor: number;
    readonly block: number;
    readonly set_id?: number;
    readonly stats?: readonly ItemStat[];
    readonly damage?: readonly SimItemDamage[];
    readonly resistances: [
        number,
        number,
        number,
        number,
        number,
        number
    ]; // [holy,fire,nature,frost,shadow,arcane]
    readonly spells?: readonly SimItemSpell[];
}

// From chroniclesdk/sim.go
/**
 * SimItemDamage is a weapon damage range with school info.
 */
export interface SimItemDamage {
    readonly min: number;
    readonly max: number;
    readonly damage_type: number;
}

// From chroniclesdk/sim.go
/**
 * SimItemSpell includes proc fields (PPMRate, cooldowns) that the tooltip
 * endpoint omits because they're not needed for display.
 */
export interface SimItemSpell {
    readonly spell_id: number;
    readonly trigger: number;
    readonly charges?: number;
    readonly ppm_rate?: number;
    readonly cooldown_ms?: number;
    readonly category_cooldown_ms?: number;
}

// From chroniclesdk/user.go
export interface SiteConfig {
    readonly signups_enabled: boolean;
    readonly short_link_domain?: string;
}

// From chroniclesdk/constants.go
export type SocialPlatform = "discord" | "twitch" | "twitter" | "website" | "youtube";

export const SocialPlatforms: SocialPlatform[] = ["discord", "twitch", "twitter", "website", "youtube"];

// From chroniclesdk/log.go
/**
 * SpeedrunKillRecord captures a single kill contributing to a requirement.
 */
export interface SpeedrunKillRecord {
    readonly entry_id: number;
    readonly guid: string;
    readonly timestamp: string;
}

// From chroniclesdk/log.go
/**
 * SpeedrunLeaderboardEntry is one row in the leaderboard.
 */
export interface SpeedrunLeaderboardEntry {
    readonly instance_id: string;
    readonly slug: string;
    readonly duration_ms: number;
    readonly guild_name: string;
    readonly realm_name: string;
    readonly start_time: string;
    readonly completion_time: string;
    readonly player_count: number;
    readonly guild_logo_url?: string;
    readonly parser_version: string;
    readonly addon_version: string;
    readonly duplicate_group_id?: string;
}

// From chroniclesdk/log.go
/**
 * SpeedrunProof ties a requirement to the kills that satisfied (or failed to satisfy) it.
 */
export interface SpeedrunProof {
    readonly requirement: SpeedrunRequirement;
    readonly kills: readonly SpeedrunKillRecord[];
    readonly satisfied: boolean;
}

// From chroniclesdk/log.go
/**
 * SpeedrunRequirement describes one rule for a valid speedrun.
 */
export interface SpeedrunRequirement {
    readonly name: string;
    readonly entry_ids: readonly number[];
    readonly count: number;
    readonly category: string;
}

// From chroniclesdk/log.go
/**
 * SpeedrunResult is the outcome of evaluating speedrun rules against an instance.
 */
export interface SpeedrunResult {
    readonly qualified: boolean;
    readonly start_time: string;
    readonly completion_time: string;
    readonly duration_ms: number;
    readonly proof: readonly SpeedrunProof[];
    readonly version_status?: SpeedrunVersionStatus;
}

// From chroniclesdk/log.go
/**
 * SpeedrunRulesResponse is the response for the speedrun rules endpoint.
 */
export interface SpeedrunRulesResponse {
    readonly instance_name: string;
    readonly requirements: readonly SpeedrunRequirement[];
}

// From chroniclesdk/log.go
/**
 * SpeedrunVersionStatus reports whether the instance's tooling versions
 * meet the leaderboard minimum requirements.
 */
export interface SpeedrunVersionStatus {
    readonly parser_version: string;
    readonly min_parser_version: string;
    readonly parser_qualified: boolean;
    readonly addon_version: string;
    readonly min_addon_version: string;
    readonly addon_qualified: boolean;
}

// From chroniclesdk/panel_layout.go
/**
 * TrackLayoutRequest identifies a layout to track.
 */
export interface TrackLayoutRequest {
    readonly layout_id: string;
}

// From chroniclesdk/world_instance.go
export type UnitAffiliation = "friendly" | "hostile" | "neutral" | "unknown" | "vary";

export const UnitAffiliations: UnitAffiliation[] = ["friendly", "hostile", "neutral", "unknown", "vary"];

// From chroniclesdk/log.go
/**
 * UnknownUnit represents a creature entry not found in the hostiles map.
 */
export interface UnknownUnit {
    readonly name: string;
    readonly count: number;
}

// From chroniclesdk/panel_layout.go
export interface UpdateActionBarSlotsRequest {
    readonly slot_1: string | null;
    readonly slot_2: string | null;
    readonly slot_3: string | null;
    readonly slot_4: string | null;
    readonly slot_5: string | null;
    readonly slot_6: string | null;
    readonly slot_7: string | null;
    readonly slot_8: string | null;
    readonly slot_9: string | null;
    readonly slot_0: string | null;
}

// From chroniclesdk/guild_page.go
export interface UpdateGuildMemberRoleRequest {
    readonly role: string; // "member" or "leader"
}

// From chroniclesdk/guild_page.go
export interface UpdateGuildPageRequest {
    readonly theme: GuildPageTheme;
}

// From chroniclesdk/guild_page.go
export interface UpdateGuildSettingsRequest {
    readonly allow_join_requests_until: string | null;
}

// From chroniclesdk/panel_layout.go
export interface UpdateLayoutDefaultsRequest {
    readonly default_desktop_layout_id?: string;
    readonly default_mobile_layout_id?: string;
}

// From chroniclesdk/user.go
/**
 * UpdatePreferencesRequest is the request body for updating user preferences.
 */
export interface UpdatePreferencesRequest {
    /**
     * RawLogRetentionHours controls raw log file retention. nil = no change, 0 = keep forever.
     */
    readonly raw_log_retention_hours: number | null;
}

// From chroniclesdk/regression.go
export interface UpdateRegressionFixtureNoteRequest {
    readonly note: string;
}

// From chroniclesdk/guild_page.go
export interface UpdateTabRequest {
    readonly label: string;
    readonly panels: readonly GuildPagePanel[];
}

// From chroniclesdk/panel_layout.go
export interface UpdateUserPanelLayoutRequest {
    readonly title?: string;
    readonly icon?: string;
    readonly description?: string;
    readonly payload?: (Record<string, string>);
}

// From chroniclesdk/azerothcore.go
export interface UploadKey {
    readonly id: string;
    readonly realm_id: string;
    readonly description: string;
    readonly created_at: string;
    readonly last_used_at?: string;
    readonly created_by?: string;
    /**
     * Secret is only populated on creation response (shown once).
     */
    readonly secret?: string;
}

// From chroniclesdk/user.go
/**
 * UpsertDataGrantRequest is used to create or update a storage grant
 */
export interface UpsertDataGrantRequest {
    readonly source: string;
    readonly storage_bytes: number;
    readonly description?: string;
    readonly expires_at?: string;
}

// From chroniclesdk/retention.go
/**
 * UpsertRetentionPolicyRequest creates or updates a retention policy.
 */
export interface UpsertRetentionPolicyRequest {
    readonly server_id: string | null;
    readonly realm_id: string | null;
    readonly enabled: boolean;
}

// From chroniclesdk/retention.go
/**
 * UpsertRetentionRuleRequest creates or updates a retention rule.
 */
export interface UpsertRetentionRuleRequest {
    readonly priority: number;
    readonly action: string;
    readonly conditions: Record<string, string>;
    readonly description: string;
}

// From chroniclesdk/world_instance.go
/**
 * UpsertWorldInstanceTemplateRequest is the request body for creating/updating an instance template.
 */
export interface UpsertWorldInstanceTemplateRequest {
    readonly name: string;
    readonly abbreviation?: string;
    readonly category: InstanceCategory;
    readonly boss_count?: number;
    readonly background?: string;
    readonly zone_names: readonly WorldInstanceZoneName[];
}

// From chroniclesdk/user.go
export interface User {
    readonly id: string;
    readonly username: string;
    readonly email: string;
    readonly roles: readonly string[];
    readonly created_at: string;
    readonly updated_at: string;
    readonly max_storage_bytes: number;
    readonly max_storage_bytes_updated: string;
    readonly consumed_storage_bytes: number;
    /**
     * RawLogRetentionHours is how long to keep raw log files. nil means keep forever.
     */
    readonly raw_log_retention_hours: number | null;
}

// From chroniclesdk/panel_layout.go
export interface UserPanelLayout {
    readonly id: string;
    readonly title: string;
    readonly icon: string;
    readonly description: string;
    readonly payload: Record<string, string>;
    readonly code: string | null;
    readonly version: number;
    readonly owner_id: string | null;
    readonly owner_username: string | null;
    readonly is_tracked: boolean;
    readonly tracker_count: number;
    readonly created_at: string;
    readonly updated_at: string;
}

// From chroniclesdk/user.go
/**
 * UserStorageInfo contains storage usage and grant breakdown for a user
 */
export interface UserStorageInfo {
    readonly max_storage_bytes: number;
    readonly consumed_storage_bytes: number;
    readonly grants: readonly DataGrant[];
}

// From chroniclesdk/youtube.go
export interface Video {
    readonly url: string;
    readonly exported_at: string;
    readonly results: readonly VideoTimestamp[];
}

// From chroniclesdk/youtube.go
export interface VideoTimestamp {
    readonly video_time_seconds: number;
    readonly raw_ocr: string;
    /**
     * ServerTime is the time shown on the in-game clock, like "17:56:08"
     */
    readonly server_time: string;
    /**
     * UTCTime is ServerTime adjusted by the user-specified offset to match UTC.
     * This is used to sync with encounter timestamps which are stored in UTC.
     */
    readonly utc_time?: string;
    readonly confidence: number;
}

// From chroniclesdk/gamedata.go
/**
 * WDBFieldDiff describes a single changed field.
 */
export interface WDBFieldDiff {
    readonly field: string;
    // empty interface{} type, falling back to unknown
    readonly old: unknown;
    // empty interface{} type, falling back to unknown
    readonly new: unknown;
    readonly unreliable?: boolean;
}

// From chroniclesdk/gamedata.go
/**
 * WDBItemDiff describes changes for one item entry.
 */
export interface WDBItemDiff {
    readonly entry: number;
    readonly name: string;
    readonly status: string; // "new", "changed", "unchanged"
    readonly fields?: readonly WDBFieldDiff[];
}

// From chroniclesdk/gamedata.go
/**
 * WDBUploadResponse is the response from uploading a WDB cache file.
 */
export interface WDBUploadResponse {
    readonly signature: string;
    readonly version: number;
    readonly record_count: number;
    readonly mode: string;
    readonly new_items: number;
    readonly changed: number;
    readonly unchanged: number;
    readonly diffs: readonly WDBItemDiff[];
}

// From types/date.go
/**
 * AddonDateFormat is the date format for addon created logs like `COMBATANT_INFO`
 */
export const WoWAddonDateFormat = "02.01.06 15:04:05";

// From types/classification.go
export type WoWAffiliation = 1 | 2 | 3 | 0;

export const WoWAffiliations: WoWAffiliation[] = [1, 2, 3, 0];

// From types/constants.go
export type WoWAuraApplication = "Fades" | "Gains" | "Removed" | "Unknown";

export const WoWAuraApplications: WoWAuraApplication[] = ["Fades", "Gains", "Removed", "Unknown"];

// From types/constants.go
export type WoWAuraState = 1 | 3 | 2 | 0;

export const WoWAuraStates: WoWAuraState[] = [1, 3, 2, 0];

// From types/constants.go
export type WoWCastActions = "begins to cast" | "casts" | "channels" | "fails casting";

export const WoWCastActionses: WoWCastActions[] = ["begins to cast", "casts", "channels", "fails casting"];

// From types/constants.go
export type WoWCastFlags = 32 | 1 | 0 | 2 | 4 | 8 | 16 | 64 | 128 | 256;

export const WoWCastFlagses: WoWCastFlags[] = [32, 1, 0, 2, 4, 8, 16, 64, 128, 256];

// From types/constants.go
export type WoWChangeDirection = "Gain" | "Loss";

export const WoWChangeDirections: WoWChangeDirection[] = ["Gain", "Loss"];

// From chroniclesdk/log.go
export interface WoWEncounter {
    readonly id: string;
    readonly instance_id: string;
    readonly boss: boolean;
    readonly name: string;
    readonly kill_type: KillType;
    readonly remaining?: readonly GUID[];
    readonly start_time: string;
    readonly end_time: string;
}

// From chroniclesdk/log.go
export interface WoWEncounterHostile {
    readonly id: GUID;
    readonly boss: boolean;
    readonly periods: readonly ActivityPeriod[];
}

// From types/constants.go
export type WoWEncounterType = "BOSS" | "TRASH" | "UNKNOWN";

export const WoWEncounterTypes: WoWEncounterType[] = ["BOSS", "TRASH", "UNKNOWN"];

// From chroniclesdk/log.go
export interface WoWEncounterWithHostiles extends WoWEncounter {
    readonly hostiles: readonly WoWEncounterHostile[];
}

// From types/constants.go
export type WoWEnvironmentType = "drowning" | "fall" | "fatigue" | "fire" | "lava" | "slime";

export const WoWEnvironmentTypes: WoWEnvironmentType[] = ["drowning", "fall", "fatigue", "fire", "lava", "slime"];

// From chroniclesdk/constants.go
export type WoWEventType = "absorbed" | "aura" | "aura_cast" | "cast" | "combatant_info" | "damage" | "dispel" | "extra_attack" | "heal" | "interrupt" | "resource_change" | "slain" | "spell_fail" | "spell_go" | "spell_start" | "unit_classification";

export const WoWEventTypes: WoWEventType[] = ["absorbed", "aura", "aura_cast", "cast", "combatant_info", "damage", "dispel", "extra_attack", "heal", "interrupt", "resource_change", "slain", "spell_fail", "spell_go", "spell_start", "unit_classification"];

// From types/constants.go
export type WoWHeroClasses = "DEATHKNIGHT" | "DRUID" | "HUNTER" | "MAGE" | "PALADIN" | "PRIEST" | "ROGUE" | "SHAMAN" | "UNKNOWN" | "WARLOCK" | "WARRIOR";

export const WoWHeroClasseses: WoWHeroClasses[] = ["DEATHKNIGHT", "DRUID", "HUNTER", "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "UNKNOWN", "WARLOCK", "WARRIOR"];

// From types/constants.go
export type WoWHeroGender = 3 | 2 | 0 | 1;

export const WoWHeroGenders: WoWHeroGender[] = [3, 2, 0, 1];

// From types/constants.go
export type WoWHeroRaces = "BloodElf" | "Dwarf" | "Gnome" | "Goblin" | "Human" | "NightElf" | "Orc" | "Scourge" | "Tauren" | "Troll" | "Unknown";

export const WoWHeroRaceses: WoWHeroRaces[] = ["BloodElf", "Dwarf", "Gnome", "Goblin", "Human", "NightElf", "Orc", "Scourge", "Tauren", "Troll", "Unknown"];

// From types/constants.go
export type WoWHitType = 4 | 512 | 32768 | 2048 | 16384 | 1024 | 128 | 262144 | 16 | 256 | 2 | 8192 | 65536 | 32 | 0 | 1 | 4096 | 64 | 131072 | 8 | 2097152 | 1048576 | 524288;

export const WoWHitTypes: WoWHitType[] = [4, 512, 32768, 2048, 16384, 1024, 128, 262144, 16, 256, 2, 8192, 65536, 32, 0, 1, 4096, 64, 131072, 8, 2097152, 1048576, 524288];

// From chroniclesdk/log.go
export interface WoWInstance {
    readonly id: string;
    readonly realm_id: string;
    readonly log_group_id: string;
    readonly name: string;
    readonly slug: string;
    readonly start_time?: string;
    readonly end_time?: string;
    readonly guild?: Guild;
    readonly capabilities: readonly string[];
    readonly versions: Record<string, string>;
    readonly recorder_name: string;
    readonly recorder_guid: string;
    readonly duplicate_group_id?: string;
}

// From chroniclesdk/log.go
export interface WoWLogFile {
    readonly id: string;
    readonly owner: string;
    readonly wow_log_id: string;
    readonly hash: string;
    readonly size_bytes: number;
    readonly mime_type: string;
    readonly compressed_size_bytes?: number;
    readonly content_encoding?: string;
    readonly created_at: string;
    readonly updated_at: string;
    readonly storage_deleted_at?: string;
}

// From chroniclesdk/log.go
export interface WoWLogGroup {
    readonly id: string;
    readonly owner: string;
    readonly created_at: string;
    readonly updated_at: string;
    readonly log_type: string;
    readonly files: readonly WoWLogFile[];
    readonly processing_output?: Record<string, string>;
}

// From chroniclesdk/log.go
export interface WoWLogGroupState extends WoWLogGroup {
    readonly status: JobStatus;
}

// From chroniclesdk/log.go
export interface WoWParsedInstance extends WoWInstance {
    readonly realm_name?: string;
    readonly encounters: readonly WoWEncounterWithHostiles[];
    readonly units: Record<string, InstanceUnit>;
    readonly players: Record<string, InstancePlayer>;
}

// From chroniclesdk/log.go
export interface WoWParsedLogJobOutput {
    readonly complete: string | null;
    readonly instance_failures: Record<string, string>;
    readonly instances: readonly WoWSimpleParsedInstance[];
    /**
     * Report contains detailed timing and performance metrics for the parse job.
     */
    readonly report?: LogParseReport;
}

// From types/constants.go
export type WoWResource = "Energy" | "Focus" | "Happiness" | "Health" | "Mana" | "Rage" | "Unknown";

export const WoWResources: WoWResource[] = ["Energy", "Focus", "Happiness", "Health", "Mana", "Rage", "Unknown"];

// From types/constants.go
export type WoWSchool = 64 | 4 | 16 | 2 | 8 | 0 | 1 | 32;

export const WoWSchools: WoWSchool[] = [64, 4, 16, 2, 8, 0, 1, 32];

// From chroniclesdk/azerothcore.go
export interface WoWServer {
    readonly id: string;
    readonly name: string;
    readonly description: string;
    readonly url?: string;
    readonly created_by?: string;
}

// From chroniclesdk/azerothcore.go
export interface WoWServerRealm {
    readonly id: string;
    readonly server_id: string;
    readonly name: string;
    readonly description: string;
    readonly url?: string;
    readonly created_by?: string;
}

// From chroniclesdk/log.go
export interface WoWSimpleParsedInstance extends WoWInstance {
    readonly encounters: readonly WoWEncounter[];
}

// From types/trailer.go
/**
 * TrailerEntry represents a single entry in the combat trailer
 */
export interface WoWTrailerEntry {
    readonly Amount: number | null;
    readonly HitType: WoWHitType;
}

// From types/classification.go
export type WoWUnitType = 2 | 3 | 1 | 0 | 4;

export const WoWUnitTypes: WoWUnitType[] = [2, 3, 1, 0, 4];

// From chroniclesdk/world_instance.go
export interface WorldInstanceTemplate {
    readonly id: string;
    readonly name: string;
    readonly abbreviation?: string;
    readonly category: InstanceCategory;
    readonly boss_count?: number;
    readonly background?: string;
    readonly zone_names: readonly WorldInstanceZoneName[];
}

// From chroniclesdk/world_instance.go
export interface WorldInstanceUnit {
    readonly entry_id: number;
    readonly name: string; // Resolved: override_name ?? world_creature_template.name ?? "Unknown"
    readonly override_name?: string;
    readonly encounter_name?: string;
    readonly boss: boolean;
    readonly affiliation: UnitAffiliation;
}

// From chroniclesdk/world_instance.go
export interface WorldInstanceZoneName {
    readonly zone_name: string;
    readonly display_name: string;
}


