// Code generated by scripts/dbcdata (server: octowow). DO NOT EDIT.

export type ExtraAttackSpell = {
  name: string;
  numExtraAttacks: number;
};

export const ExtraAttackSpells: Record<number, ExtraAttackSpell> = {
  677: { name: "Holy Flurry II", numExtraAttacks: 1 },
  1869: { name: "Holy Flurry III", numExtraAttacks: 2 },
  1870: { name: "Holy Flurry IV", numExtraAttacks: 2 },
  3391: { name: "Thrash", numExtraAttacks: 2 },
  8233: { name: "Windfury Weapon", numExtraAttacks: 2 },
  8236: { name: "Windfury Weapon", numExtraAttacks: 2 },
  8516: { name: "Windfury Totem", numExtraAttacks: 1 },
  10484: { name: "Windfury Weapon", numExtraAttacks: 2 },
  10608: { name: "Windfury Totem", numExtraAttacks: 1 },
  10610: { name: "Windfury Totem", numExtraAttacks: 1 },
  15494: { name: "Fury of Forgewright", numExtraAttacks: 2 },
  15601: { name: "Hand of Justice", numExtraAttacks: 1 },
  15642: { name: "Ironfoe", numExtraAttacks: 3 },
  16361: { name: "Windfury Weapon", numExtraAttacks: 2 },
  16459: { name: "Sword Specialization", numExtraAttacks: 1 },
  16843: { name: "Crimson Fury", numExtraAttacks: 3 },
  18797: { name: "Flurry Axe", numExtraAttacks: 1 },
  18941: { name: "Double Attack", numExtraAttacks: 1 },
  19105: { name: "MHTest01 Effect", numExtraAttacks: 2 },
  19109: { name: "MHTest02 Effect", numExtraAttacks: 2 },
  20178: { name: "Reckoning", numExtraAttacks: 1 },
  21919: { name: "Thrash", numExtraAttacks: 1 },
  25175: { name: "Triple Attack", numExtraAttacks: 2 },
  27035: { name: "Sword Specialization (OLD)", numExtraAttacks: 1 },
  49369: { name: "Rage of the Mountain", numExtraAttacks: 1 },
  51368: { name: "Windfury Totem", numExtraAttacks: 1 },
  52634: { name: "Hack and Slash", numExtraAttacks: 1 },
  52732: { name: "Timeless Strike", numExtraAttacks: 1 },
  58123: { name: "Maddened Strikes", numExtraAttacks: 1 },
};
