// Code generated by scripts/dbcdata (server: vanillaplus). DO NOT EDIT.

package vanillaplus

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellRanges = map[int32]dbcmem.SpellRange{
		1: {ID: 1, RangeMin: 0, RangeMax: 0, Flags: 0, Name: "Self Only"},
		2: {ID: 2, RangeMin: 0, RangeMax: 5, Flags: 1, Name: "Combat Range"},
		3: {ID: 3, RangeMin: 0, RangeMax: 20, Flags: 0, Name: "Short Range"},
		4: {ID: 4, RangeMin: 0, RangeMax: 30, Flags: 0, Name: "Medium Range"},
		5: {ID: 5, RangeMin: 0, RangeMax: 40, Flags: 0, Name: "Long Range"},
		6: {ID: 6, RangeMin: 0, RangeMax: 100, Flags: 0, Name: "Vision Range"},
		7: {ID: 7, RangeMin: 0, RangeMax: 10, Flags: 0, Name: "Very Short Range"},
		8: {ID: 8, RangeMin: 10, RangeMax: 20, Flags: 0, Name: "Short Range"},
		9: {ID: 9, RangeMin: 10, RangeMax: 30, Flags: 0, Name: "Medium Range"},
		10: {ID: 10, RangeMin: 10, RangeMax: 40, Flags: 0, Name: "Long Range"},
		11: {ID: 11, RangeMin: 0, RangeMax: 15, Flags: 0, Name: "Shorter Range"},
		12: {ID: 12, RangeMin: 0, RangeMax: 5, Flags: 0, Name: "Interact Range"},
		13: {ID: 13, RangeMin: 0, RangeMax: 50000, Flags: 0, Name: "Anywhere"},
		14: {ID: 14, RangeMin: 0, RangeMax: 60, Flags: 0, Name: "Extra Long Range"},
		34: {ID: 34, RangeMin: 0, RangeMax: 25, Flags: 0, Name: "Medium-Short Range"},
		35: {ID: 35, RangeMin: 0, RangeMax: 35, Flags: 0, Name: "Medium-Long Range"},
		36: {ID: 36, RangeMin: 0, RangeMax: 45, Flags: 0, Name: "Longer Range"},
		37: {ID: 37, RangeMin: 0, RangeMax: 50, Flags: 0, Name: "Extended Range"},
		38: {ID: 38, RangeMin: 10, RangeMax: 25, Flags: 0, Name: "Extra Medium Range"},
		54: {ID: 54, RangeMin: 5, RangeMax: 30, Flags: 0, Name: "Geoff Monster Shoot"},
		74: {ID: 74, RangeMin: 8, RangeMax: 30, Flags: 0, Name: "Ranged Weapon"},
		94: {ID: 94, RangeMin: 8, RangeMax: 40, Flags: 0, Name: "Sting"},
		95: {ID: 95, RangeMin: 8, RangeMax: 25, Flags: 0, Name: "Charge"},
		96: {ID: 96, RangeMin: 0, RangeMax: 2, Flags: 0, Name: "Trap"},
		114: {ID: 114, RangeMin: 10, RangeMax: 35, Flags: 0, Name: "Hunter Range"},
		134: {ID: 134, RangeMin: 0, RangeMax: 80, Flags: 0, Name: "Tower 80"},
		135: {ID: 135, RangeMin: 0, RangeMax: 100, Flags: 0, Name: "Tower 100"},
		136: {ID: 136, RangeMin: 30, RangeMax: 80, Flags: 0, Name: "Artillery Range"},
	}
}
