-- Code generated by 'make chronicle/database/generate'. DO NOT EDIT.


CREATE DOMAIN activity_periods AS jsonb;

CREATE TYPE instance_category AS ENUM (
    'raid',
    'dungeon',
    'pvp'
);

CREATE TYPE item_effect_type AS ENUM (
    'on_use',
    'on_equip',
    'on_hit',
    'proc'
);

CREATE TYPE kill_type AS ENUM (
    'clean',
    'partial',
    'wipe',
    'reset'
);

CREATE TYPE log_instance_event_type AS ENUM (
    'damage',
    'heal',
    'resource_change',
    'extra_attack',
    'slain',
    'cast',
    'aura',
    'spell_go',
    'aura_cast',
    'spell_start',
    'spell_fail',
    'unit_classification',
    'dispel',
    'combatant_info',
    'interrupt',
    'absorbed'
);

CREATE TYPE log_type AS ENUM (
    'v1',
    'v2',
    'warmane',
    'epoch',
    'kronos',
    'azerothcore'
);

CREATE TYPE river_job_state AS ENUM (
    'available',
    'cancelled',
    'completed',
    'discarded',
    'pending',
    'retryable',
    'running',
    'scheduled'
);

CREATE TYPE unit_affiliation AS ENUM (
    'unknown',
    'friendly',
    'neutral',
    'hostile',
    'vary'
);

CREATE DOMAIN wow_guid AS text
	CONSTRAINT wow_guid_check CHECK ((VALUE ~ '^0x[0-9A-Fa-f]{16}$'::text));

CREATE DOMAIN wow_log_group_files AS jsonb;

CREATE TYPE wow_playable_class AS ENUM (
    'WARRIOR',
    'PALADIN',
    'HUNTER',
    'ROGUE',
    'PRIEST',
    'DEATH_KNIGHT',
    'SHAMAN',
    'MAGE',
    'WARLOCK',
    'DRUID',
    'MONK',
    'DEMON_HUNTER',
    'UNKNOWN'
);

CREATE TYPE wow_playable_gender AS ENUM (
    'NotSet',
    'Unknown',
    'Male',
    'Female'
);

CREATE TYPE wow_playable_race AS ENUM (
    'Scourge',
    'Orc',
    'Troll',
    'Tauren',
    'Goblin',
    'Human',
    'Gnome',
    'Dwarf',
    'NightElf',
    'BloodElf',
    'Unknown'
);

CREATE FUNCTION cleanup_orphaned_layout() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  check_layout_id uuid;
BEGIN
  IF TG_TABLE_NAME = 'user_tracked_layouts' THEN
    check_layout_id := OLD.layout_id;
  ELSE
    check_layout_id := NEW.id;
  END IF;

  DELETE FROM user_panel_layouts
  WHERE id = check_layout_id
    AND user_id IS NULL
    AND NOT EXISTS (
      SELECT 1
      FROM user_tracked_layouts
      WHERE layout_id = check_layout_id
    );

  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE FUNCTION insert_default_data_grant() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  INSERT INTO data_grants (user_id, source, storage_bytes, description)
  VALUES (NEW.id, 'base', 150000000, 'Default storage allocation');
  RETURN NEW;
END;
$$;

CREATE FUNCTION reattach_by_slug() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.hashed_slug IS NOT NULL AND NEW.hashed_slug != '' THEN
        UPDATE shared_views
        SET instance_id = NEW.id
        WHERE instance_slug = NEW.hashed_slug AND instance_id IS NULL;

        UPDATE log_instance_youtube_timestamped
        SET log_instance_id = NEW.id
        WHERE instance_slug = NEW.hashed_slug AND log_instance_id IS NULL;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION river_job_state_in_bitmask(bitmask bit, state river_job_state) RETURNS boolean
    LANGUAGE sql IMMUTABLE
    AS $$
    SELECT CASE state
        WHEN 'available' THEN get_bit(bitmask, 7)
        WHEN 'cancelled' THEN get_bit(bitmask, 6)
        WHEN 'completed' THEN get_bit(bitmask, 5)
        WHEN 'discarded' THEN get_bit(bitmask, 4)
        WHEN 'pending'   THEN get_bit(bitmask, 3)
        WHEN 'retryable' THEN get_bit(bitmask, 2)
        WHEN 'running'   THEN get_bit(bitmask, 1)
        WHEN 'scheduled' THEN get_bit(bitmask, 0)
        ELSE 0
    END = 1;
$$;

CREATE TABLE authz_schema_migrations (
    version integer NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE data_grants (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    source text NOT NULL,
    storage_bytes bigint NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone
);

CREATE TABLE log_file (
    id uuid NOT NULL,
    owner uuid NOT NULL,
    wow_log_id uuid NOT NULL,
    hash text NOT NULL,
    size_bytes bigint NOT NULL,
    mime_type text NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    storage_deleted_at timestamp with time zone,
    compressed_size_bytes bigint,
    content_encoding text
);

COMMENT ON COLUMN log_file.size_bytes IS 'Original uncompressed file size in bytes';

COMMENT ON COLUMN log_file.storage_deleted_at IS 'The timestamp when the file was deleted from storage. This allows us to keep track of files that have been removed from storage, even if the log_file record still exists in the database.';

COMMENT ON COLUMN log_file.compressed_size_bytes IS 'Compressed file size in bytes (NULL if stored uncompressed)';

COMMENT ON COLUMN log_file.content_encoding IS 'Content encoding used for storage (e.g., gzip), NULL if stored raw';

CREATE VIEW user_storage_limits AS
 SELECT data_grants.user_id,
    sum(data_grants.storage_bytes) AS max_storage_bytes,
    max(data_grants.created_at) AS updated_at
   FROM data_grants
  WHERE ((data_grants.expires_at IS NULL) OR (data_grants.expires_at > now()))
  GROUP BY data_grants.user_id;

CREATE TABLE users (
    id uuid NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    default_desktop_layout_id uuid,
    default_mobile_layout_id uuid,
    raw_log_retention_hours integer
);

CREATE VIEW chronicle_users AS
 SELECT u.id,
    u.username,
    u.email,
    u.created_at,
    u.updated_at,
    u.default_desktop_layout_id,
    u.default_mobile_layout_id,
    u.raw_log_retention_hours,
    COALESCE(sl.max_storage_bytes, (0)::numeric) AS max_storage_bytes,
    sl.updated_at AS data_limit_updated_at,
    COALESCE(lf.total_size_bytes, (0)::numeric) AS consumed_storage_bytes
   FROM ((public.users u
     LEFT JOIN user_storage_limits sl ON ((sl.user_id = u.id)))
     LEFT JOIN ( SELECT log_file.owner,
            sum(COALESCE(log_file.compressed_size_bytes, log_file.size_bytes)) AS total_size_bytes
           FROM log_file
          WHERE (log_file.storage_deleted_at IS NULL)
          GROUP BY log_file.owner) lf ON ((lf.owner = u.id)));

CREATE TABLE dbc_item_display_info (
    id integer NOT NULL,
    model_name jsonb DEFAULT '[]'::jsonb NOT NULL,
    model_texture jsonb DEFAULT '[]'::jsonb NOT NULL,
    geoset_group jsonb DEFAULT '[]'::jsonb NOT NULL,
    flags integer DEFAULT 0 NOT NULL,
    spell_visual_id integer DEFAULT 0 NOT NULL,
    helmet_geoset_vis jsonb DEFAULT '[]'::jsonb NOT NULL,
    texture jsonb DEFAULT '[]'::jsonb NOT NULL,
    item_visual integer DEFAULT 0 NOT NULL,
    particle_color_id integer DEFAULT 0 NOT NULL,
    attachment_geoset_group jsonb DEFAULT '[]'::jsonb NOT NULL,
    item_ranged_display_info_id integer DEFAULT 0 NOT NULL,
    model_material_resources_id jsonb DEFAULT '[]'::jsonb NOT NULL,
    model_resources_id jsonb DEFAULT '[]'::jsonb NOT NULL,
    model_type_1 integer DEFAULT 0 NOT NULL,
    override_swoosh_sound_kit_id integer DEFAULT 0 NOT NULL,
    sheathe_transform_matrix_id integer DEFAULT 0 NOT NULL,
    sheathed_spell_visual_kit_id integer DEFAULT 0 NOT NULL,
    state_spell_visual_kit_id integer DEFAULT 0 NOT NULL,
    unsheathed_spell_visual_kit_id integer DEFAULT 0 NOT NULL,
    inventory_icon jsonb DEFAULT '[]'::jsonb NOT NULL,
    group_sound_index integer DEFAULT 0 NOT NULL,
    ground_model text DEFAULT ''::text NOT NULL,
    item_size integer DEFAULT 0 NOT NULL,
    helmet_geoset_vis_id jsonb DEFAULT '[]'::jsonb NOT NULL
);

CREATE TABLE dbc_item_random_properties (
    id integer NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    name_lang text DEFAULT ''::text NOT NULL,
    enchantment_1 integer DEFAULT 0 NOT NULL,
    enchantment_2 integer DEFAULT 0 NOT NULL,
    enchantment_3 integer DEFAULT 0 NOT NULL,
    enchantment_4 integer DEFAULT 0 NOT NULL,
    enchantment_5 integer DEFAULT 0 NOT NULL
);

CREATE TABLE dbc_item_set (
    id integer NOT NULL,
    name_lang text DEFAULT ''::text NOT NULL,
    required_skill integer DEFAULT 0 NOT NULL,
    required_skill_rank integer DEFAULT 0 NOT NULL,
    item_ids integer[] DEFAULT '{}'::integer[] NOT NULL
);

CREATE TABLE dbc_item_set_bonus (
    set_id integer NOT NULL,
    threshold integer NOT NULL,
    spell_id integer NOT NULL
);

CREATE TABLE dbc_item_set_item (
    set_id integer NOT NULL,
    item_entry integer NOT NULL
);

CREATE TABLE dbc_spell_item_enchantment (
    id integer NOT NULL,
    charges integer DEFAULT 0 NOT NULL,
    effect_1 integer DEFAULT 0 NOT NULL,
    effect_2 integer DEFAULT 0 NOT NULL,
    effect_3 integer DEFAULT 0 NOT NULL,
    effect_points_min_1 integer DEFAULT 0 NOT NULL,
    effect_points_min_2 integer DEFAULT 0 NOT NULL,
    effect_points_min_3 integer DEFAULT 0 NOT NULL,
    effect_arg_1 integer DEFAULT 0 NOT NULL,
    effect_arg_2 integer DEFAULT 0 NOT NULL,
    effect_arg_3 integer DEFAULT 0 NOT NULL,
    name_lang text DEFAULT ''::text NOT NULL,
    item_visual integer DEFAULT 0 NOT NULL,
    flags integer DEFAULT 0 NOT NULL,
    src_item_id integer DEFAULT 0 NOT NULL,
    condition_id integer DEFAULT 0 NOT NULL,
    required_skill_id integer DEFAULT 0 NOT NULL,
    required_skill_rank integer DEFAULT 0 NOT NULL,
    min_level integer DEFAULT 0 NOT NULL,
    max_level integer DEFAULT 0 NOT NULL
);

CREATE TABLE game_players (
    id wow_guid NOT NULL,
    realm_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    guild_id uuid,
    name text NOT NULL,
    class wow_playable_class NOT NULL,
    gender wow_playable_gender NOT NULL,
    race wow_playable_race NOT NULL,
    gear jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_from_instance uuid,
    level smallint DEFAULT 0 NOT NULL,
    talents jsonb DEFAULT 'null'::jsonb NOT NULL
);

CREATE TABLE guild_join_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    guild_id uuid NOT NULL,
    user_id uuid NOT NULL,
    message text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE guild_page_panels (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tab_id uuid NOT NULL,
    panel_type text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    "position" jsonb DEFAULT '{"h": 2, "w": 6, "x": 0, "y": 0}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE guild_page_tabs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    page_id uuid NOT NULL,
    label text NOT NULL,
    slug text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE guild_pages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    guild_id uuid NOT NULL,
    theme jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE guild_settings (
    guild_id uuid NOT NULL,
    allow_join_requests_until timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE instance_speedruns (
    instance_id uuid NOT NULL,
    instance_name text NOT NULL,
    realm_id uuid NOT NULL,
    guild_id uuid,
    qualified boolean NOT NULL,
    start_time timestamp with time zone NOT NULL,
    completion_time timestamp with time zone NOT NULL,
    duration_ms bigint NOT NULL,
    proof jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    addon_version text DEFAULT ''::text NOT NULL,
    parser_version_num bigint DEFAULT 0 NOT NULL,
    addon_version_num bigint DEFAULT 0 NOT NULL
);

CREATE VIEW guild_speedrun_ranks AS
 SELECT instance_speedruns.instance_id,
    instance_speedruns.instance_name,
    instance_speedruns.realm_id,
    instance_speedruns.guild_id,
    instance_speedruns.duration_ms,
    rank() OVER (PARTITION BY instance_speedruns.guild_id, instance_speedruns.instance_name, instance_speedruns.realm_id ORDER BY instance_speedruns.duration_ms) AS guild_rank
   FROM instance_speedruns
  WHERE ((instance_speedruns.qualified = true) AND (instance_speedruns.guild_id IS NOT NULL));

CREATE TABLE guilds (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    realm_id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE instance_loot (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    instance_id uuid NOT NULL,
    realm_id uuid NOT NULL,
    source_guid bigint NOT NULL,
    source_ts timestamp with time zone NOT NULL,
    received_guid bigint NOT NULL,
    received_ts timestamp with time zone NOT NULL,
    item_id integer NOT NULL,
    item_name text NOT NULL,
    loot_suffix integer DEFAULT 0 NOT NULL,
    quantity integer DEFAULT 1 NOT NULL
);

CREATE TABLE leaderboard_version_requirements (
    instance_name text NOT NULL,
    min_parser_version text DEFAULT ''::text NOT NULL,
    min_parser_version_num bigint DEFAULT 0 NOT NULL,
    min_addon_version text DEFAULT ''::text NOT NULL,
    min_addon_version_num bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE log_instance_encounter_damage_unit_summary (
    encounter_id uuid NOT NULL,
    unit_guid wow_guid NOT NULL,
    unit_name text NOT NULL,
    damage_done_total bigint DEFAULT 0 NOT NULL,
    damage_taken_total bigint DEFAULT 0 NOT NULL,
    damage_done_abilities jsonb,
    damage_taken_abilities jsonb,
    is_player boolean NOT NULL,
    owner_guid wow_guid
);

CREATE TABLE log_instance_encounter_hostiles (
    encounter_id uuid NOT NULL,
    id wow_guid NOT NULL,
    periods activity_periods NOT NULL,
    boss boolean DEFAULT false NOT NULL
);

CREATE TABLE log_instance_encounters (
    id uuid NOT NULL,
    instance_id uuid NOT NULL,
    name text NOT NULL,
    remaining wow_guid[] NOT NULL,
    boss boolean NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    kill_type kill_type NOT NULL
);

CREATE TABLE log_instance_events (
    instance_id uuid NOT NULL,
    type log_instance_event_type NOT NULL,
    events bytea NOT NULL
);

COMMENT ON COLUMN log_instance_events.events IS 'Gzipped protobuf-encoded events';

CREATE TABLE log_instance_players (
    instance_id uuid NOT NULL,
    unit_guid wow_guid NOT NULL,
    name text NOT NULL,
    level integer NOT NULL,
    class wow_playable_class NOT NULL,
    race wow_playable_race NOT NULL,
    guild_id uuid
);

CREATE TABLE log_instance_units (
    instance_id uuid NOT NULL,
    unit_guid wow_guid NOT NULL,
    name text NOT NULL,
    entry integer NOT NULL,
    owner_guid wow_guid
);

COMMENT ON TABLE log_instance_units IS 'Stores all units (NPCs, not players) that participated in an instance.';

CREATE TABLE log_instance_youtube_timestamped (
    log_instance_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    exported_at timestamp with time zone DEFAULT now() NOT NULL,
    video_url text NOT NULL,
    payload jsonb NOT NULL,
    instance_slug text,
    id uuid DEFAULT gen_random_uuid() NOT NULL
);

CREATE TABLE log_instances (
    id uuid NOT NULL,
    realm_id uuid NOT NULL,
    log_group_id uuid NOT NULL,
    name text NOT NULL,
    hashed_slug text,
    guild_id uuid,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    capabilities text[] DEFAULT '{}'::text[] NOT NULL,
    versions jsonb DEFAULT '{}'::jsonb NOT NULL,
    recorder_name text DEFAULT ''::text NOT NULL,
    recorder_guid text DEFAULT ''::text NOT NULL,
    parser_version text DEFAULT '0.0'::text NOT NULL,
    duplicate_group_id uuid
);

COMMENT ON COLUMN log_instances.guild_id IS 'If set, that means it was a guild run.';

CREATE TABLE wow_server_realms (
    id uuid NOT NULL,
    server_id uuid NOT NULL,
    name text NOT NULL,
    created_by uuid,
    url text,
    description text DEFAULT ''::text NOT NULL
);

CREATE VIEW log_instances_guild AS
 SELECT li.id,
    li.realm_id,
    li.log_group_id,
    li.name,
    li.hashed_slug,
    li.guild_id,
    li.capabilities,
    li.versions,
    li.recorder_name,
    li.recorder_guid,
    li.duplicate_group_id,
    li.start_time,
    li.end_time,
    COALESCE(wsr.name, 'Unknown'::text) AS realm_name,
    g.name AS guild_name,
    g.realm_id AS guild_realm_id,
    g.created_at AS guild_created_at
   FROM ((public.log_instances li
     LEFT JOIN wow_server_realms wsr ON ((wsr.id = li.realm_id)))
     LEFT JOIN guilds g ON ((li.guild_id = g.id)));

CREATE TABLE parsed_log_group (
    id uuid NOT NULL
);

COMMENT ON TABLE parsed_log_group IS 'A parsed_log_group is a wow_log_group that has been processed and contains parsed logs. A duplicate allows deleting this one row to clear all parsed logs for a given wow_log_group.';

CREATE TABLE regression_fixtures (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    log_group_id uuid NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE regression_snapshots (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    fixture_id uuid NOT NULL,
    version text NOT NULL,
    snapshot jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    build_time text DEFAULT ''::text NOT NULL,
    matches_previous boolean,
    previous_snapshot_id uuid
);

CREATE TABLE retention_policies (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    server_id uuid,
    realm_id uuid,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_run_at timestamp with time zone,
    total_deleted bigint DEFAULT 0 NOT NULL,
    total_kept bigint DEFAULT 0 NOT NULL,
    CONSTRAINT retention_policies_scope CHECK ((((server_id IS NOT NULL) AND (realm_id IS NULL)) OR ((server_id IS NULL) AND (realm_id IS NOT NULL))))
);

CREATE TABLE retention_rules (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    policy_id uuid NOT NULL,
    priority integer NOT NULL,
    action text NOT NULL,
    conditions jsonb DEFAULT '[]'::jsonb NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT retention_rules_action_check CHECK ((action = ANY (ARRAY['keep'::text, 'delete'::text])))
);

CREATE UNLOGGED TABLE river_client (
    id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    paused_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT name_length CHECK (((char_length(id) > 0) AND (char_length(id) < 128)))
);

CREATE UNLOGGED TABLE river_client_queue (
    river_client_id text NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    max_workers bigint DEFAULT 0 NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    num_jobs_completed bigint DEFAULT 0 NOT NULL,
    num_jobs_running bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT name_length CHECK (((char_length(name) > 0) AND (char_length(name) < 128))),
    CONSTRAINT num_jobs_completed_zero_or_positive CHECK ((num_jobs_completed >= 0)),
    CONSTRAINT num_jobs_running_zero_or_positive CHECK ((num_jobs_running >= 0))
);

CREATE TABLE river_job (
    id bigint NOT NULL,
    state river_job_state DEFAULT 'available'::river_job_state NOT NULL,
    attempt smallint DEFAULT 0 NOT NULL,
    max_attempts smallint NOT NULL,
    attempted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    finalized_at timestamp with time zone,
    scheduled_at timestamp with time zone DEFAULT now() NOT NULL,
    priority smallint DEFAULT 1 NOT NULL,
    args jsonb NOT NULL,
    attempted_by text[],
    errors jsonb[],
    kind text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    queue text DEFAULT 'default'::text NOT NULL,
    tags character varying(255)[] DEFAULT '{}'::character varying[] NOT NULL,
    unique_key bytea,
    unique_states bit(8),
    CONSTRAINT finalized_or_finalized_at_null CHECK ((((finalized_at IS NULL) AND (state <> ALL (ARRAY['cancelled'::river_job_state, 'completed'::river_job_state, 'discarded'::river_job_state]))) OR ((finalized_at IS NOT NULL) AND (state = ANY (ARRAY['cancelled'::river_job_state, 'completed'::river_job_state, 'discarded'::river_job_state]))))),
    CONSTRAINT kind_length CHECK (((char_length(kind) > 0) AND (char_length(kind) < 128))),
    CONSTRAINT max_attempts_is_positive CHECK ((max_attempts > 0)),
    CONSTRAINT priority_in_range CHECK (((priority >= 1) AND (priority <= 4))),
    CONSTRAINT queue_length CHECK (((char_length(queue) > 0) AND (char_length(queue) < 128)))
);

CREATE SEQUENCE river_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE river_job_id_seq OWNED BY river_job.id;

CREATE UNLOGGED TABLE river_leader (
    elected_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    leader_id text NOT NULL,
    name text DEFAULT 'default'::text NOT NULL,
    CONSTRAINT leader_id_length CHECK (((char_length(leader_id) > 0) AND (char_length(leader_id) < 128))),
    CONSTRAINT name_length CHECK ((name = 'default'::text))
);

CREATE TABLE river_migration (
    line text NOT NULL,
    version bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT line_length CHECK (((char_length(line) > 0) AND (char_length(line) < 128))),
    CONSTRAINT version_gte_1 CHECK ((version >= 1))
);

CREATE TABLE river_queue (
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    paused_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE server_upload_meta (
    log_group_id uuid NOT NULL,
    instance_id text NOT NULL,
    instance_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    realm_id uuid,
    instance_token text
);

CREATE TABLE shared_views (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code text NOT NULL,
    hash text NOT NULL,
    instance_id uuid,
    payload jsonb NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    instance_slug text DEFAULT ''::text NOT NULL,
    CONSTRAINT shared_views_payload_max_10kb CHECK ((octet_length((payload)::text) <= 10240))
);

CREATE TABLE site_config (
    id boolean DEFAULT true NOT NULL,
    signups_enabled boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT site_config_id_check CHECK (id)
);

CREATE TABLE user_action_bar_slots (
    user_id uuid NOT NULL,
    slot_1 uuid,
    slot_2 uuid,
    slot_3 uuid,
    slot_4 uuid,
    slot_5 uuid,
    slot_6 uuid,
    slot_7 uuid,
    slot_8 uuid,
    slot_9 uuid,
    slot_0 uuid
);

CREATE TABLE user_auth_links (
    id uuid NOT NULL,
    linked_id text NOT NULL,
    user_id uuid NOT NULL,
    provider text NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE user_auth_session (
    id uuid NOT NULL,
    user_auth_id uuid NOT NULL,
    user_id uuid NOT NULL,
    access_token text NOT NULL,
    access_token_secret text NOT NULL,
    refresh_token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    jwt_id uuid DEFAULT gen_random_uuid() NOT NULL
);

CREATE TABLE user_panel_layouts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    title text NOT NULL,
    title_normalized text GENERATED ALWAYS AS (lower(title)) STORED,
    icon text DEFAULT 'INV_Misc_Book_09'::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    code text,
    CONSTRAINT user_panel_layouts_payload_size_chk CHECK ((octet_length((payload)::text) <= 10240)),
    CONSTRAINT user_panel_layouts_title_format_chk CHECK ((title ~ '^[A-Za-z0-9_\-\s]+$'::text))
);

CREATE TABLE user_passwords (
    user_auth_id uuid NOT NULL,
    password_hash text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    verification_token_hash text,
    verification_token_expires_at timestamp with time zone,
    verification_token_created_at timestamp with time zone,
    reset_token_hash text,
    reset_token_expires_at timestamp with time zone,
    reset_token_created_at timestamp with time zone
);

CREATE TABLE user_tracked_layouts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    layout_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE world (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE world_creature_spawn (
    guid integer NOT NULL,
    id integer DEFAULT 0 NOT NULL,
    id2 integer DEFAULT 0 NOT NULL,
    id3 integer DEFAULT 0 NOT NULL,
    id4 integer DEFAULT 0 NOT NULL,
    map integer DEFAULT 0 NOT NULL
);

CREATE TABLE world_creature_template (
    entry integer NOT NULL,
    display_id1 integer DEFAULT 0 NOT NULL,
    display_id2 integer DEFAULT 0 NOT NULL,
    display_id3 integer DEFAULT 0 NOT NULL,
    display_id4 integer DEFAULT 0 NOT NULL,
    mount_display_id integer DEFAULT 0 NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    subname text,
    level_min integer DEFAULT 0 NOT NULL,
    level_max integer DEFAULT 0 NOT NULL,
    health_min integer DEFAULT 0 NOT NULL,
    health_max integer DEFAULT 0 NOT NULL,
    mana_min integer DEFAULT 0 NOT NULL,
    mana_max integer DEFAULT 0 NOT NULL,
    armor integer DEFAULT 0 NOT NULL,
    dmg_min double precision DEFAULT 0 NOT NULL,
    dmg_max double precision DEFAULT 0 NOT NULL,
    dmg_school integer DEFAULT 0 NOT NULL,
    attack_power integer DEFAULT 0 NOT NULL,
    dmg_multiplier double precision DEFAULT 1 NOT NULL,
    base_attack_time integer DEFAULT 0 NOT NULL,
    ranged_attack_time integer DEFAULT 0 NOT NULL,
    unit_class integer DEFAULT 0 NOT NULL,
    unit_flags integer DEFAULT 0 NOT NULL,
    ranged_dmg_min double precision DEFAULT 0 NOT NULL,
    ranged_dmg_max double precision DEFAULT 0 NOT NULL,
    holy_res integer DEFAULT 0 NOT NULL,
    fire_res integer DEFAULT 0 NOT NULL,
    nature_res integer DEFAULT 0 NOT NULL,
    frost_res integer DEFAULT 0 NOT NULL,
    shadow_res integer DEFAULT 0 NOT NULL,
    arcane_res integer DEFAULT 0 NOT NULL,
    mechanic_immune_mask bigint DEFAULT 0 NOT NULL,
    school_immune_mask integer DEFAULT 0 NOT NULL,
    immunity_flags integer DEFAULT 0 NOT NULL
);

CREATE TABLE world_display_info (
    id integer NOT NULL,
    icon text DEFAULT ''::text NOT NULL
);

CREATE TABLE world_instance_template (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    abbreviation text,
    category instance_category NOT NULL,
    boss_count integer,
    background text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE world_instance_units (
    instance_id uuid NOT NULL,
    entry_id integer NOT NULL,
    override_name text,
    encounter_name text,
    boss boolean DEFAULT false NOT NULL,
    affiliation unit_affiliation DEFAULT 'hostile'::unit_affiliation NOT NULL
);

CREATE TABLE world_instance_zone_names (
    instance_id uuid NOT NULL,
    zone_name text NOT NULL,
    display_name text NOT NULL
);

CREATE TABLE world_item_enchantment (
    entry integer NOT NULL,
    ench integer NOT NULL,
    chance double precision DEFAULT 0 NOT NULL
);

CREATE TABLE world_item_template (
    entry integer NOT NULL,
    class integer DEFAULT 0 NOT NULL,
    subclass integer DEFAULT 0 NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    display_id integer DEFAULT 0 NOT NULL,
    quality integer DEFAULT 0 NOT NULL,
    flags integer DEFAULT 0 NOT NULL,
    buy_count integer DEFAULT 0 NOT NULL,
    buy_price integer DEFAULT 0 NOT NULL,
    sell_price integer DEFAULT 0 NOT NULL,
    inventory_type integer DEFAULT 0 NOT NULL,
    allowable_class integer DEFAULT '-1'::integer NOT NULL,
    allowable_race integer DEFAULT '-1'::integer NOT NULL,
    item_level integer DEFAULT 0 NOT NULL,
    required_level integer DEFAULT 0 NOT NULL,
    required_skill integer DEFAULT 0 NOT NULL,
    required_skill_rank integer DEFAULT 0 NOT NULL,
    required_spell integer DEFAULT 0 NOT NULL,
    required_honor_rank integer DEFAULT 0 NOT NULL,
    required_city_rank integer DEFAULT 0 NOT NULL,
    required_reputation_faction integer DEFAULT 0 NOT NULL,
    required_reputation_rank integer DEFAULT 0 NOT NULL,
    max_count integer DEFAULT 0 NOT NULL,
    stackable integer DEFAULT 1 NOT NULL,
    container_slots integer DEFAULT 0 NOT NULL,
    stat_type1 integer DEFAULT 0 NOT NULL,
    stat_value1 integer DEFAULT 0 NOT NULL,
    stat_type2 integer DEFAULT 0 NOT NULL,
    stat_value2 integer DEFAULT 0 NOT NULL,
    stat_type3 integer DEFAULT 0 NOT NULL,
    stat_value3 integer DEFAULT 0 NOT NULL,
    stat_type4 integer DEFAULT 0 NOT NULL,
    stat_value4 integer DEFAULT 0 NOT NULL,
    stat_type5 integer DEFAULT 0 NOT NULL,
    stat_value5 integer DEFAULT 0 NOT NULL,
    stat_type6 integer DEFAULT 0 NOT NULL,
    stat_value6 integer DEFAULT 0 NOT NULL,
    stat_type7 integer DEFAULT 0 NOT NULL,
    stat_value7 integer DEFAULT 0 NOT NULL,
    stat_type8 integer DEFAULT 0 NOT NULL,
    stat_value8 integer DEFAULT 0 NOT NULL,
    stat_type9 integer DEFAULT 0 NOT NULL,
    stat_value9 integer DEFAULT 0 NOT NULL,
    stat_type10 integer DEFAULT 0 NOT NULL,
    stat_value10 integer DEFAULT 0 NOT NULL,
    delay integer DEFAULT 0 NOT NULL,
    range_mod double precision DEFAULT 0 NOT NULL,
    ammo_type integer DEFAULT 0 NOT NULL,
    dmg_min1 double precision DEFAULT 0 NOT NULL,
    dmg_max1 double precision DEFAULT 0 NOT NULL,
    dmg_type1 integer DEFAULT 0 NOT NULL,
    dmg_min2 double precision DEFAULT 0 NOT NULL,
    dmg_max2 double precision DEFAULT 0 NOT NULL,
    dmg_type2 integer DEFAULT 0 NOT NULL,
    dmg_min3 double precision DEFAULT 0 NOT NULL,
    dmg_max3 double precision DEFAULT 0 NOT NULL,
    dmg_type3 integer DEFAULT 0 NOT NULL,
    dmg_min4 double precision DEFAULT 0 NOT NULL,
    dmg_max4 double precision DEFAULT 0 NOT NULL,
    dmg_type4 integer DEFAULT 0 NOT NULL,
    dmg_min5 double precision DEFAULT 0 NOT NULL,
    dmg_max5 double precision DEFAULT 0 NOT NULL,
    dmg_type5 integer DEFAULT 0 NOT NULL,
    block integer DEFAULT 0 NOT NULL,
    armor integer DEFAULT 0 NOT NULL,
    holy_res integer DEFAULT 0 NOT NULL,
    fire_res integer DEFAULT 0 NOT NULL,
    nature_res integer DEFAULT 0 NOT NULL,
    frost_res integer DEFAULT 0 NOT NULL,
    shadow_res integer DEFAULT 0 NOT NULL,
    arcane_res integer DEFAULT 0 NOT NULL,
    spellid_1 integer DEFAULT 0 NOT NULL,
    spelltrigger_1 integer DEFAULT 0 NOT NULL,
    spellcharges_1 integer DEFAULT 0 NOT NULL,
    spellppmrate_1 double precision DEFAULT 0 NOT NULL,
    spellcooldown_1 integer DEFAULT '-1'::integer NOT NULL,
    spellcategory_1 integer DEFAULT 0 NOT NULL,
    spellcategorycooldown_1 integer DEFAULT '-1'::integer NOT NULL,
    spellid_2 integer DEFAULT 0 NOT NULL,
    spelltrigger_2 integer DEFAULT 0 NOT NULL,
    spellcharges_2 integer DEFAULT 0 NOT NULL,
    spellppmrate_2 double precision DEFAULT 0 NOT NULL,
    spellcooldown_2 integer DEFAULT '-1'::integer NOT NULL,
    spellcategory_2 integer DEFAULT 0 NOT NULL,
    spellcategorycooldown_2 integer DEFAULT '-1'::integer NOT NULL,
    spellid_3 integer DEFAULT 0 NOT NULL,
    spelltrigger_3 integer DEFAULT 0 NOT NULL,
    spellcharges_3 integer DEFAULT 0 NOT NULL,
    spellppmrate_3 double precision DEFAULT 0 NOT NULL,
    spellcooldown_3 integer DEFAULT '-1'::integer NOT NULL,
    spellcategory_3 integer DEFAULT 0 NOT NULL,
    spellcategorycooldown_3 integer DEFAULT '-1'::integer NOT NULL,
    spellid_4 integer DEFAULT 0 NOT NULL,
    spelltrigger_4 integer DEFAULT 0 NOT NULL,
    spellcharges_4 integer DEFAULT 0 NOT NULL,
    spellppmrate_4 double precision DEFAULT 0 NOT NULL,
    spellcooldown_4 integer DEFAULT '-1'::integer NOT NULL,
    spellcategory_4 integer DEFAULT 0 NOT NULL,
    spellcategorycooldown_4 integer DEFAULT '-1'::integer NOT NULL,
    spellid_5 integer DEFAULT 0 NOT NULL,
    spelltrigger_5 integer DEFAULT 0 NOT NULL,
    spellcharges_5 integer DEFAULT 0 NOT NULL,
    spellppmrate_5 double precision DEFAULT 0 NOT NULL,
    spellcooldown_5 integer DEFAULT 0 NOT NULL,
    spellcategory_5 integer DEFAULT 0 NOT NULL,
    spellcategorycooldown_5 integer DEFAULT 0 NOT NULL,
    bonding integer DEFAULT 0 NOT NULL,
    page_text integer DEFAULT 0 NOT NULL,
    page_language integer DEFAULT 0 NOT NULL,
    page_material integer DEFAULT 0 NOT NULL,
    start_quest integer DEFAULT 0 NOT NULL,
    lock_id integer DEFAULT 0 NOT NULL,
    material integer DEFAULT 0 NOT NULL,
    sheath integer DEFAULT 0 NOT NULL,
    random_property integer DEFAULT 0 NOT NULL,
    set_id integer DEFAULT 0 NOT NULL,
    max_durability integer DEFAULT 0 NOT NULL,
    area_bound integer DEFAULT 0 NOT NULL,
    map_bound integer DEFAULT 0 NOT NULL,
    duration integer DEFAULT 0 NOT NULL,
    bag_family integer DEFAULT 0 NOT NULL,
    disenchant_id integer DEFAULT 0 NOT NULL,
    food_type integer DEFAULT 0 NOT NULL,
    min_money_loot integer DEFAULT 0 NOT NULL,
    max_money_loot integer DEFAULT 0 NOT NULL,
    wrapped_gift integer DEFAULT 0 NOT NULL,
    extra_flags integer DEFAULT 0 NOT NULL,
    other_team_entry integer DEFAULT 0 NOT NULL,
    script_name text,
    patch text,
    tooltip_set_id integer DEFAULT 0 NOT NULL,
    random_suffix integer DEFAULT 0 NOT NULL,
    totem_category integer DEFAULT 0 NOT NULL,
    socket_color_1 integer DEFAULT 0 NOT NULL,
    socket_content_1 integer DEFAULT 0 NOT NULL,
    socket_color_2 integer DEFAULT 0 NOT NULL,
    socket_content_2 integer DEFAULT 0 NOT NULL,
    socket_color_3 integer DEFAULT 0 NOT NULL,
    socket_content_3 integer DEFAULT 0 NOT NULL,
    socket_bonus integer DEFAULT 0 NOT NULL,
    gem_properties integer DEFAULT 0 NOT NULL,
    required_disenchant_skill integer DEFAULT '-1'::integer NOT NULL,
    armor_damage_modifier double precision DEFAULT 0 NOT NULL,
    scaling_stat_distribution integer DEFAULT 0 NOT NULL,
    scaling_stat_value integer DEFAULT 0 NOT NULL,
    item_limit_category integer DEFAULT 0 NOT NULL,
    holiday_id integer DEFAULT 0 NOT NULL
);

CREATE TABLE world_server (
    server_id uuid NOT NULL,
    world_id uuid NOT NULL
);

CREATE TABLE world_spell_area (
    spell integer NOT NULL,
    area integer NOT NULL,
    quest_start integer DEFAULT 0 NOT NULL,
    quest_start_active integer DEFAULT 0 NOT NULL,
    quest_end integer DEFAULT 0 NOT NULL,
    aura_spell integer DEFAULT 0 NOT NULL,
    racemask integer DEFAULT 0 NOT NULL,
    gender integer DEFAULT 2 NOT NULL,
    autocast integer DEFAULT 0 NOT NULL
);

CREATE TABLE world_spell_chain (
    spell_id integer NOT NULL,
    prev_spell integer DEFAULT 0 NOT NULL,
    first_spell integer DEFAULT 0 NOT NULL,
    rank integer DEFAULT 0 NOT NULL,
    req_spell integer DEFAULT 0 NOT NULL
);

CREATE TABLE world_spell_group (
    group_id integer NOT NULL,
    group_spell_id integer DEFAULT 0 NOT NULL,
    spell_id integer NOT NULL
);

CREATE TABLE world_spell_threat (
    entry integer NOT NULL,
    threat integer DEFAULT 0 NOT NULL,
    multiplier double precision DEFAULT 1 NOT NULL,
    ap_bonus double precision DEFAULT 0 NOT NULL
);

CREATE TABLE wow_log_groups (
    id uuid NOT NULL,
    owner uuid NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    log_type log_type DEFAULT 'v1'::log_type NOT NULL
);

CREATE TABLE wow_server_upload_keys (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    realm_id uuid NOT NULL,
    secret_hash text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone,
    created_by uuid
);

CREATE TABLE wow_servers (
    id uuid NOT NULL,
    name text NOT NULL,
    created_by uuid,
    url text,
    description text DEFAULT ''::text NOT NULL
);

ALTER TABLE ONLY river_job ALTER COLUMN id SET DEFAULT nextval('river_job_id_seq'::regclass);

ALTER TABLE ONLY authz_schema_migrations
    ADD CONSTRAINT authz_schema_migrations_pkey PRIMARY KEY (version);

ALTER TABLE ONLY data_grants
    ADD CONSTRAINT data_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY data_grants
    ADD CONSTRAINT data_grants_user_id_source_key UNIQUE (user_id, source);

ALTER TABLE ONLY dbc_item_display_info
    ADD CONSTRAINT dbc_item_display_info_pkey PRIMARY KEY (id);

ALTER TABLE ONLY dbc_item_random_properties
    ADD CONSTRAINT dbc_item_random_properties_pkey PRIMARY KEY (id);

ALTER TABLE ONLY dbc_item_set_bonus
    ADD CONSTRAINT dbc_item_set_bonus_pkey PRIMARY KEY (set_id, threshold, spell_id);

ALTER TABLE ONLY dbc_item_set_item
    ADD CONSTRAINT dbc_item_set_item_pkey PRIMARY KEY (set_id, item_entry);

ALTER TABLE ONLY dbc_item_set
    ADD CONSTRAINT dbc_item_set_pkey PRIMARY KEY (id);

ALTER TABLE ONLY dbc_spell_item_enchantment
    ADD CONSTRAINT dbc_spell_item_enchantment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY game_players
    ADD CONSTRAINT game_players_pkey PRIMARY KEY (id, realm_id);

ALTER TABLE ONLY guild_join_requests
    ADD CONSTRAINT guild_join_requests_guild_id_user_id_key UNIQUE (guild_id, user_id);

ALTER TABLE ONLY guild_join_requests
    ADD CONSTRAINT guild_join_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY guild_page_panels
    ADD CONSTRAINT guild_page_panels_pkey PRIMARY KEY (id);

ALTER TABLE ONLY guild_page_tabs
    ADD CONSTRAINT guild_page_tabs_page_id_slug_key UNIQUE (page_id, slug);

ALTER TABLE ONLY guild_page_tabs
    ADD CONSTRAINT guild_page_tabs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY guild_pages
    ADD CONSTRAINT guild_pages_guild_id_key UNIQUE (guild_id);

ALTER TABLE ONLY guild_pages
    ADD CONSTRAINT guild_pages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY guild_settings
    ADD CONSTRAINT guild_settings_pkey PRIMARY KEY (guild_id);

ALTER TABLE ONLY guilds
    ADD CONSTRAINT guilds_pkey PRIMARY KEY (id);

ALTER TABLE ONLY guilds
    ADD CONSTRAINT guilds_realm_id_name_key UNIQUE (realm_id, name);

ALTER TABLE ONLY instance_loot
    ADD CONSTRAINT instance_loot_pkey PRIMARY KEY (id);

ALTER TABLE ONLY instance_speedruns
    ADD CONSTRAINT instance_speedruns_pkey PRIMARY KEY (instance_id);

ALTER TABLE ONLY leaderboard_version_requirements
    ADD CONSTRAINT leaderboard_version_requirements_pkey PRIMARY KEY (instance_name);

ALTER TABLE ONLY log_file
    ADD CONSTRAINT log_file_pkey PRIMARY KEY (id);

ALTER TABLE ONLY log_instance_encounter_damage_unit_summary
    ADD CONSTRAINT log_instance_encounter_damage_unit_summary_pkey PRIMARY KEY (encounter_id, unit_guid);

ALTER TABLE ONLY log_instance_encounter_hostiles
    ADD CONSTRAINT log_instance_encounter_hostiles_pkey PRIMARY KEY (encounter_id, id);

ALTER TABLE ONLY log_instance_encounters
    ADD CONSTRAINT log_instance_encounters_pkey PRIMARY KEY (id);

ALTER TABLE ONLY log_instance_units
    ADD CONSTRAINT log_instance_units_pkey PRIMARY KEY (instance_id, unit_guid);

ALTER TABLE ONLY log_instance_youtube_timestamped
    ADD CONSTRAINT log_instance_youtube_timestamped_pkey PRIMARY KEY (id);

ALTER TABLE ONLY log_instances
    ADD CONSTRAINT log_instances_pkey PRIMARY KEY (id);

ALTER TABLE ONLY parsed_log_group
    ADD CONSTRAINT parsed_log_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY regression_fixtures
    ADD CONSTRAINT regression_fixtures_log_group_id_key UNIQUE (log_group_id);

ALTER TABLE ONLY regression_fixtures
    ADD CONSTRAINT regression_fixtures_pkey PRIMARY KEY (id);

ALTER TABLE ONLY regression_snapshots
    ADD CONSTRAINT regression_snapshots_pkey PRIMARY KEY (id);

ALTER TABLE ONLY retention_policies
    ADD CONSTRAINT retention_policies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY retention_policies
    ADD CONSTRAINT retention_policies_unique_realm UNIQUE (realm_id);

ALTER TABLE ONLY retention_policies
    ADD CONSTRAINT retention_policies_unique_server UNIQUE (server_id);

ALTER TABLE ONLY retention_rules
    ADD CONSTRAINT retention_rules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY retention_rules
    ADD CONSTRAINT retention_rules_unique_priority UNIQUE (policy_id, priority);

ALTER TABLE ONLY river_client
    ADD CONSTRAINT river_client_pkey PRIMARY KEY (id);

ALTER TABLE ONLY river_client_queue
    ADD CONSTRAINT river_client_queue_pkey PRIMARY KEY (river_client_id, name);

ALTER TABLE ONLY river_job
    ADD CONSTRAINT river_job_pkey PRIMARY KEY (id);

ALTER TABLE ONLY river_leader
    ADD CONSTRAINT river_leader_pkey PRIMARY KEY (name);

ALTER TABLE ONLY river_migration
    ADD CONSTRAINT river_migration_pkey1 PRIMARY KEY (line, version);

ALTER TABLE ONLY river_queue
    ADD CONSTRAINT river_queue_pkey PRIMARY KEY (name);

ALTER TABLE ONLY server_upload_meta
    ADD CONSTRAINT server_upload_meta_pkey PRIMARY KEY (log_group_id);

ALTER TABLE ONLY shared_views
    ADD CONSTRAINT shared_views_code_key UNIQUE (code);

ALTER TABLE ONLY shared_views
    ADD CONSTRAINT shared_views_instance_hash_unique UNIQUE (instance_id, hash);

ALTER TABLE ONLY shared_views
    ADD CONSTRAINT shared_views_pkey PRIMARY KEY (id);

ALTER TABLE ONLY site_config
    ADD CONSTRAINT site_config_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_action_bar_slots
    ADD CONSTRAINT user_action_bar_slots_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY user_auth_links
    ADD CONSTRAINT user_auth_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_auth_session
    ADD CONSTRAINT user_auth_session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_panel_layouts
    ADD CONSTRAINT user_panel_layouts_code_key UNIQUE (code);

ALTER TABLE ONLY user_panel_layouts
    ADD CONSTRAINT user_panel_layouts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_passwords
    ADD CONSTRAINT user_passwords_pkey PRIMARY KEY (user_auth_id);

ALTER TABLE ONLY user_tracked_layouts
    ADD CONSTRAINT user_tracked_layouts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_tracked_layouts
    ADD CONSTRAINT user_tracked_layouts_unique UNIQUE (user_id, layout_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY world_creature_spawn
    ADD CONSTRAINT world_creature_spawn_pkey PRIMARY KEY (guid);

ALTER TABLE ONLY world_creature_template
    ADD CONSTRAINT world_creature_template_pkey PRIMARY KEY (entry);

ALTER TABLE ONLY world_display_info
    ADD CONSTRAINT world_display_info_pkey PRIMARY KEY (id);

ALTER TABLE ONLY world_instance_template
    ADD CONSTRAINT world_instance_template_name_key UNIQUE (name);

ALTER TABLE ONLY world_instance_template
    ADD CONSTRAINT world_instance_template_pkey PRIMARY KEY (id);

ALTER TABLE ONLY world_instance_units
    ADD CONSTRAINT world_instance_units_pkey PRIMARY KEY (instance_id, entry_id);

ALTER TABLE ONLY world_instance_zone_names
    ADD CONSTRAINT world_instance_zone_names_pkey PRIMARY KEY (instance_id, zone_name);

ALTER TABLE ONLY world_item_enchantment
    ADD CONSTRAINT world_item_enchantment_pkey PRIMARY KEY (entry, ench);

ALTER TABLE ONLY world_item_template
    ADD CONSTRAINT world_item_template_pkey PRIMARY KEY (entry);

ALTER TABLE ONLY world
    ADD CONSTRAINT world_name_key UNIQUE (name);

ALTER TABLE ONLY world
    ADD CONSTRAINT world_pkey PRIMARY KEY (id);

ALTER TABLE ONLY world_server
    ADD CONSTRAINT world_server_pkey PRIMARY KEY (server_id, world_id);

ALTER TABLE ONLY world_spell_area
    ADD CONSTRAINT world_spell_area_pkey PRIMARY KEY (spell, area);

ALTER TABLE ONLY world_spell_chain
    ADD CONSTRAINT world_spell_chain_pkey PRIMARY KEY (spell_id);

ALTER TABLE ONLY world_spell_group
    ADD CONSTRAINT world_spell_group_pkey PRIMARY KEY (group_id, spell_id);

ALTER TABLE ONLY world_spell_threat
    ADD CONSTRAINT world_spell_threat_pkey PRIMARY KEY (entry);

ALTER TABLE ONLY wow_log_groups
    ADD CONSTRAINT wow_log_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY wow_server_realms
    ADD CONSTRAINT wow_server_realms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY wow_server_upload_keys
    ADD CONSTRAINT wow_server_upload_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY wow_servers
    ADD CONSTRAINT wow_servers_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX files_unique_owner_hash ON log_file USING btree (owner, hash);

CREATE INDEX game_players_player_and_realm ON game_players USING btree (name, realm_id);

CREATE INDEX idx_data_grants_user_id ON data_grants USING btree (user_id);

CREATE INDEX idx_guild_join_requests_guild ON guild_join_requests USING btree (guild_id);

CREATE INDEX idx_guild_page_panels_tab ON guild_page_panels USING btree (tab_id);

CREATE INDEX idx_guild_page_tabs_page ON guild_page_tabs USING btree (page_id);

CREATE INDEX idx_instance_loot_instance ON instance_loot USING btree (instance_id);

CREATE INDEX idx_instance_loot_item ON instance_loot USING btree (item_id);

CREATE INDEX idx_instance_loot_received ON instance_loot USING btree (received_guid);

CREATE INDEX idx_instance_speedruns_leaderboard ON instance_speedruns USING btree (instance_name, duration_ms) WHERE (qualified = true);

CREATE INDEX idx_instance_speedruns_realm ON instance_speedruns USING btree (realm_id, instance_name);

CREATE INDEX idx_log_instance_encounters_instance_id ON log_instance_encounters USING btree (instance_id);

CREATE INDEX idx_log_instance_players_instance_id ON log_instance_players USING btree (instance_id);

CREATE INDEX idx_log_instances_duplicate_group ON log_instances USING btree (duplicate_group_id) WHERE (duplicate_group_id IS NOT NULL);

CREATE INDEX idx_log_instances_log_group_id ON log_instances USING btree (log_group_id);

CREATE INDEX idx_log_instances_realm_id ON log_instances USING btree (realm_id);

CREATE INDEX idx_regression_snapshots_fixture ON regression_snapshots USING btree (fixture_id, created_at DESC);

CREATE INDEX idx_server_upload_meta_lookup ON server_upload_meta USING btree (instance_id, instance_name, realm_id);

CREATE INDEX idx_server_upload_meta_token ON server_upload_meta USING btree (instance_token) WHERE (instance_token IS NOT NULL);

CREATE INDEX idx_shared_views_code ON shared_views USING btree (code);

CREATE INDEX idx_shared_views_instance_hash ON shared_views USING btree (instance_id, hash);

CREATE INDEX idx_upload_keys_realm ON wow_server_upload_keys USING btree (realm_id);

CREATE INDEX idx_user_panel_layouts_code ON user_panel_layouts USING btree (code);

CREATE INDEX idx_world_creature_spawn_id ON world_creature_spawn USING btree (id);

CREATE INDEX idx_world_creature_template_name ON world_creature_template USING btree (name);

CREATE INDEX idx_world_instance_zone_name ON world_instance_zone_names USING btree (zone_name) INCLUDE (instance_id);

CREATE INDEX idx_world_item_template_name ON world_item_template USING btree (name);

CREATE UNIQUE INDEX log_instance_youtube_timestamped_instance_id_idx ON log_instance_youtube_timestamped USING btree (log_instance_id) WHERE (log_instance_id IS NOT NULL);

CREATE UNIQUE INDEX log_instance_youtube_timestamped_slug_idx ON log_instance_youtube_timestamped USING btree (instance_slug) WHERE (instance_slug IS NOT NULL);

CREATE UNIQUE INDEX log_instances_hashed_slug_idx ON log_instances USING btree (hashed_slug) WHERE (hashed_slug IS NOT NULL);

CREATE INDEX river_job_args_index ON river_job USING gin (args);

CREATE INDEX river_job_kind ON river_job USING btree (kind);

CREATE INDEX river_job_metadata_index ON river_job USING gin (metadata);

CREATE INDEX river_job_prioritized_fetching_index ON river_job USING btree (state, queue, priority, scheduled_at, id);

CREATE INDEX river_job_state_and_finalized_at_index ON river_job USING btree (state, finalized_at) WHERE (finalized_at IS NOT NULL);

CREATE UNIQUE INDEX river_job_unique_idx ON river_job USING btree (unique_key) WHERE ((unique_key IS NOT NULL) AND (unique_states IS NOT NULL) AND river_job_state_in_bitmask(unique_states, state));

CREATE UNIQUE INDEX user_auths_unique_linked_id ON user_auth_links USING btree (lower(linked_id), provider);

CREATE UNIQUE INDEX user_panel_layouts_user_title_ci_uidx ON user_panel_layouts USING btree (user_id, title_normalized) WHERE (user_id IS NOT NULL);

CREATE TRIGGER trg_cleanup_after_soft_delete AFTER UPDATE OF user_id ON user_panel_layouts FOR EACH ROW WHEN ((new.user_id IS NULL)) EXECUTE FUNCTION cleanup_orphaned_layout();

CREATE TRIGGER trg_cleanup_after_untrack AFTER DELETE ON user_tracked_layouts FOR EACH ROW EXECUTE FUNCTION cleanup_orphaned_layout();

CREATE TRIGGER trg_reattach_by_slug AFTER INSERT ON log_instances FOR EACH ROW EXECUTE FUNCTION reattach_by_slug();

CREATE TRIGGER trigger_insert_default_data_grant AFTER INSERT ON users FOR EACH ROW EXECUTE FUNCTION insert_default_data_grant();

ALTER TABLE ONLY data_grants
    ADD CONSTRAINT data_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY game_players
    ADD CONSTRAINT game_players_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE SET NULL;

ALTER TABLE ONLY game_players
    ADD CONSTRAINT game_players_realm_id_fkey FOREIGN KEY (realm_id) REFERENCES wow_server_realms(id) ON DELETE CASCADE;

ALTER TABLE ONLY game_players
    ADD CONSTRAINT game_players_updated_from_instance_fkey FOREIGN KEY (updated_from_instance) REFERENCES log_instances(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY guild_join_requests
    ADD CONSTRAINT guild_join_requests_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;

ALTER TABLE ONLY guild_join_requests
    ADD CONSTRAINT guild_join_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY guild_page_panels
    ADD CONSTRAINT guild_page_panels_tab_id_fkey FOREIGN KEY (tab_id) REFERENCES guild_page_tabs(id) ON DELETE CASCADE;

ALTER TABLE ONLY guild_page_tabs
    ADD CONSTRAINT guild_page_tabs_page_id_fkey FOREIGN KEY (page_id) REFERENCES guild_pages(id) ON DELETE CASCADE;

ALTER TABLE ONLY guild_pages
    ADD CONSTRAINT guild_pages_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;

ALTER TABLE ONLY guild_settings
    ADD CONSTRAINT guild_settings_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;

ALTER TABLE ONLY guilds
    ADD CONSTRAINT guilds_realm_id_fkey FOREIGN KEY (realm_id) REFERENCES wow_server_realms(id);

ALTER TABLE ONLY instance_loot
    ADD CONSTRAINT instance_loot_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES log_instances(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY instance_speedruns
    ADD CONSTRAINT instance_speedruns_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id);

ALTER TABLE ONLY instance_speedruns
    ADD CONSTRAINT instance_speedruns_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES log_instances(id) ON DELETE CASCADE;

ALTER TABLE ONLY instance_speedruns
    ADD CONSTRAINT instance_speedruns_realm_id_fkey FOREIGN KEY (realm_id) REFERENCES wow_server_realms(id);

ALTER TABLE ONLY log_file
    ADD CONSTRAINT log_file_owner_fkey FOREIGN KEY (owner) REFERENCES users(id);

ALTER TABLE ONLY log_file
    ADD CONSTRAINT log_file_wow_log_id_fkey FOREIGN KEY (wow_log_id) REFERENCES wow_log_groups(id) ON DELETE CASCADE;

ALTER TABLE ONLY log_instance_encounter_damage_unit_summary
    ADD CONSTRAINT log_instance_encounter_damage_unit_summary_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES log_instance_encounters(id) ON DELETE CASCADE;

ALTER TABLE ONLY log_instance_encounter_hostiles
    ADD CONSTRAINT log_instance_encounter_hostiles_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES log_instance_encounters(id) ON DELETE CASCADE;

ALTER TABLE ONLY log_instance_encounters
    ADD CONSTRAINT log_instance_encounters_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES log_instances(id) ON DELETE CASCADE;

ALTER TABLE ONLY log_instance_events
    ADD CONSTRAINT log_instance_events_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES log_instances(id) ON DELETE CASCADE;

ALTER TABLE ONLY log_instance_players
    ADD CONSTRAINT log_instance_players_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id);

ALTER TABLE ONLY log_instance_players
    ADD CONSTRAINT log_instance_players_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES log_instances(id) ON DELETE CASCADE;

ALTER TABLE ONLY log_instance_units
    ADD CONSTRAINT log_instance_units_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES log_instances(id) ON DELETE CASCADE;

ALTER TABLE ONLY log_instance_youtube_timestamped
    ADD CONSTRAINT log_instance_youtube_timestamped_log_instance_id_fkey FOREIGN KEY (log_instance_id) REFERENCES log_instances(id) ON DELETE SET NULL;

ALTER TABLE ONLY log_instances
    ADD CONSTRAINT log_instances_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id);

ALTER TABLE ONLY log_instances
    ADD CONSTRAINT log_instances_log_group_id_fkey FOREIGN KEY (log_group_id) REFERENCES parsed_log_group(id) ON DELETE CASCADE;

ALTER TABLE ONLY log_instances
    ADD CONSTRAINT log_instances_realm_id_fkey FOREIGN KEY (realm_id) REFERENCES wow_server_realms(id);

ALTER TABLE ONLY parsed_log_group
    ADD CONSTRAINT parsed_log_group_id_fkey FOREIGN KEY (id) REFERENCES wow_log_groups(id) ON DELETE CASCADE;

ALTER TABLE ONLY regression_fixtures
    ADD CONSTRAINT regression_fixtures_log_group_id_fkey FOREIGN KEY (log_group_id) REFERENCES wow_log_groups(id) ON DELETE CASCADE;

ALTER TABLE ONLY regression_snapshots
    ADD CONSTRAINT regression_snapshots_fixture_id_fkey FOREIGN KEY (fixture_id) REFERENCES regression_fixtures(id) ON DELETE CASCADE;

ALTER TABLE ONLY regression_snapshots
    ADD CONSTRAINT regression_snapshots_previous_snapshot_id_fkey FOREIGN KEY (previous_snapshot_id) REFERENCES regression_snapshots(id) ON DELETE SET NULL;

ALTER TABLE ONLY retention_policies
    ADD CONSTRAINT retention_policies_realm_id_fkey FOREIGN KEY (realm_id) REFERENCES wow_server_realms(id) ON DELETE CASCADE;

ALTER TABLE ONLY retention_policies
    ADD CONSTRAINT retention_policies_server_id_fkey FOREIGN KEY (server_id) REFERENCES wow_servers(id) ON DELETE CASCADE;

ALTER TABLE ONLY retention_rules
    ADD CONSTRAINT retention_rules_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES retention_policies(id) ON DELETE CASCADE;

ALTER TABLE ONLY river_client_queue
    ADD CONSTRAINT river_client_queue_river_client_id_fkey FOREIGN KEY (river_client_id) REFERENCES river_client(id) ON DELETE CASCADE;

ALTER TABLE ONLY server_upload_meta
    ADD CONSTRAINT server_upload_meta_log_group_id_fkey FOREIGN KEY (log_group_id) REFERENCES wow_log_groups(id) ON DELETE CASCADE;

ALTER TABLE ONLY server_upload_meta
    ADD CONSTRAINT server_upload_meta_realm_id_fkey FOREIGN KEY (realm_id) REFERENCES wow_server_realms(id) ON DELETE CASCADE;

ALTER TABLE ONLY shared_views
    ADD CONSTRAINT shared_views_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE ONLY shared_views
    ADD CONSTRAINT shared_views_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES log_instances(id) ON DELETE SET NULL;

ALTER TABLE ONLY user_action_bar_slots
    ADD CONSTRAINT user_action_bar_slots_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_auth_links
    ADD CONSTRAINT user_auth_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY user_auth_session
    ADD CONSTRAINT user_auth_session_user_auth_id_fkey FOREIGN KEY (user_auth_id) REFERENCES user_auth_links(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_auth_session
    ADD CONSTRAINT user_auth_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY user_panel_layouts
    ADD CONSTRAINT user_panel_layouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_passwords
    ADD CONSTRAINT user_passwords_user_auth_id_fkey FOREIGN KEY (user_auth_id) REFERENCES user_auth_links(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_tracked_layouts
    ADD CONSTRAINT user_tracked_layouts_layout_id_fkey FOREIGN KEY (layout_id) REFERENCES user_panel_layouts(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_tracked_layouts
    ADD CONSTRAINT user_tracked_layouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY users
    ADD CONSTRAINT users_default_desktop_layout_id_fkey FOREIGN KEY (default_desktop_layout_id) REFERENCES user_panel_layouts(id) ON DELETE SET NULL;

ALTER TABLE ONLY users
    ADD CONSTRAINT users_default_mobile_layout_id_fkey FOREIGN KEY (default_mobile_layout_id) REFERENCES user_panel_layouts(id) ON DELETE SET NULL;

ALTER TABLE ONLY world_instance_units
    ADD CONSTRAINT world_instance_units_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES world_instance_template(id) ON DELETE CASCADE;

ALTER TABLE ONLY world_instance_zone_names
    ADD CONSTRAINT world_instance_zone_names_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES world_instance_template(id) ON DELETE CASCADE;

ALTER TABLE ONLY world_server
    ADD CONSTRAINT world_server_server_id_fkey FOREIGN KEY (server_id) REFERENCES wow_servers(id) ON DELETE CASCADE;

ALTER TABLE ONLY world_server
    ADD CONSTRAINT world_server_world_id_fkey FOREIGN KEY (world_id) REFERENCES world(id) ON DELETE CASCADE;

ALTER TABLE ONLY wow_log_groups
    ADD CONSTRAINT wow_log_groups_owner_fkey FOREIGN KEY (owner) REFERENCES users(id);

ALTER TABLE ONLY wow_server_realms
    ADD CONSTRAINT wow_server_realms_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);

ALTER TABLE ONLY wow_server_realms
    ADD CONSTRAINT wow_server_realms_server_id_fkey FOREIGN KEY (server_id) REFERENCES wow_servers(id) ON DELETE CASCADE;

ALTER TABLE ONLY wow_server_upload_keys
    ADD CONSTRAINT wow_server_upload_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);

ALTER TABLE ONLY wow_server_upload_keys
    ADD CONSTRAINT wow_server_upload_keys_realm_id_fkey FOREIGN KEY (realm_id) REFERENCES wow_server_realms(id) ON DELETE CASCADE;

ALTER TABLE ONLY wow_servers
    ADD CONSTRAINT wow_servers_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);


