// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/Emyrk/chronicle/combatlog/parser/guid"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InstanceCategory string

const (
	InstanceCategoryRaid    InstanceCategory = "raid"
	InstanceCategoryDungeon InstanceCategory = "dungeon"
	InstanceCategoryPvp     InstanceCategory = "pvp"
)

func (e *InstanceCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstanceCategory(s)
	case string:
		*e = InstanceCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for InstanceCategory: %T", src)
	}
	return nil
}

type NullInstanceCategory struct {
	InstanceCategory InstanceCategory `json:"instance_category"`
	Valid            bool             `json:"valid"` // Valid is true if InstanceCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstanceCategory) Scan(value interface{}) error {
	if value == nil {
		ns.InstanceCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstanceCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstanceCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstanceCategory), nil
}

func (e InstanceCategory) Valid() bool {
	switch e {
	case InstanceCategoryRaid,
		InstanceCategoryDungeon,
		InstanceCategoryPvp:
		return true
	}
	return false
}

func AllInstanceCategoryValues() []InstanceCategory {
	return []InstanceCategory{
		InstanceCategoryRaid,
		InstanceCategoryDungeon,
		InstanceCategoryPvp,
	}
}

type ItemEffectType string

const (
	ItemEffectTypeOnUse   ItemEffectType = "on_use"
	ItemEffectTypeOnEquip ItemEffectType = "on_equip"
	ItemEffectTypeOnHit   ItemEffectType = "on_hit"
	ItemEffectTypeProc    ItemEffectType = "proc"
)

func (e *ItemEffectType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemEffectType(s)
	case string:
		*e = ItemEffectType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemEffectType: %T", src)
	}
	return nil
}

type NullItemEffectType struct {
	ItemEffectType ItemEffectType `json:"item_effect_type"`
	Valid          bool           `json:"valid"` // Valid is true if ItemEffectType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemEffectType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemEffectType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemEffectType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemEffectType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemEffectType), nil
}

func (e ItemEffectType) Valid() bool {
	switch e {
	case ItemEffectTypeOnUse,
		ItemEffectTypeOnEquip,
		ItemEffectTypeOnHit,
		ItemEffectTypeProc:
		return true
	}
	return false
}

func AllItemEffectTypeValues() []ItemEffectType {
	return []ItemEffectType{
		ItemEffectTypeOnUse,
		ItemEffectTypeOnEquip,
		ItemEffectTypeOnHit,
		ItemEffectTypeProc,
	}
}

type KillType string

const (
	KillTypeClean   KillType = "clean"
	KillTypePartial KillType = "partial"
	KillTypeWipe    KillType = "wipe"
	KillTypeReset   KillType = "reset"
)

func (e *KillType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KillType(s)
	case string:
		*e = KillType(s)
	default:
		return fmt.Errorf("unsupported scan type for KillType: %T", src)
	}
	return nil
}

type NullKillType struct {
	KillType KillType `json:"kill_type"`
	Valid    bool     `json:"valid"` // Valid is true if KillType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKillType) Scan(value interface{}) error {
	if value == nil {
		ns.KillType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KillType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKillType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KillType), nil
}

func (e KillType) Valid() bool {
	switch e {
	case KillTypeClean,
		KillTypePartial,
		KillTypeWipe,
		KillTypeReset:
		return true
	}
	return false
}

func AllKillTypeValues() []KillType {
	return []KillType{
		KillTypeClean,
		KillTypePartial,
		KillTypeWipe,
		KillTypeReset,
	}
}

type LogInstanceEventType string

const (
	LogInstanceEventTypeDamage             LogInstanceEventType = "damage"
	LogInstanceEventTypeHeal               LogInstanceEventType = "heal"
	LogInstanceEventTypeResourceChange     LogInstanceEventType = "resource_change"
	LogInstanceEventTypeExtraAttack        LogInstanceEventType = "extra_attack"
	LogInstanceEventTypeSlain              LogInstanceEventType = "slain"
	LogInstanceEventTypeCast               LogInstanceEventType = "cast"
	LogInstanceEventTypeAura               LogInstanceEventType = "aura"
	LogInstanceEventTypeSpellGo            LogInstanceEventType = "spell_go"
	LogInstanceEventTypeAuraCast           LogInstanceEventType = "aura_cast"
	LogInstanceEventTypeSpellStart         LogInstanceEventType = "spell_start"
	LogInstanceEventTypeSpellFail          LogInstanceEventType = "spell_fail"
	LogInstanceEventTypeUnitClassification LogInstanceEventType = "unit_classification"
	LogInstanceEventTypeDispel             LogInstanceEventType = "dispel"
	LogInstanceEventTypeCombatantInfo      LogInstanceEventType = "combatant_info"
	LogInstanceEventTypeInterrupt          LogInstanceEventType = "interrupt"
	LogInstanceEventTypeAbsorbed           LogInstanceEventType = "absorbed"
)

func (e *LogInstanceEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogInstanceEventType(s)
	case string:
		*e = LogInstanceEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for LogInstanceEventType: %T", src)
	}
	return nil
}

type NullLogInstanceEventType struct {
	LogInstanceEventType LogInstanceEventType `json:"log_instance_event_type"`
	Valid                bool                 `json:"valid"` // Valid is true if LogInstanceEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogInstanceEventType) Scan(value interface{}) error {
	if value == nil {
		ns.LogInstanceEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogInstanceEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogInstanceEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogInstanceEventType), nil
}

func (e LogInstanceEventType) Valid() bool {
	switch e {
	case LogInstanceEventTypeDamage,
		LogInstanceEventTypeHeal,
		LogInstanceEventTypeResourceChange,
		LogInstanceEventTypeExtraAttack,
		LogInstanceEventTypeSlain,
		LogInstanceEventTypeCast,
		LogInstanceEventTypeAura,
		LogInstanceEventTypeSpellGo,
		LogInstanceEventTypeAuraCast,
		LogInstanceEventTypeSpellStart,
		LogInstanceEventTypeSpellFail,
		LogInstanceEventTypeUnitClassification,
		LogInstanceEventTypeDispel,
		LogInstanceEventTypeCombatantInfo,
		LogInstanceEventTypeInterrupt,
		LogInstanceEventTypeAbsorbed:
		return true
	}
	return false
}

func AllLogInstanceEventTypeValues() []LogInstanceEventType {
	return []LogInstanceEventType{
		LogInstanceEventTypeDamage,
		LogInstanceEventTypeHeal,
		LogInstanceEventTypeResourceChange,
		LogInstanceEventTypeExtraAttack,
		LogInstanceEventTypeSlain,
		LogInstanceEventTypeCast,
		LogInstanceEventTypeAura,
		LogInstanceEventTypeSpellGo,
		LogInstanceEventTypeAuraCast,
		LogInstanceEventTypeSpellStart,
		LogInstanceEventTypeSpellFail,
		LogInstanceEventTypeUnitClassification,
		LogInstanceEventTypeDispel,
		LogInstanceEventTypeCombatantInfo,
		LogInstanceEventTypeInterrupt,
		LogInstanceEventTypeAbsorbed,
	}
}

type LogType string

const (
	LogTypeV1          LogType = "v1"
	LogTypeV2          LogType = "v2"
	LogTypeWarmane     LogType = "warmane"
	LogTypeEpoch       LogType = "epoch"
	LogTypeKronos      LogType = "kronos"
	LogTypeAzerothcore LogType = "azerothcore"
)

func (e *LogType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogType(s)
	case string:
		*e = LogType(s)
	default:
		return fmt.Errorf("unsupported scan type for LogType: %T", src)
	}
	return nil
}

type NullLogType struct {
	LogType LogType `json:"log_type"`
	Valid   bool    `json:"valid"` // Valid is true if LogType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogType) Scan(value interface{}) error {
	if value == nil {
		ns.LogType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogType), nil
}

func (e LogType) Valid() bool {
	switch e {
	case LogTypeV1,
		LogTypeV2,
		LogTypeWarmane,
		LogTypeEpoch,
		LogTypeKronos,
		LogTypeAzerothcore:
		return true
	}
	return false
}

func AllLogTypeValues() []LogType {
	return []LogType{
		LogTypeV1,
		LogTypeV2,
		LogTypeWarmane,
		LogTypeEpoch,
		LogTypeKronos,
		LogTypeAzerothcore,
	}
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState `json:"river_job_state"`
	Valid         bool          `json:"valid"` // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

func (e RiverJobState) Valid() bool {
	switch e {
	case RiverJobStateAvailable,
		RiverJobStateCancelled,
		RiverJobStateCompleted,
		RiverJobStateDiscarded,
		RiverJobStatePending,
		RiverJobStateRetryable,
		RiverJobStateRunning,
		RiverJobStateScheduled:
		return true
	}
	return false
}

func AllRiverJobStateValues() []RiverJobState {
	return []RiverJobState{
		RiverJobStateAvailable,
		RiverJobStateCancelled,
		RiverJobStateCompleted,
		RiverJobStateDiscarded,
		RiverJobStatePending,
		RiverJobStateRetryable,
		RiverJobStateRunning,
		RiverJobStateScheduled,
	}
}

type UnitAffiliation string

const (
	UnitAffiliationUnknown  UnitAffiliation = "unknown"
	UnitAffiliationFriendly UnitAffiliation = "friendly"
	UnitAffiliationNeutral  UnitAffiliation = "neutral"
	UnitAffiliationHostile  UnitAffiliation = "hostile"
	UnitAffiliationVary     UnitAffiliation = "vary"
)

func (e *UnitAffiliation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitAffiliation(s)
	case string:
		*e = UnitAffiliation(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitAffiliation: %T", src)
	}
	return nil
}

type NullUnitAffiliation struct {
	UnitAffiliation UnitAffiliation `json:"unit_affiliation"`
	Valid           bool            `json:"valid"` // Valid is true if UnitAffiliation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitAffiliation) Scan(value interface{}) error {
	if value == nil {
		ns.UnitAffiliation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitAffiliation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitAffiliation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitAffiliation), nil
}

func (e UnitAffiliation) Valid() bool {
	switch e {
	case UnitAffiliationUnknown,
		UnitAffiliationFriendly,
		UnitAffiliationNeutral,
		UnitAffiliationHostile,
		UnitAffiliationVary:
		return true
	}
	return false
}

func AllUnitAffiliationValues() []UnitAffiliation {
	return []UnitAffiliation{
		UnitAffiliationUnknown,
		UnitAffiliationFriendly,
		UnitAffiliationNeutral,
		UnitAffiliationHostile,
		UnitAffiliationVary,
	}
}

type WowPlayableClass string

const (
	WowPlayableClassWARRIOR     WowPlayableClass = "WARRIOR"
	WowPlayableClassPALADIN     WowPlayableClass = "PALADIN"
	WowPlayableClassHUNTER      WowPlayableClass = "HUNTER"
	WowPlayableClassROGUE       WowPlayableClass = "ROGUE"
	WowPlayableClassPRIEST      WowPlayableClass = "PRIEST"
	WowPlayableClassDEATHKNIGHT WowPlayableClass = "DEATH_KNIGHT"
	WowPlayableClassSHAMAN      WowPlayableClass = "SHAMAN"
	WowPlayableClassMAGE        WowPlayableClass = "MAGE"
	WowPlayableClassWARLOCK     WowPlayableClass = "WARLOCK"
	WowPlayableClassDRUID       WowPlayableClass = "DRUID"
	WowPlayableClassMONK        WowPlayableClass = "MONK"
	WowPlayableClassDEMONHUNTER WowPlayableClass = "DEMON_HUNTER"
	WowPlayableClassUNKNOWN     WowPlayableClass = "UNKNOWN"
)

func (e *WowPlayableClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WowPlayableClass(s)
	case string:
		*e = WowPlayableClass(s)
	default:
		return fmt.Errorf("unsupported scan type for WowPlayableClass: %T", src)
	}
	return nil
}

type NullWowPlayableClass struct {
	WowPlayableClass WowPlayableClass `json:"wow_playable_class"`
	Valid            bool             `json:"valid"` // Valid is true if WowPlayableClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWowPlayableClass) Scan(value interface{}) error {
	if value == nil {
		ns.WowPlayableClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WowPlayableClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWowPlayableClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WowPlayableClass), nil
}

func (e WowPlayableClass) Valid() bool {
	switch e {
	case WowPlayableClassWARRIOR,
		WowPlayableClassPALADIN,
		WowPlayableClassHUNTER,
		WowPlayableClassROGUE,
		WowPlayableClassPRIEST,
		WowPlayableClassDEATHKNIGHT,
		WowPlayableClassSHAMAN,
		WowPlayableClassMAGE,
		WowPlayableClassWARLOCK,
		WowPlayableClassDRUID,
		WowPlayableClassMONK,
		WowPlayableClassDEMONHUNTER,
		WowPlayableClassUNKNOWN:
		return true
	}
	return false
}

func AllWowPlayableClassValues() []WowPlayableClass {
	return []WowPlayableClass{
		WowPlayableClassWARRIOR,
		WowPlayableClassPALADIN,
		WowPlayableClassHUNTER,
		WowPlayableClassROGUE,
		WowPlayableClassPRIEST,
		WowPlayableClassDEATHKNIGHT,
		WowPlayableClassSHAMAN,
		WowPlayableClassMAGE,
		WowPlayableClassWARLOCK,
		WowPlayableClassDRUID,
		WowPlayableClassMONK,
		WowPlayableClassDEMONHUNTER,
		WowPlayableClassUNKNOWN,
	}
}

type WowPlayableGender string

const (
	WowPlayableGenderNotSet  WowPlayableGender = "NotSet"
	WowPlayableGenderUnknown WowPlayableGender = "Unknown"
	WowPlayableGenderMale    WowPlayableGender = "Male"
	WowPlayableGenderFemale  WowPlayableGender = "Female"
)

func (e *WowPlayableGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WowPlayableGender(s)
	case string:
		*e = WowPlayableGender(s)
	default:
		return fmt.Errorf("unsupported scan type for WowPlayableGender: %T", src)
	}
	return nil
}

type NullWowPlayableGender struct {
	WowPlayableGender WowPlayableGender `json:"wow_playable_gender"`
	Valid             bool              `json:"valid"` // Valid is true if WowPlayableGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWowPlayableGender) Scan(value interface{}) error {
	if value == nil {
		ns.WowPlayableGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WowPlayableGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWowPlayableGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WowPlayableGender), nil
}

func (e WowPlayableGender) Valid() bool {
	switch e {
	case WowPlayableGenderNotSet,
		WowPlayableGenderUnknown,
		WowPlayableGenderMale,
		WowPlayableGenderFemale:
		return true
	}
	return false
}

func AllWowPlayableGenderValues() []WowPlayableGender {
	return []WowPlayableGender{
		WowPlayableGenderNotSet,
		WowPlayableGenderUnknown,
		WowPlayableGenderMale,
		WowPlayableGenderFemale,
	}
}

type WowPlayableRace string

const (
	WowPlayableRaceScourge  WowPlayableRace = "Scourge"
	WowPlayableRaceOrc      WowPlayableRace = "Orc"
	WowPlayableRaceTroll    WowPlayableRace = "Troll"
	WowPlayableRaceTauren   WowPlayableRace = "Tauren"
	WowPlayableRaceGoblin   WowPlayableRace = "Goblin"
	WowPlayableRaceHuman    WowPlayableRace = "Human"
	WowPlayableRaceGnome    WowPlayableRace = "Gnome"
	WowPlayableRaceDwarf    WowPlayableRace = "Dwarf"
	WowPlayableRaceNightElf WowPlayableRace = "NightElf"
	WowPlayableRaceBloodElf WowPlayableRace = "BloodElf"
	WowPlayableRaceUnknown  WowPlayableRace = "Unknown"
)

func (e *WowPlayableRace) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WowPlayableRace(s)
	case string:
		*e = WowPlayableRace(s)
	default:
		return fmt.Errorf("unsupported scan type for WowPlayableRace: %T", src)
	}
	return nil
}

type NullWowPlayableRace struct {
	WowPlayableRace WowPlayableRace `json:"wow_playable_race"`
	Valid           bool            `json:"valid"` // Valid is true if WowPlayableRace is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWowPlayableRace) Scan(value interface{}) error {
	if value == nil {
		ns.WowPlayableRace, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WowPlayableRace.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWowPlayableRace) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WowPlayableRace), nil
}

func (e WowPlayableRace) Valid() bool {
	switch e {
	case WowPlayableRaceScourge,
		WowPlayableRaceOrc,
		WowPlayableRaceTroll,
		WowPlayableRaceTauren,
		WowPlayableRaceGoblin,
		WowPlayableRaceHuman,
		WowPlayableRaceGnome,
		WowPlayableRaceDwarf,
		WowPlayableRaceNightElf,
		WowPlayableRaceBloodElf,
		WowPlayableRaceUnknown:
		return true
	}
	return false
}

func AllWowPlayableRaceValues() []WowPlayableRace {
	return []WowPlayableRace{
		WowPlayableRaceScourge,
		WowPlayableRaceOrc,
		WowPlayableRaceTroll,
		WowPlayableRaceTauren,
		WowPlayableRaceGoblin,
		WowPlayableRaceHuman,
		WowPlayableRaceGnome,
		WowPlayableRaceDwarf,
		WowPlayableRaceNightElf,
		WowPlayableRaceBloodElf,
		WowPlayableRaceUnknown,
	}
}

type AuthzSchemaMigration struct {
	Version   int32              `db:"version" json:"version"`
	AppliedAt pgtype.Timestamptz `db:"applied_at" json:"applied_at"`
}

type ChronicleUser struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	Username               string             `db:"username" json:"username"`
	Email                  string             `db:"email" json:"email"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DefaultDesktopLayoutID uuid.NullUUID      `db:"default_desktop_layout_id" json:"default_desktop_layout_id"`
	DefaultMobileLayoutID  uuid.NullUUID      `db:"default_mobile_layout_id" json:"default_mobile_layout_id"`
	RawLogRetentionHours   pgtype.Int4        `db:"raw_log_retention_hours" json:"raw_log_retention_hours"`
	MaxStorageBytes        int64              `db:"max_storage_bytes" json:"max_storage_bytes"`
	DataLimitUpdatedAt     interface{}        `db:"data_limit_updated_at" json:"data_limit_updated_at"`
	ConsumedStorageBytes   int64              `db:"consumed_storage_bytes" json:"consumed_storage_bytes"`
}

type DataGrant struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	Source       string             `db:"source" json:"source"`
	StorageBytes int64              `db:"storage_bytes" json:"storage_bytes"`
	Description  pgtype.Text        `db:"description" json:"description"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type DbcItemDisplayInfo struct {
	ID                         int32  `db:"id" json:"id"`
	ModelName                  []byte `db:"model_name" json:"model_name"`
	ModelTexture               []byte `db:"model_texture" json:"model_texture"`
	GeosetGroup                []byte `db:"geoset_group" json:"geoset_group"`
	Flags                      int32  `db:"flags" json:"flags"`
	SpellVisualID              int32  `db:"spell_visual_id" json:"spell_visual_id"`
	HelmetGeosetVis            []byte `db:"helmet_geoset_vis" json:"helmet_geoset_vis"`
	Texture                    []byte `db:"texture" json:"texture"`
	ItemVisual                 int32  `db:"item_visual" json:"item_visual"`
	ParticleColorID            int32  `db:"particle_color_id" json:"particle_color_id"`
	AttachmentGeosetGroup      []byte `db:"attachment_geoset_group" json:"attachment_geoset_group"`
	ItemRangedDisplayInfoID    int32  `db:"item_ranged_display_info_id" json:"item_ranged_display_info_id"`
	ModelMaterialResourcesID   []byte `db:"model_material_resources_id" json:"model_material_resources_id"`
	ModelResourcesID           []byte `db:"model_resources_id" json:"model_resources_id"`
	ModelType1                 int32  `db:"model_type_1" json:"model_type_1"`
	OverrideSwooshSoundKitID   int32  `db:"override_swoosh_sound_kit_id" json:"override_swoosh_sound_kit_id"`
	SheatheTransformMatrixID   int32  `db:"sheathe_transform_matrix_id" json:"sheathe_transform_matrix_id"`
	SheathedSpellVisualKitID   int32  `db:"sheathed_spell_visual_kit_id" json:"sheathed_spell_visual_kit_id"`
	StateSpellVisualKitID      int32  `db:"state_spell_visual_kit_id" json:"state_spell_visual_kit_id"`
	UnsheathedSpellVisualKitID int32  `db:"unsheathed_spell_visual_kit_id" json:"unsheathed_spell_visual_kit_id"`
	InventoryIcon              []byte `db:"inventory_icon" json:"inventory_icon"`
	GroupSoundIndex            int32  `db:"group_sound_index" json:"group_sound_index"`
	GroundModel                string `db:"ground_model" json:"ground_model"`
	ItemSize                   int32  `db:"item_size" json:"item_size"`
	HelmetGeosetVisID          []byte `db:"helmet_geoset_vis_id" json:"helmet_geoset_vis_id"`
}

type DbcItemRandomProperty struct {
	ID           int32  `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	NameLang     string `db:"name_lang" json:"name_lang"`
	Enchantment1 int32  `db:"enchantment_1" json:"enchantment_1"`
	Enchantment2 int32  `db:"enchantment_2" json:"enchantment_2"`
	Enchantment3 int32  `db:"enchantment_3" json:"enchantment_3"`
	Enchantment4 int32  `db:"enchantment_4" json:"enchantment_4"`
	Enchantment5 int32  `db:"enchantment_5" json:"enchantment_5"`
}

type DbcItemSet struct {
	ID                int32   `db:"id" json:"id"`
	NameLang          string  `db:"name_lang" json:"name_lang"`
	RequiredSkill     int32   `db:"required_skill" json:"required_skill"`
	RequiredSkillRank int32   `db:"required_skill_rank" json:"required_skill_rank"`
	ItemIds           []int32 `db:"item_ids" json:"item_ids"`
}

type DbcItemSetBonu struct {
	SetID     int32 `db:"set_id" json:"set_id"`
	Threshold int32 `db:"threshold" json:"threshold"`
	SpellID   int32 `db:"spell_id" json:"spell_id"`
}

type DbcItemSetItem struct {
	SetID     int32 `db:"set_id" json:"set_id"`
	ItemEntry int32 `db:"item_entry" json:"item_entry"`
}

type DbcSpellItemEnchantment struct {
	ID                int32  `db:"id" json:"id"`
	Charges           int32  `db:"charges" json:"charges"`
	Effect1           int32  `db:"effect_1" json:"effect_1"`
	Effect2           int32  `db:"effect_2" json:"effect_2"`
	Effect3           int32  `db:"effect_3" json:"effect_3"`
	EffectPointsMin1  int32  `db:"effect_points_min_1" json:"effect_points_min_1"`
	EffectPointsMin2  int32  `db:"effect_points_min_2" json:"effect_points_min_2"`
	EffectPointsMin3  int32  `db:"effect_points_min_3" json:"effect_points_min_3"`
	EffectArg1        int32  `db:"effect_arg_1" json:"effect_arg_1"`
	EffectArg2        int32  `db:"effect_arg_2" json:"effect_arg_2"`
	EffectArg3        int32  `db:"effect_arg_3" json:"effect_arg_3"`
	NameLang          string `db:"name_lang" json:"name_lang"`
	ItemVisual        int32  `db:"item_visual" json:"item_visual"`
	Flags             int32  `db:"flags" json:"flags"`
	SrcItemID         int32  `db:"src_item_id" json:"src_item_id"`
	ConditionID       int32  `db:"condition_id" json:"condition_id"`
	RequiredSkillID   int32  `db:"required_skill_id" json:"required_skill_id"`
	RequiredSkillRank int32  `db:"required_skill_rank" json:"required_skill_rank"`
	MinLevel          int32  `db:"min_level" json:"min_level"`
	MaxLevel          int32  `db:"max_level" json:"max_level"`
}

type GamePlayer struct {
	ID                  guid.GUID          `db:"id" json:"id"`
	RealmID             uuid.UUID          `db:"realm_id" json:"realm_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	GuildID             uuid.NullUUID      `db:"guild_id" json:"guild_id"`
	Name                string             `db:"name" json:"name"`
	Class               WowPlayableClass   `db:"class" json:"class"`
	Gender              WowPlayableGender  `db:"gender" json:"gender"`
	Race                WowPlayableRace    `db:"race" json:"race"`
	Gear                PlayerOutfit       `db:"gear" json:"gear"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedFromInstance uuid.NullUUID      `db:"updated_from_instance" json:"updated_from_instance"`
	Level               int16              `db:"level" json:"level"`
	Talents             *PlayerTalents     `db:"talents" json:"talents"`
}

type Guild struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	RealmID   uuid.UUID          `db:"realm_id" json:"realm_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GuildJoinRequest struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	GuildID   uuid.UUID          `db:"guild_id" json:"guild_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Message   string             `db:"message" json:"message"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GuildPage struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	GuildID   uuid.UUID          `db:"guild_id" json:"guild_id"`
	Theme     []byte             `db:"theme" json:"theme"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GuildPagePanel struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TabID     uuid.UUID          `db:"tab_id" json:"tab_id"`
	PanelType string             `db:"panel_type" json:"panel_type"`
	Config    []byte             `db:"config" json:"config"`
	Position  []byte             `db:"position" json:"position"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GuildPageTab struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	PageID    uuid.UUID          `db:"page_id" json:"page_id"`
	Label     string             `db:"label" json:"label"`
	Slug      string             `db:"slug" json:"slug"`
	SortOrder int32              `db:"sort_order" json:"sort_order"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GuildSetting struct {
	GuildID                uuid.UUID          `db:"guild_id" json:"guild_id"`
	AllowJoinRequestsUntil pgtype.Timestamptz `db:"allow_join_requests_until" json:"allow_join_requests_until"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GuildSpeedrunRank struct {
	InstanceID   uuid.UUID     `db:"instance_id" json:"instance_id"`
	InstanceName string        `db:"instance_name" json:"instance_name"`
	RealmID      uuid.UUID     `db:"realm_id" json:"realm_id"`
	GuildID      uuid.NullUUID `db:"guild_id" json:"guild_id"`
	DurationMs   int64         `db:"duration_ms" json:"duration_ms"`
	GuildRank    int64         `db:"guild_rank" json:"guild_rank"`
}

type InstanceLoot struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	InstanceID   uuid.UUID          `db:"instance_id" json:"instance_id"`
	RealmID      uuid.UUID          `db:"realm_id" json:"realm_id"`
	SourceGuid   int64              `db:"source_guid" json:"source_guid"`
	SourceTs     pgtype.Timestamptz `db:"source_ts" json:"source_ts"`
	ReceivedGuid int64              `db:"received_guid" json:"received_guid"`
	ReceivedTs   pgtype.Timestamptz `db:"received_ts" json:"received_ts"`
	ItemID       int32              `db:"item_id" json:"item_id"`
	ItemName     string             `db:"item_name" json:"item_name"`
	LootSuffix   int32              `db:"loot_suffix" json:"loot_suffix"`
	Quantity     int32              `db:"quantity" json:"quantity"`
}

type InstanceSpeedrun struct {
	InstanceID       uuid.UUID          `db:"instance_id" json:"instance_id"`
	InstanceName     string             `db:"instance_name" json:"instance_name"`
	RealmID          uuid.UUID          `db:"realm_id" json:"realm_id"`
	GuildID          uuid.NullUUID      `db:"guild_id" json:"guild_id"`
	Qualified        bool               `db:"qualified" json:"qualified"`
	StartTime        pgtype.Timestamptz `db:"start_time" json:"start_time"`
	CompletionTime   pgtype.Timestamptz `db:"completion_time" json:"completion_time"`
	DurationMs       int64              `db:"duration_ms" json:"duration_ms"`
	Proof            []byte             `db:"proof" json:"proof"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AddonVersion     string             `db:"addon_version" json:"addon_version"`
	ParserVersionNum int64              `db:"parser_version_num" json:"parser_version_num"`
	AddonVersionNum  int64              `db:"addon_version_num" json:"addon_version_num"`
}

type LeaderboardVersionRequirement struct {
	InstanceName        string             `db:"instance_name" json:"instance_name"`
	MinParserVersion    string             `db:"min_parser_version" json:"min_parser_version"`
	MinParserVersionNum int64              `db:"min_parser_version_num" json:"min_parser_version_num"`
	MinAddonVersion     string             `db:"min_addon_version" json:"min_addon_version"`
	MinAddonVersionNum  int64              `db:"min_addon_version_num" json:"min_addon_version_num"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type LogFile struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Owner    uuid.UUID `db:"owner" json:"owner"`
	WowLogID uuid.UUID `db:"wow_log_id" json:"wow_log_id"`
	Hash     string    `db:"hash" json:"hash"`
	// Original uncompressed file size in bytes
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	MimeType  string             `db:"mime_type" json:"mime_type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// The timestamp when the file was deleted from storage. This allows us to keep track of files that have been removed from storage, even if the log_file record still exists in the database.
	StorageDeletedAt pgtype.Timestamptz `db:"storage_deleted_at" json:"storage_deleted_at"`
	// Compressed file size in bytes (NULL if stored uncompressed)
	CompressedSizeBytes pgtype.Int8 `db:"compressed_size_bytes" json:"compressed_size_bytes"`
	// Content encoding used for storage (e.g., gzip), NULL if stored raw
	ContentEncoding pgtype.Text `db:"content_encoding" json:"content_encoding"`
}

type LogInstance struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	RealmID    uuid.UUID   `db:"realm_id" json:"realm_id"`
	LogGroupID uuid.UUID   `db:"log_group_id" json:"log_group_id"`
	Name       string      `db:"name" json:"name"`
	HashedSlug pgtype.Text `db:"hashed_slug" json:"hashed_slug"`
	// If set, that means it was a guild run.
	GuildID          uuid.NullUUID      `db:"guild_id" json:"guild_id"`
	StartTime        pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime          pgtype.Timestamptz `db:"end_time" json:"end_time"`
	Capabilities     []string           `db:"capabilities" json:"capabilities"`
	Versions         VersionsMap        `db:"versions" json:"versions"`
	RecorderName     string             `db:"recorder_name" json:"recorder_name"`
	RecorderGuid     string             `db:"recorder_guid" json:"recorder_guid"`
	ParserVersion    string             `db:"parser_version" json:"parser_version"`
	DuplicateGroupID uuid.NullUUID      `db:"duplicate_group_id" json:"duplicate_group_id"`
}

type LogInstanceEncounter struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	InstanceID uuid.UUID          `db:"instance_id" json:"instance_id"`
	Name       string             `db:"name" json:"name"`
	Remaining  guid.GUIDs         `db:"remaining" json:"remaining"`
	Boss       bool               `db:"boss" json:"boss"`
	StartTime  pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime    pgtype.Timestamptz `db:"end_time" json:"end_time"`
	KillType   KillType           `db:"kill_type" json:"kill_type"`
}

type LogInstanceEncounterDamageUnitSummary struct {
	EncounterID          uuid.UUID                        `db:"encounter_id" json:"encounter_id"`
	UnitGuid             guid.GUID                        `db:"unit_guid" json:"unit_guid"`
	UnitName             string                           `db:"unit_name" json:"unit_name"`
	DamageDoneTotal      int64                            `db:"damage_done_total" json:"damage_done_total"`
	DamageTakenTotal     int64                            `db:"damage_taken_total" json:"damage_taken_total"`
	DamageDoneAbilities  map[guid.GUID]map[string]Ability `db:"damage_done_abilities" json:"damage_done_abilities"`
	DamageTakenAbilities map[guid.GUID]map[string]Ability `db:"damage_taken_abilities" json:"damage_taken_abilities"`
	IsPlayer             bool                             `db:"is_player" json:"is_player"`
	OwnerGuid            *guid.GUID                       `db:"owner_guid" json:"owner_guid"`
}

type LogInstanceEncounterHostile struct {
	EncounterID uuid.UUID `db:"encounter_id" json:"encounter_id"`
	ID          guid.GUID `db:"id" json:"id"`
	Periods     Periods   `db:"periods" json:"periods"`
	Boss        bool      `db:"boss" json:"boss"`
}

type LogInstanceEvent struct {
	InstanceID uuid.UUID            `db:"instance_id" json:"instance_id"`
	Type       LogInstanceEventType `db:"type" json:"type"`
	// Gzipped protobuf-encoded events
	Events []byte `db:"events" json:"events"`
}

type LogInstancePlayer struct {
	InstanceID uuid.UUID        `db:"instance_id" json:"instance_id"`
	UnitGuid   guid.GUID        `db:"unit_guid" json:"unit_guid"`
	Name       string           `db:"name" json:"name"`
	Level      int32            `db:"level" json:"level"`
	Class      WowPlayableClass `db:"class" json:"class"`
	Race       WowPlayableRace  `db:"race" json:"race"`
	GuildID    uuid.NullUUID    `db:"guild_id" json:"guild_id"`
}

// Stores all units (NPCs, not players) that participated in an instance.
type LogInstanceUnit struct {
	InstanceID uuid.UUID  `db:"instance_id" json:"instance_id"`
	UnitGuid   guid.GUID  `db:"unit_guid" json:"unit_guid"`
	Name       string     `db:"name" json:"name"`
	Entry      int32      `db:"entry" json:"entry"`
	OwnerGuid  *guid.GUID `db:"owner_guid" json:"owner_guid"`
}

type LogInstanceYoutubeTimestamped struct {
	LogInstanceID uuid.NullUUID      `db:"log_instance_id" json:"log_instance_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExportedAt    pgtype.Timestamptz `db:"exported_at" json:"exported_at"`
	VideoUrl      string             `db:"video_url" json:"video_url"`
	Payload       []VideoTimestamp   `db:"payload" json:"payload"`
	InstanceSlug  pgtype.Text        `db:"instance_slug" json:"instance_slug"`
	ID            uuid.UUID          `db:"id" json:"id"`
}

type LogInstancesGuild struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	RealmID          uuid.UUID          `db:"realm_id" json:"realm_id"`
	LogGroupID       uuid.UUID          `db:"log_group_id" json:"log_group_id"`
	Name             string             `db:"name" json:"name"`
	HashedSlug       pgtype.Text        `db:"hashed_slug" json:"hashed_slug"`
	GuildID          uuid.NullUUID      `db:"guild_id" json:"guild_id"`
	Capabilities     []string           `db:"capabilities" json:"capabilities"`
	Versions         VersionsMap        `db:"versions" json:"versions"`
	RecorderName     string             `db:"recorder_name" json:"recorder_name"`
	RecorderGuid     string             `db:"recorder_guid" json:"recorder_guid"`
	DuplicateGroupID uuid.NullUUID      `db:"duplicate_group_id" json:"duplicate_group_id"`
	StartTime        pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime          pgtype.Timestamptz `db:"end_time" json:"end_time"`
	RealmName        string             `db:"realm_name" json:"realm_name"`
	GuildName        pgtype.Text        `db:"guild_name" json:"guild_name"`
	GuildRealmID     uuid.NullUUID      `db:"guild_realm_id" json:"guild_realm_id"`
	GuildCreatedAt   pgtype.Timestamptz `db:"guild_created_at" json:"guild_created_at"`
}

// A parsed_log_group is a wow_log_group that has been processed and contains parsed logs. A duplicate allows deleting this one row to clear all parsed logs for a given wow_log_group.
type ParsedLogGroup struct {
	ID uuid.UUID `db:"id" json:"id"`
}

type RegressionFixture struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	LogGroupID uuid.UUID          `db:"log_group_id" json:"log_group_id"`
	Note       string             `db:"note" json:"note"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RegressionSnapshot struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	FixtureID          uuid.UUID          `db:"fixture_id" json:"fixture_id"`
	Version            string             `db:"version" json:"version"`
	Snapshot           []byte             `db:"snapshot" json:"snapshot"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	BuildTime          string             `db:"build_time" json:"build_time"`
	MatchesPrevious    pgtype.Bool        `db:"matches_previous" json:"matches_previous"`
	PreviousSnapshotID uuid.NullUUID      `db:"previous_snapshot_id" json:"previous_snapshot_id"`
}

type RetentionPolicy struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	ServerID     uuid.NullUUID      `db:"server_id" json:"server_id"`
	RealmID      uuid.NullUUID      `db:"realm_id" json:"realm_id"`
	Enabled      bool               `db:"enabled" json:"enabled"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastRunAt    pgtype.Timestamptz `db:"last_run_at" json:"last_run_at"`
	TotalDeleted int64              `db:"total_deleted" json:"total_deleted"`
	TotalKept    int64              `db:"total_kept" json:"total_kept"`
}

type RetentionRule struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	PolicyID    uuid.UUID          `db:"policy_id" json:"policy_id"`
	Priority    int32              `db:"priority" json:"priority"`
	Action      string             `db:"action" json:"action"`
	Conditions  []byte             `db:"conditions" json:"conditions"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RiverClient struct {
	ID        string             `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	PausedAt  pgtype.Timestamptz `db:"paused_at" json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RiverClientQueue struct {
	RiverClientID    string             `db:"river_client_id" json:"river_client_id"`
	Name             string             `db:"name" json:"name"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	MaxWorkers       int64              `db:"max_workers" json:"max_workers"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	NumJobsCompleted int64              `db:"num_jobs_completed" json:"num_jobs_completed"`
	NumJobsRunning   int64              `db:"num_jobs_running" json:"num_jobs_running"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RiverJob struct {
	ID           int64              `db:"id" json:"id"`
	State        RiverJobState      `db:"state" json:"state"`
	Attempt      int16              `db:"attempt" json:"attempt"`
	MaxAttempts  int16              `db:"max_attempts" json:"max_attempts"`
	AttemptedAt  pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `db:"finalized_at" json:"finalized_at"`
	ScheduledAt  pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	Priority     int16              `db:"priority" json:"priority"`
	Args         []byte             `db:"args" json:"args"`
	AttemptedBy  []string           `db:"attempted_by" json:"attempted_by"`
	Errors       [][]byte           `db:"errors" json:"errors"`
	Kind         string             `db:"kind" json:"kind"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
	Queue        string             `db:"queue" json:"queue"`
	Tags         []string           `db:"tags" json:"tags"`
	UniqueKey    []byte             `db:"unique_key" json:"unique_key"`
	UniqueStates pgtype.Bits        `db:"unique_states" json:"unique_states"`
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz `db:"elected_at" json:"elected_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LeaderID  string             `db:"leader_id" json:"leader_id"`
	Name      string             `db:"name" json:"name"`
}

type RiverMigration struct {
	Line      string             `db:"line" json:"line"`
	Version   int64              `db:"version" json:"version"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RiverQueue struct {
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	PausedAt  pgtype.Timestamptz `db:"paused_at" json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ServerUploadMetum struct {
	LogGroupID    uuid.UUID          `db:"log_group_id" json:"log_group_id"`
	InstanceID    string             `db:"instance_id" json:"instance_id"`
	InstanceName  string             `db:"instance_name" json:"instance_name"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RealmID       uuid.NullUUID      `db:"realm_id" json:"realm_id"`
	InstanceToken pgtype.Text        `db:"instance_token" json:"instance_token"`
}

type SharedView struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Hash         string             `db:"hash" json:"hash"`
	InstanceID   uuid.NullUUID      `db:"instance_id" json:"instance_id"`
	Payload      []byte             `db:"payload" json:"payload"`
	CreatedBy    uuid.NullUUID      `db:"created_by" json:"created_by"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	InstanceSlug string             `db:"instance_slug" json:"instance_slug"`
}

type SiteConfig struct {
	ID             bool               `db:"id" json:"id"`
	SignupsEnabled bool               `db:"signups_enabled" json:"signups_enabled"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	Username               string             `db:"username" json:"username"`
	Email                  string             `db:"email" json:"email"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DefaultDesktopLayoutID uuid.NullUUID      `db:"default_desktop_layout_id" json:"default_desktop_layout_id"`
	DefaultMobileLayoutID  uuid.NullUUID      `db:"default_mobile_layout_id" json:"default_mobile_layout_id"`
	RawLogRetentionHours   pgtype.Int4        `db:"raw_log_retention_hours" json:"raw_log_retention_hours"`
}

type UserActionBarSlot struct {
	UserID uuid.UUID     `db:"user_id" json:"user_id"`
	Slot1  uuid.NullUUID `db:"slot_1" json:"slot_1"`
	Slot2  uuid.NullUUID `db:"slot_2" json:"slot_2"`
	Slot3  uuid.NullUUID `db:"slot_3" json:"slot_3"`
	Slot4  uuid.NullUUID `db:"slot_4" json:"slot_4"`
	Slot5  uuid.NullUUID `db:"slot_5" json:"slot_5"`
	Slot6  uuid.NullUUID `db:"slot_6" json:"slot_6"`
	Slot7  uuid.NullUUID `db:"slot_7" json:"slot_7"`
	Slot8  uuid.NullUUID `db:"slot_8" json:"slot_8"`
	Slot9  uuid.NullUUID `db:"slot_9" json:"slot_9"`
	Slot0  uuid.NullUUID `db:"slot_0" json:"slot_0"`
}

type UserAuthLink struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	LinkedID  string             `db:"linked_id" json:"linked_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Provider  string             `db:"provider" json:"provider"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserAuthSession struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	UserAuthID        uuid.UUID          `db:"user_auth_id" json:"user_auth_id"`
	UserID            uuid.UUID          `db:"user_id" json:"user_id"`
	AccessToken       string             `db:"access_token" json:"access_token"`
	AccessTokenSecret string             `db:"access_token_secret" json:"access_token_secret"`
	RefreshToken      string             `db:"refresh_token" json:"refresh_token"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	JwtID             uuid.UUID          `db:"jwt_id" json:"jwt_id"`
}

type UserPanelLayout struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	UserID          uuid.NullUUID      `db:"user_id" json:"user_id"`
	Title           string             `db:"title" json:"title"`
	TitleNormalized pgtype.Text        `db:"title_normalized" json:"title_normalized"`
	Icon            string             `db:"icon" json:"icon"`
	Description     string             `db:"description" json:"description"`
	Payload         []byte             `db:"payload" json:"payload"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version         int32              `db:"version" json:"version"`
	Code            pgtype.Text        `db:"code" json:"code"`
}

type UserPassword struct {
	UserAuthID                 uuid.UUID          `db:"user_auth_id" json:"user_auth_id"`
	PasswordHash               string             `db:"password_hash" json:"password_hash"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EmailVerified              bool               `db:"email_verified" json:"email_verified"`
	VerificationTokenHash      pgtype.Text        `db:"verification_token_hash" json:"verification_token_hash"`
	VerificationTokenExpiresAt pgtype.Timestamptz `db:"verification_token_expires_at" json:"verification_token_expires_at"`
	VerificationTokenCreatedAt pgtype.Timestamptz `db:"verification_token_created_at" json:"verification_token_created_at"`
	ResetTokenHash             pgtype.Text        `db:"reset_token_hash" json:"reset_token_hash"`
	ResetTokenExpiresAt        pgtype.Timestamptz `db:"reset_token_expires_at" json:"reset_token_expires_at"`
	ResetTokenCreatedAt        pgtype.Timestamptz `db:"reset_token_created_at" json:"reset_token_created_at"`
}

type UserStorageLimit struct {
	UserID          uuid.UUID   `db:"user_id" json:"user_id"`
	MaxStorageBytes int64       `db:"max_storage_bytes" json:"max_storage_bytes"`
	UpdatedAt       interface{} `db:"updated_at" json:"updated_at"`
}

type UserTrackedLayout struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	LayoutID  uuid.UUID          `db:"layout_id" json:"layout_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WoWLogGroup struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Owner     uuid.UUID          `db:"owner" json:"owner"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LogType   LogType            `db:"log_type" json:"log_type"`
}

type World struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WorldCreatureSpawn struct {
	Guid int32 `db:"guid" json:"guid"`
	ID   int32 `db:"id" json:"id"`
	Id2  int32 `db:"id2" json:"id2"`
	Id3  int32 `db:"id3" json:"id3"`
	Id4  int32 `db:"id4" json:"id4"`
	Map  int32 `db:"map" json:"map"`
}

type WorldCreatureTemplate struct {
	Entry              int32       `db:"entry" json:"entry"`
	DisplayId1         int32       `db:"display_id1" json:"display_id1"`
	DisplayId2         int32       `db:"display_id2" json:"display_id2"`
	DisplayId3         int32       `db:"display_id3" json:"display_id3"`
	DisplayId4         int32       `db:"display_id4" json:"display_id4"`
	MountDisplayID     int32       `db:"mount_display_id" json:"mount_display_id"`
	Name               string      `db:"name" json:"name"`
	Subname            pgtype.Text `db:"subname" json:"subname"`
	LevelMin           int32       `db:"level_min" json:"level_min"`
	LevelMax           int32       `db:"level_max" json:"level_max"`
	HealthMin          int32       `db:"health_min" json:"health_min"`
	HealthMax          int32       `db:"health_max" json:"health_max"`
	ManaMin            int32       `db:"mana_min" json:"mana_min"`
	ManaMax            int32       `db:"mana_max" json:"mana_max"`
	Armor              int32       `db:"armor" json:"armor"`
	DmgMin             float64     `db:"dmg_min" json:"dmg_min"`
	DmgMax             float64     `db:"dmg_max" json:"dmg_max"`
	DmgSchool          int32       `db:"dmg_school" json:"dmg_school"`
	AttackPower        int32       `db:"attack_power" json:"attack_power"`
	DmgMultiplier      float64     `db:"dmg_multiplier" json:"dmg_multiplier"`
	BaseAttackTime     int32       `db:"base_attack_time" json:"base_attack_time"`
	RangedAttackTime   int32       `db:"ranged_attack_time" json:"ranged_attack_time"`
	UnitClass          int32       `db:"unit_class" json:"unit_class"`
	UnitFlags          int32       `db:"unit_flags" json:"unit_flags"`
	RangedDmgMin       float64     `db:"ranged_dmg_min" json:"ranged_dmg_min"`
	RangedDmgMax       float64     `db:"ranged_dmg_max" json:"ranged_dmg_max"`
	HolyRes            int32       `db:"holy_res" json:"holy_res"`
	FireRes            int32       `db:"fire_res" json:"fire_res"`
	NatureRes          int32       `db:"nature_res" json:"nature_res"`
	FrostRes           int32       `db:"frost_res" json:"frost_res"`
	ShadowRes          int32       `db:"shadow_res" json:"shadow_res"`
	ArcaneRes          int32       `db:"arcane_res" json:"arcane_res"`
	MechanicImmuneMask int64       `db:"mechanic_immune_mask" json:"mechanic_immune_mask"`
	SchoolImmuneMask   int32       `db:"school_immune_mask" json:"school_immune_mask"`
	ImmunityFlags      int32       `db:"immunity_flags" json:"immunity_flags"`
}

type WorldDisplayInfo struct {
	ID   int32  `db:"id" json:"id"`
	Icon string `db:"icon" json:"icon"`
}

type WorldBossCredit struct {
	Entry               int32  `db:"entry" json:"entry"`
	CreditType          int32  `db:"credit_type" json:"credit_type"`
	CreditEntry         int32  `db:"credit_entry" json:"credit_entry"`
	LastEncounterDungeon int32 `db:"last_encounter_dungeon" json:"last_encounter_dungeon"`
	Comment             string `db:"comment" json:"comment"`
}

type WorldInstanceScript struct {
	Map    int32  `db:"map" json:"map"`
	Parent int32  `db:"parent" json:"parent"`
	Script string `db:"script" json:"script"`
}

type WorldInstanceTemplate struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Abbreviation pgtype.Text        `db:"abbreviation" json:"abbreviation"`
	Category     InstanceCategory   `db:"category" json:"category"`
	BossCount    pgtype.Int4        `db:"boss_count" json:"boss_count"`
	Background   pgtype.Text        `db:"background" json:"background"`
	MapID        pgtype.Int4        `db:"map_id" json:"map_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WorldInstanceUnit struct {
	InstanceID    uuid.UUID       `db:"instance_id" json:"instance_id"`
	EntryID       int32           `db:"entry_id" json:"entry_id"`
	OverrideName  pgtype.Text     `db:"override_name" json:"override_name"`
	EncounterName pgtype.Text     `db:"encounter_name" json:"encounter_name"`
	Boss          bool            `db:"boss" json:"boss"`
	Affiliation   UnitAffiliation `db:"affiliation" json:"affiliation"`
}

type WorldInstanceZoneName struct {
	InstanceID  uuid.UUID `db:"instance_id" json:"instance_id"`
	ZoneName    string    `db:"zone_name" json:"zone_name"`
	DisplayName string    `db:"display_name" json:"display_name"`
}

type WorldItemEnchantment struct {
	Entry  int32   `db:"entry" json:"entry"`
	Ench   int32   `db:"ench" json:"ench"`
	Chance float64 `db:"chance" json:"chance"`
}

type WorldItemTemplate struct {
	Entry                     int32       `db:"entry" json:"entry"`
	Class                     int32       `db:"class" json:"class"`
	Subclass                  int32       `db:"subclass" json:"subclass"`
	Name                      string      `db:"name" json:"name"`
	Description               string      `db:"description" json:"description"`
	DisplayID                 int32       `db:"display_id" json:"display_id"`
	Quality                   int32       `db:"quality" json:"quality"`
	Flags                     int32       `db:"flags" json:"flags"`
	BuyCount                  int32       `db:"buy_count" json:"buy_count"`
	BuyPrice                  int32       `db:"buy_price" json:"buy_price"`
	SellPrice                 int32       `db:"sell_price" json:"sell_price"`
	InventoryType             int32       `db:"inventory_type" json:"inventory_type"`
	AllowableClass            int32       `db:"allowable_class" json:"allowable_class"`
	AllowableRace             int32       `db:"allowable_race" json:"allowable_race"`
	ItemLevel                 int32       `db:"item_level" json:"item_level"`
	RequiredLevel             int32       `db:"required_level" json:"required_level"`
	RequiredSkill             int32       `db:"required_skill" json:"required_skill"`
	RequiredSkillRank         int32       `db:"required_skill_rank" json:"required_skill_rank"`
	RequiredSpell             int32       `db:"required_spell" json:"required_spell"`
	RequiredHonorRank         int32       `db:"required_honor_rank" json:"required_honor_rank"`
	RequiredCityRank          int32       `db:"required_city_rank" json:"required_city_rank"`
	RequiredReputationFaction int32       `db:"required_reputation_faction" json:"required_reputation_faction"`
	RequiredReputationRank    int32       `db:"required_reputation_rank" json:"required_reputation_rank"`
	MaxCount                  int32       `db:"max_count" json:"max_count"`
	Stackable                 int32       `db:"stackable" json:"stackable"`
	ContainerSlots            int32       `db:"container_slots" json:"container_slots"`
	StatType1                 int32       `db:"stat_type1" json:"stat_type1"`
	StatValue1                int32       `db:"stat_value1" json:"stat_value1"`
	StatType2                 int32       `db:"stat_type2" json:"stat_type2"`
	StatValue2                int32       `db:"stat_value2" json:"stat_value2"`
	StatType3                 int32       `db:"stat_type3" json:"stat_type3"`
	StatValue3                int32       `db:"stat_value3" json:"stat_value3"`
	StatType4                 int32       `db:"stat_type4" json:"stat_type4"`
	StatValue4                int32       `db:"stat_value4" json:"stat_value4"`
	StatType5                 int32       `db:"stat_type5" json:"stat_type5"`
	StatValue5                int32       `db:"stat_value5" json:"stat_value5"`
	StatType6                 int32       `db:"stat_type6" json:"stat_type6"`
	StatValue6                int32       `db:"stat_value6" json:"stat_value6"`
	StatType7                 int32       `db:"stat_type7" json:"stat_type7"`
	StatValue7                int32       `db:"stat_value7" json:"stat_value7"`
	StatType8                 int32       `db:"stat_type8" json:"stat_type8"`
	StatValue8                int32       `db:"stat_value8" json:"stat_value8"`
	StatType9                 int32       `db:"stat_type9" json:"stat_type9"`
	StatValue9                int32       `db:"stat_value9" json:"stat_value9"`
	StatType10                int32       `db:"stat_type10" json:"stat_type10"`
	StatValue10               int32       `db:"stat_value10" json:"stat_value10"`
	Delay                     int32       `db:"delay" json:"delay"`
	RangeMod                  float64     `db:"range_mod" json:"range_mod"`
	AmmoType                  int32       `db:"ammo_type" json:"ammo_type"`
	DmgMin1                   float64     `db:"dmg_min1" json:"dmg_min1"`
	DmgMax1                   float64     `db:"dmg_max1" json:"dmg_max1"`
	DmgType1                  int32       `db:"dmg_type1" json:"dmg_type1"`
	DmgMin2                   float64     `db:"dmg_min2" json:"dmg_min2"`
	DmgMax2                   float64     `db:"dmg_max2" json:"dmg_max2"`
	DmgType2                  int32       `db:"dmg_type2" json:"dmg_type2"`
	DmgMin3                   float64     `db:"dmg_min3" json:"dmg_min3"`
	DmgMax3                   float64     `db:"dmg_max3" json:"dmg_max3"`
	DmgType3                  int32       `db:"dmg_type3" json:"dmg_type3"`
	DmgMin4                   float64     `db:"dmg_min4" json:"dmg_min4"`
	DmgMax4                   float64     `db:"dmg_max4" json:"dmg_max4"`
	DmgType4                  int32       `db:"dmg_type4" json:"dmg_type4"`
	DmgMin5                   float64     `db:"dmg_min5" json:"dmg_min5"`
	DmgMax5                   float64     `db:"dmg_max5" json:"dmg_max5"`
	DmgType5                  int32       `db:"dmg_type5" json:"dmg_type5"`
	Block                     int32       `db:"block" json:"block"`
	Armor                     int32       `db:"armor" json:"armor"`
	HolyRes                   int32       `db:"holy_res" json:"holy_res"`
	FireRes                   int32       `db:"fire_res" json:"fire_res"`
	NatureRes                 int32       `db:"nature_res" json:"nature_res"`
	FrostRes                  int32       `db:"frost_res" json:"frost_res"`
	ShadowRes                 int32       `db:"shadow_res" json:"shadow_res"`
	ArcaneRes                 int32       `db:"arcane_res" json:"arcane_res"`
	Spellid1                  int32       `db:"spellid_1" json:"spellid_1"`
	Spelltrigger1             int32       `db:"spelltrigger_1" json:"spelltrigger_1"`
	Spellcharges1             int32       `db:"spellcharges_1" json:"spellcharges_1"`
	Spellppmrate1             float64     `db:"spellppmrate_1" json:"spellppmrate_1"`
	Spellcooldown1            int32       `db:"spellcooldown_1" json:"spellcooldown_1"`
	Spellcategory1            int32       `db:"spellcategory_1" json:"spellcategory_1"`
	Spellcategorycooldown1    int32       `db:"spellcategorycooldown_1" json:"spellcategorycooldown_1"`
	Spellid2                  int32       `db:"spellid_2" json:"spellid_2"`
	Spelltrigger2             int32       `db:"spelltrigger_2" json:"spelltrigger_2"`
	Spellcharges2             int32       `db:"spellcharges_2" json:"spellcharges_2"`
	Spellppmrate2             float64     `db:"spellppmrate_2" json:"spellppmrate_2"`
	Spellcooldown2            int32       `db:"spellcooldown_2" json:"spellcooldown_2"`
	Spellcategory2            int32       `db:"spellcategory_2" json:"spellcategory_2"`
	Spellcategorycooldown2    int32       `db:"spellcategorycooldown_2" json:"spellcategorycooldown_2"`
	Spellid3                  int32       `db:"spellid_3" json:"spellid_3"`
	Spelltrigger3             int32       `db:"spelltrigger_3" json:"spelltrigger_3"`
	Spellcharges3             int32       `db:"spellcharges_3" json:"spellcharges_3"`
	Spellppmrate3             float64     `db:"spellppmrate_3" json:"spellppmrate_3"`
	Spellcooldown3            int32       `db:"spellcooldown_3" json:"spellcooldown_3"`
	Spellcategory3            int32       `db:"spellcategory_3" json:"spellcategory_3"`
	Spellcategorycooldown3    int32       `db:"spellcategorycooldown_3" json:"spellcategorycooldown_3"`
	Spellid4                  int32       `db:"spellid_4" json:"spellid_4"`
	Spelltrigger4             int32       `db:"spelltrigger_4" json:"spelltrigger_4"`
	Spellcharges4             int32       `db:"spellcharges_4" json:"spellcharges_4"`
	Spellppmrate4             float64     `db:"spellppmrate_4" json:"spellppmrate_4"`
	Spellcooldown4            int32       `db:"spellcooldown_4" json:"spellcooldown_4"`
	Spellcategory4            int32       `db:"spellcategory_4" json:"spellcategory_4"`
	Spellcategorycooldown4    int32       `db:"spellcategorycooldown_4" json:"spellcategorycooldown_4"`
	Spellid5                  int32       `db:"spellid_5" json:"spellid_5"`
	Spelltrigger5             int32       `db:"spelltrigger_5" json:"spelltrigger_5"`
	Spellcharges5             int32       `db:"spellcharges_5" json:"spellcharges_5"`
	Spellppmrate5             float64     `db:"spellppmrate_5" json:"spellppmrate_5"`
	Spellcooldown5            int32       `db:"spellcooldown_5" json:"spellcooldown_5"`
	Spellcategory5            int32       `db:"spellcategory_5" json:"spellcategory_5"`
	Spellcategorycooldown5    int32       `db:"spellcategorycooldown_5" json:"spellcategorycooldown_5"`
	Bonding                   int32       `db:"bonding" json:"bonding"`
	PageText                  int32       `db:"page_text" json:"page_text"`
	PageLanguage              int32       `db:"page_language" json:"page_language"`
	PageMaterial              int32       `db:"page_material" json:"page_material"`
	StartQuest                int32       `db:"start_quest" json:"start_quest"`
	LockID                    int32       `db:"lock_id" json:"lock_id"`
	Material                  int32       `db:"material" json:"material"`
	Sheath                    int32       `db:"sheath" json:"sheath"`
	RandomProperty            int32       `db:"random_property" json:"random_property"`
	SetID                     int32       `db:"set_id" json:"set_id"`
	MaxDurability             int32       `db:"max_durability" json:"max_durability"`
	AreaBound                 int32       `db:"area_bound" json:"area_bound"`
	MapBound                  int32       `db:"map_bound" json:"map_bound"`
	Duration                  int32       `db:"duration" json:"duration"`
	BagFamily                 int32       `db:"bag_family" json:"bag_family"`
	DisenchantID              int32       `db:"disenchant_id" json:"disenchant_id"`
	FoodType                  int32       `db:"food_type" json:"food_type"`
	MinMoneyLoot              int32       `db:"min_money_loot" json:"min_money_loot"`
	MaxMoneyLoot              int32       `db:"max_money_loot" json:"max_money_loot"`
	WrappedGift               int32       `db:"wrapped_gift" json:"wrapped_gift"`
	ExtraFlags                int32       `db:"extra_flags" json:"extra_flags"`
	OtherTeamEntry            int32       `db:"other_team_entry" json:"other_team_entry"`
	ScriptName                pgtype.Text `db:"script_name" json:"script_name"`
	Patch                     pgtype.Text `db:"patch" json:"patch"`
	TooltipSetID              int32       `db:"tooltip_set_id" json:"tooltip_set_id"`
	RandomSuffix              int32       `db:"random_suffix" json:"random_suffix"`
	TotemCategory             int32       `db:"totem_category" json:"totem_category"`
	SocketColor1              int32       `db:"socket_color_1" json:"socket_color_1"`
	SocketContent1            int32       `db:"socket_content_1" json:"socket_content_1"`
	SocketColor2              int32       `db:"socket_color_2" json:"socket_color_2"`
	SocketContent2            int32       `db:"socket_content_2" json:"socket_content_2"`
	SocketColor3              int32       `db:"socket_color_3" json:"socket_color_3"`
	SocketContent3            int32       `db:"socket_content_3" json:"socket_content_3"`
	SocketBonus               int32       `db:"socket_bonus" json:"socket_bonus"`
	GemProperties             int32       `db:"gem_properties" json:"gem_properties"`
	RequiredDisenchantSkill   int32       `db:"required_disenchant_skill" json:"required_disenchant_skill"`
	ArmorDamageModifier       float64     `db:"armor_damage_modifier" json:"armor_damage_modifier"`
	ScalingStatDistribution   int32       `db:"scaling_stat_distribution" json:"scaling_stat_distribution"`
	ScalingStatValue          int32       `db:"scaling_stat_value" json:"scaling_stat_value"`
	ItemLimitCategory         int32       `db:"item_limit_category" json:"item_limit_category"`
	HolidayID                 int32       `db:"holiday_id" json:"holiday_id"`
}

type WorldServer struct {
	ServerID uuid.UUID `db:"server_id" json:"server_id"`
	WorldID  uuid.UUID `db:"world_id" json:"world_id"`
}

type WorldSpellArea struct {
	Spell            int32 `db:"spell" json:"spell"`
	Area             int32 `db:"area" json:"area"`
	QuestStart       int32 `db:"quest_start" json:"quest_start"`
	QuestStartActive int32 `db:"quest_start_active" json:"quest_start_active"`
	QuestEnd         int32 `db:"quest_end" json:"quest_end"`
	AuraSpell        int32 `db:"aura_spell" json:"aura_spell"`
	Racemask         int32 `db:"racemask" json:"racemask"`
	Gender           int32 `db:"gender" json:"gender"`
	Autocast         int32 `db:"autocast" json:"autocast"`
}

type WorldSpellChain struct {
	SpellID    int32 `db:"spell_id" json:"spell_id"`
	PrevSpell  int32 `db:"prev_spell" json:"prev_spell"`
	FirstSpell int32 `db:"first_spell" json:"first_spell"`
	Rank       int32 `db:"rank" json:"rank"`
	ReqSpell   int32 `db:"req_spell" json:"req_spell"`
}

type WorldSpellGroup struct {
	GroupID      int32 `db:"group_id" json:"group_id"`
	GroupSpellID int32 `db:"group_spell_id" json:"group_spell_id"`
	SpellID      int32 `db:"spell_id" json:"spell_id"`
}

type WorldSpellThreat struct {
	Entry      int32   `db:"entry" json:"entry"`
	Threat     int32   `db:"threat" json:"threat"`
	Multiplier float64 `db:"multiplier" json:"multiplier"`
	ApBonus    float64 `db:"ap_bonus" json:"ap_bonus"`
}

type WowServer struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	Name        string        `db:"name" json:"name"`
	CreatedBy   uuid.NullUUID `db:"created_by" json:"created_by"`
	Url         pgtype.Text   `db:"url" json:"url"`
	Description string        `db:"description" json:"description"`
}

type WowServerRealm struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	ServerID    uuid.UUID     `db:"server_id" json:"server_id"`
	Name        string        `db:"name" json:"name"`
	CreatedBy   uuid.NullUUID `db:"created_by" json:"created_by"`
	Url         pgtype.Text   `db:"url" json:"url"`
	Description string        `db:"description" json:"description"`
}

type WowServerUploadKey struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	RealmID     uuid.UUID          `db:"realm_id" json:"realm_id"`
	SecretHash  string             `db:"secret_hash" json:"secret_hash"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedBy   uuid.NullUUID      `db:"created_by" json:"created_by"`
}
