// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/Emyrk/chronicle/combatlog/parser/guid"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type sqlcQuerier interface {
	AdminListOutdatedParserVersionInstances(ctx context.Context, arg AdminListOutdatedParserVersionInstancesParams) ([]AdminListOutdatedParserVersionInstancesRow, error)
	AssignWorldToServer(ctx context.Context, arg AssignWorldToServerParams) error
	BulkUpsertGuildPagePanels(ctx context.Context, dollar_1 []byte) error
	ClearDuplicateGroupID(ctx context.Context, id uuid.UUID) error
	ClearResetToken(ctx context.Context, userAuthID uuid.UUID) error
	CountActiveRegressionJobs(ctx context.Context) (int64, error)
	CountAllWoWLogGroups(ctx context.Context, arg CountAllWoWLogGroupsParams) (int32, error)
	CountUserAuthLinks(ctx context.Context) (int64, error)
	CountUserPanelLayoutsTotal(ctx context.Context, userID uuid.NullUUID) (int32, error)
	// Guild Join Requests
	CreateGuildJoinRequest(ctx context.Context, arg CreateGuildJoinRequestParams) (GuildJoinRequest, error)
	CreateSharedView(ctx context.Context, arg CreateSharedViewParams) (SharedView, error)
	CreateUserPanelLayout(ctx context.Context, arg CreateUserPanelLayoutParams) (UserPanelLayout, error)
	DeleteAllParsedLogsByGroupID(ctx context.Context, id uuid.UUID) error
	DeleteDataGrant(ctx context.Context, arg DeleteDataGrantParams) error
	DeleteGuildJoinRequest(ctx context.Context, arg DeleteGuildJoinRequestParams) error
	DeleteGuildPage(ctx context.Context, guildID uuid.UUID) error
	DeleteGuildPagePanel(ctx context.Context, id uuid.UUID) error
	DeleteGuildPagePanelsByTab(ctx context.Context, tabID uuid.UUID) error
	DeleteGuildPageTab(ctx context.Context, id uuid.UUID) error
	DeleteGuildPageTabsByPage(ctx context.Context, pageID uuid.UUID) error
	DeleteLogInstanceByIDAndGroup(ctx context.Context, arg DeleteLogInstanceByIDAndGroupParams) (uuid.UUID, error)
	DeleteLogInstancesByIDs(ctx context.Context, ids []uuid.UUID) (int64, error)
	DeleteRegressionFixture(ctx context.Context, id uuid.UUID) error
	DeleteRegressionSnapshot(ctx context.Context, id uuid.UUID) error
	DeleteRetentionPolicy(ctx context.Context, id uuid.UUID) error
	DeleteRetentionRule(ctx context.Context, id uuid.UUID) error
	DeleteUploadKey(ctx context.Context, id uuid.UUID) error
	DeleteUserPanelLayoutByID(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteWoWLogGroup(ctx context.Context, id uuid.UUID) error
	DeleteWoWLogGroupFiles(ctx context.Context, arg DeleteWoWLogGroupFilesParams) ([]LogFile, error)
	DeleteWoWServer(ctx context.Context, id uuid.UUID) error
	DeleteWoWServerRealm(ctx context.Context, id uuid.UUID) error
	DeleteWorld(ctx context.Context, id uuid.UUID) error
	DeleteWorldInstanceTemplate(ctx context.Context, id uuid.UUID) error
	DeleteWorldInstanceUnits(ctx context.Context, instanceID uuid.UUID) error
	DeleteWorldInstanceZoneNames(ctx context.Context, instanceID uuid.UUID) error
	DeleteYoutubeVideoByInstanceOrSlug(ctx context.Context, arg DeleteYoutubeVideoByInstanceOrSlugParams) error
	EncountersByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]LogInstanceEncounter, error)
	FindDuplicateInstanceCandidates(ctx context.Context, arg FindDuplicateInstanceCandidatesParams) ([]FindDuplicateInstanceCandidatesRow, error)
	// Matches an existing log group by all available instance identity criteria:
	// instance_token (unique per instance, immune to AzerothCore ID reuse),
	// instance_id, instance_name, and realm_id.
	FindMatchingServerUpload(ctx context.Context, arg FindMatchingServerUploadParams) (WoWLogGroup, error)
	GetAppliedAuthzMigrations(ctx context.Context) ([]int32, error)
	GetCreatureTemplatesByEntries(ctx context.Context, entries []int32) ([]WorldCreatureTemplate, error)
	GetDBCItemDisplayInfoByID(ctx context.Context, id int32) (DbcItemDisplayInfo, error)
	GetDisplayInfoByID(ctx context.Context, id int32) (WorldDisplayInfo, error)
	GetEncounterSummariesByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]GetEncounterSummariesByInstanceIDRow, error)
	GetEncounterSummariesByInstanceIDs(ctx context.Context, instanceIds []uuid.UUID) ([]GetEncounterSummariesByInstanceIDsRow, error)
	// Returns log groups whose raw files are past their owner's retention window.
	// Only considers users who have set a retention policy (non-NULL).
	GetExpiredRawLogGroups(ctx context.Context, limit int32) ([]uuid.UUID, error)
	GetFileByHash(ctx context.Context, hash string) (LogFile, error)
	// Full page fetch with all tabs and panels
	GetFullGuildPage(ctx context.Context, guildID uuid.UUID) (GetFullGuildPageRow, error)
	GetGamePlayerByGUID(ctx context.Context, arg GetGamePlayerByGUIDParams) (GetGamePlayerByGUIDRow, error)
	GetGuildByID(ctx context.Context, id uuid.UUID) (GetGuildByIDRow, error)
	GetGuildJoinRequestByUser(ctx context.Context, arg GetGuildJoinRequestByUserParams) (GuildJoinRequest, error)
	// Guild Pages
	GetGuildPage(ctx context.Context, guildID uuid.UUID) (GuildPage, error)
	GetGuildPageByID(ctx context.Context, id uuid.UUID) (GuildPage, error)
	GetGuildPagePanel(ctx context.Context, id uuid.UUID) (GuildPagePanel, error)
	GetGuildPageTab(ctx context.Context, id uuid.UUID) (GuildPageTab, error)
	// Guild Settings
	GetGuildSettings(ctx context.Context, guildID uuid.UUID) (GuildSetting, error)
	GetInstanceEncounterCharacterFights(ctx context.Context, instanceID uuid.UUID) ([]LogInstanceEncounterHostile, error)
	GetInstanceLoot(ctx context.Context, instanceID uuid.UUID) ([]GetInstanceLootRow, error)
	GetInstanceSpeedrun(ctx context.Context, instanceID uuid.UUID) (InstanceSpeedrun, error)
	GetInstanceYoutubeData(ctx context.Context, arg GetInstanceYoutubeDataParams) (LogInstanceYoutubeTimestamped, error)
	GetInstancesByLogGroupID(ctx context.Context, logGroupID uuid.UUID) ([]LogInstancesGuild, error)
	// Fetches all log instances for a given realm with pre-joined speedrun rank data.
	// Used by the preview endpoint (admin-only, synchronous).
	GetInstancesForRetentionCheck(ctx context.Context, realmID uuid.UUID) ([]GetInstancesForRetentionCheckRow, error)
	// Fetches a page of log instances for cursor-based retention processing.
	// Ordered by end_time ASC so older logs are processed first.
	GetInstancesForRetentionCheckPaged(ctx context.Context, arg GetInstancesForRetentionCheckPagedParams) ([]GetInstancesForRetentionCheckPagedRow, error)
	GetItemRandomPropertiesByID(ctx context.Context, id int32) (DbcItemRandomProperty, error)
	GetItemSetBonuses(ctx context.Context, setID int32) ([]DbcItemSetBonu, error)
	GetItemSetByID(ctx context.Context, id int32) (DbcItemSet, error)
	GetItemSetItems(ctx context.Context, setID int32) ([]DbcItemSetItem, error)
	GetItemTemplateByEntry(ctx context.Context, entry int32) (WorldItemTemplate, error)
	// Looks up items by ID. For items not found by ID (e.g. transmog IDs),
	// falls back to name lookup but only if the name is unique in the table.
	// Pass paired arrays where item_ids[i] corresponds to item_names[i].
	GetItemTemplateMetadataBatch(ctx context.Context, arg GetItemTemplateMetadataBatchParams) ([]GetItemTemplateMetadataBatchRow, error)
	GetItemTemplatesByEntries(ctx context.Context, entries []int32) ([]WorldItemTemplate, error)
	GetItemTemplatesBySetID(ctx context.Context, setID int32) ([]GetItemTemplatesBySetIDRow, error)
	GetLatestRegressionSnapshot(ctx context.Context, fixtureID uuid.UUID) (RegressionSnapshot, error)
	GetLeaderboardVersionRequirements(ctx context.Context, instanceName string) (LeaderboardVersionRequirement, error)
	GetLogFile(ctx context.Context, id uuid.UUID) (LogFile, error)
	GetPanelLayoutByCode(ctx context.Context, code pgtype.Text) (GetPanelLayoutByCodeRow, error)
	GetPanelLayoutByID(ctx context.Context, id uuid.UUID) (GetPanelLayoutByIDRow, error)
	// Returns all realm IDs that have an applicable retention policy
	// (either directly or through their server).
	GetRealmsWithRetentionPolicies(ctx context.Context) ([]uuid.UUID, error)
	GetRegressionFixture(ctx context.Context, id uuid.UUID) (RegressionFixture, error)
	GetRegressionSnapshot(ctx context.Context, id uuid.UUID) (RegressionSnapshot, error)
	GetRetentionPolicies(ctx context.Context) ([]RetentionPolicy, error)
	GetRetentionPolicy(ctx context.Context, id uuid.UUID) (RetentionPolicy, error)
	// Returns the realm-specific policy if it exists, otherwise the server-level policy.
	GetRetentionPolicyForRealm(ctx context.Context, realmID uuid.NullUUID) (RetentionPolicy, error)
	GetRetentionRulesByPolicy(ctx context.Context, policyID uuid.UUID) ([]RetentionRule, error)
	GetServerUploadMetaRealmID(ctx context.Context, logGroupID uuid.UUID) (uuid.NullUUID, error)
	GetServersForWorld(ctx context.Context, worldID uuid.UUID) ([]WowServer, error)
	GetSharedViewByCode(ctx context.Context, code string) (SharedView, error)
	GetSharedViewByInstanceAndHash(ctx context.Context, arg GetSharedViewByInstanceAndHashParams) (SharedView, error)
	GetSiteConfig(ctx context.Context) (SiteConfig, error)
	GetSpellItemEnchantmentByID(ctx context.Context, id int32) (DbcSpellItemEnchantment, error)
	GetUploadKey(ctx context.Context, id uuid.UUID) (WowServerUploadKey, error)
	GetUploadKeyByHash(ctx context.Context, secretHash string) (GetUploadKeyByHashRow, error)
	GetUserActionBarSlots(ctx context.Context, userID uuid.UUID) (GetUserActionBarSlotsRow, error)
	GetUserAuthByLinkedID(ctx context.Context, arg GetUserAuthByLinkedIDParams) (UserAuthLink, error)
	GetUserAuthLinkByUserID(ctx context.Context, userID uuid.UUID) (UserAuthLink, error)
	GetUserAuthSessionByID(ctx context.Context, id uuid.UUID) (UserAuthSession, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (ChronicleUser, error)
	GetUserDataGrants(ctx context.Context, userID uuid.UUID) ([]DataGrant, error)
	GetUserPanelLayoutDefaults(ctx context.Context, id uuid.UUID) (GetUserPanelLayoutDefaultsRow, error)
	GetUserPasswordByAuthID(ctx context.Context, userAuthID uuid.UUID) (UserPassword, error)
	GetUserPasswordByResetToken(ctx context.Context, resetTokenHash pgtype.Text) (GetUserPasswordByResetTokenRow, error)
	GetUserPasswordByVerificationToken(ctx context.Context, verificationTokenHash pgtype.Text) (GetUserPasswordByVerificationTokenRow, error)
	GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]ChronicleUser, error)
	GetWoWLogFilesByGroupID(ctx context.Context, wowLogID uuid.UUID) ([]LogFile, error)
	GetWoWLogGroupByID(ctx context.Context, id uuid.UUID) (GetWoWLogGroupByIDRow, error)
	GetWoWLogGroupsByOwner(ctx context.Context, arg GetWoWLogGroupsByOwnerParams) ([]GetWoWLogGroupsByOwnerRow, error)
	GetWoWServer(ctx context.Context, id uuid.UUID) (WowServer, error)
	GetWoWServerByName(ctx context.Context, name string) (WowServer, error)
	GetWoWServerRealm(ctx context.Context, id uuid.UUID) (WowServerRealm, error)
	GetWorld(ctx context.Context, id uuid.UUID) (World, error)
	GetWorldByName(ctx context.Context, name string) (World, error)
	GetWorldInstanceTemplateByZoneName(ctx context.Context, zoneName string) (WorldInstanceTemplate, error)
	GetWorldInstanceUnits(ctx context.Context, instanceID uuid.UUID) ([]GetWorldInstanceUnitsRow, error)
	GetWorldInstanceZoneNames(ctx context.Context, instanceID uuid.UUID) ([]WorldInstanceZoneName, error)
	GetWorldsByServer(ctx context.Context, serverID uuid.UUID) ([]World, error)
	InsertEncounter(ctx context.Context, arg InsertEncounterParams) (LogInstanceEncounter, error)
	InsertEncounterCharacterFights(ctx context.Context, arg []InsertEncounterCharacterFightsParams) *InsertEncounterCharacterFightsBatchResults
	InsertGuildPagePanel(ctx context.Context, arg InsertGuildPagePanelParams) (GuildPagePanel, error)
	InsertGuildPageTab(ctx context.Context, arg InsertGuildPageTabParams) (GuildPageTab, error)
	InsertInstance(ctx context.Context, arg InsertInstanceParams) (LogInstance, error)
	InsertInstanceLoot(ctx context.Context, arg []InsertInstanceLootParams) *InsertInstanceLootBatchResults
	InsertInstancePlayers(ctx context.Context, arg []InsertInstancePlayersParams) *InsertInstancePlayersBatchResults
	InsertInstanceSpeedrun(ctx context.Context, arg InsertInstanceSpeedrunParams) error
	InsertInstanceUnits(ctx context.Context, arg []InsertInstanceUnitsParams) *InsertInstanceUnitsBatchResults
	InsertLogFile(ctx context.Context, arg InsertLogFileParams) (LogFile, error)
	InsertLogInstanceEvents(ctx context.Context, arg []InsertLogInstanceEventsParams) *InsertLogInstanceEventsBatchResults
	InsertParsedLogGroup(ctx context.Context, id uuid.UUID) error
	InsertRegressionFixture(ctx context.Context, arg InsertRegressionFixtureParams) (RegressionFixture, error)
	InsertRegressionSnapshot(ctx context.Context, arg InsertRegressionSnapshotParams) (RegressionSnapshot, error)
	InsertServerUploadMeta(ctx context.Context, arg InsertServerUploadMetaParams) error
	InsertStampedYoutubeVideo(ctx context.Context, arg InsertStampedYoutubeVideoParams) error
	// Upload Keys
	InsertUploadKey(ctx context.Context, arg InsertUploadKeyParams) (WowServerUploadKey, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertUserAuth(ctx context.Context, arg InsertUserAuthParams) (UserAuthLink, error)
	InsertUserAuthSession(ctx context.Context, arg InsertUserAuthSessionParams) (UserAuthSession, error)
	InsertUserPassword(ctx context.Context, arg InsertUserPasswordParams) (UserPassword, error)
	InsertWoWLogGroup(ctx context.Context, arg InsertWoWLogGroupParams) (WoWLogGroup, error)
	InsertWoWServer(ctx context.Context, arg InsertWoWServerParams) (WowServer, error)
	InsertWoWServerRealm(ctx context.Context, arg InsertWoWServerRealmParams) (WowServerRealm, error)
	InsertWorld(ctx context.Context, name string) (World, error)
	InsertWorldInstanceZoneName(ctx context.Context, arg InsertWorldInstanceZoneNameParams) error
	Instance(ctx context.Context, id uuid.UUID) (LogInstancesGuild, error)
	InstanceBySlug(ctx context.Context, hashedSlug pgtype.Text) (LogInstancesGuild, error)
	InstanceEvent(ctx context.Context, arg InstanceEventParams) (LogInstanceEvent, error)
	InstancePlayerGUIDsByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]guid.GUID, error)
	InstancePlayersByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]LogInstancePlayer, error)
	InstanceUnitsByInstanceID(ctx context.Context, instanceID uuid.UUID) ([]LogInstanceUnit, error)
	IsLayoutTrackedByUser(ctx context.Context, arg IsLayoutTrackedByUserParams) (bool, error)
	ListAllRetentionPolicies(ctx context.Context) ([]RetentionPolicy, error)
	ListAllUsers(ctx context.Context) ([]ChronicleUser, error)
	ListAllWoWLogGroupsWithOwner(ctx context.Context) ([]ListAllWoWLogGroupsWithOwnerRow, error)
	ListAllWoWLogGroupsWithOwnerPaginated(ctx context.Context, arg ListAllWoWLogGroupsWithOwnerPaginatedParams) ([]ListAllWoWLogGroupsWithOwnerPaginatedRow, error)
	ListDistinctInstanceNames(ctx context.Context) ([]string, error)
	ListGuildJoinRequests(ctx context.Context, guildID uuid.UUID) ([]ListGuildJoinRequestsRow, error)
	// Guild Page Panels
	ListGuildPagePanels(ctx context.Context, tabID uuid.UUID) ([]GuildPagePanel, error)
	// Guild Page Tabs
	ListGuildPageTabs(ctx context.Context, pageID uuid.UUID) ([]GuildPageTab, error)
	ListGuildsWithPages(ctx context.Context, arg ListGuildsWithPagesParams) ([]ListGuildsWithPagesRow, error)
	ListInstancesByDuplicateGroup(ctx context.Context, duplicateGroupID uuid.NullUUID) ([]ListInstancesByDuplicateGroupRow, error)
	ListInstancesByParserVersion(ctx context.Context, parserVersion string) ([]ListInstancesByParserVersionRow, error)
	ListInstancesByTimeRange(ctx context.Context, arg ListInstancesByTimeRangeParams) ([]ListInstancesByTimeRangeRow, error)
	ListLeaderboardVersionRequirements(ctx context.Context) ([]LeaderboardVersionRequirement, error)
	ListRecentInstances(ctx context.Context, arg ListRecentInstancesParams) ([]ListRecentInstancesRow, error)
	ListRecentInstancesByPlayer(ctx context.Context, arg ListRecentInstancesByPlayerParams) ([]ListRecentInstancesByPlayerRow, error)
	ListRegressionFixtures(ctx context.Context) ([]ListRegressionFixturesRow, error)
	ListRegressionSnapshots(ctx context.Context, arg ListRegressionSnapshotsParams) ([]ListRegressionSnapshotsRow, error)
	ListUploadKeysByRealm(ctx context.Context, realmID uuid.UUID) ([]ListUploadKeysByRealmRow, error)
	ListUserPanelLayouts(ctx context.Context, userID uuid.NullUUID) ([]ListUserPanelLayoutsRow, error)
	// Realms
	ListWoWServerRealms(ctx context.Context, serverID uuid.UUID) ([]WowServerRealm, error)
	// Servers
	ListWoWServers(ctx context.Context) ([]WowServer, error)
	ListWorldBossCredits(ctx context.Context) ([]WorldBossCredit, error)
	ListWorldInstanceScripts(ctx context.Context) ([]WorldInstanceScript, error)
	ListWorldInstanceSpawnEntries(ctx context.Context) ([]ListWorldInstanceSpawnEntriesRow, error)
	ListWorldInstanceTemplates(ctx context.Context) ([]WorldInstanceTemplate, error)
	ListWorldInstanceUnits(ctx context.Context) ([]ListWorldInstanceUnitsRow, error)
	ListWorldInstanceZoneNames(ctx context.Context) ([]WorldInstanceZoneName, error)
	ListWorlds(ctx context.Context) ([]World, error)
	MarkEmailVerified(ctx context.Context, userAuthID uuid.UUID) error
	PruneParsedInstanceFromLogOutput(ctx context.Context, arg PruneParsedInstanceFromLogOutputParams) error
	RecordAuthzMigration(ctx context.Context, version int32) error
	SearchGamePlayers(ctx context.Context, arg SearchGamePlayersParams) ([]SearchGamePlayersRow, error)
	SetDuplicateGroupIDs(ctx context.Context, arg SetDuplicateGroupIDsParams) error
	SetPanelLayoutCode(ctx context.Context, arg SetPanelLayoutCodeParams) (int64, error)
	SetResetToken(ctx context.Context, arg SetResetTokenParams) error
	SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error
	// Returns distinct instance names that have at least one qualified speedrun.
	SpeedrunInstanceNames(ctx context.Context) ([]string, error)
	// Returns the leaderboard for a given instance name.
	// Deduplicates by duplicate_group, then by guild (best per guild unless guild_id filter is set).
	// Excludes runs without a guild. Optional filters: realm, player count, guild.
	// When no guild filter: keep only the best run per guild.
	// When guild filter is set: keep all runs for that guild.
	SpeedrunLeaderboard(ctx context.Context, arg SpeedrunLeaderboardParams) ([]SpeedrunLeaderboardRow, error)
	// Returns distinct realm names that have at least one qualified speedrun.
	SpeedrunRealmNames(ctx context.Context) ([]string, error)
	TouchUploadKeyLastUsed(ctx context.Context, id uuid.UUID) error
	TrackUserPanelLayout(ctx context.Context, arg TrackUserPanelLayoutParams) (UserTrackedLayout, error)
	UnassignWorldFromServer(ctx context.Context, arg UnassignWorldFromServerParams) error
	UntrackUserPanelLayout(ctx context.Context, arg UntrackUserPanelLayoutParams) (int64, error)
	UpdateGuildPagePanel(ctx context.Context, arg UpdateGuildPagePanelParams) (GuildPagePanel, error)
	UpdateGuildPageTab(ctx context.Context, arg UpdateGuildPageTabParams) (GuildPageTab, error)
	UpdateLogFileAfterAppend(ctx context.Context, arg UpdateLogFileAfterAppendParams) error
	UpdateRegressionFixtureNote(ctx context.Context, arg UpdateRegressionFixtureNoteParams) error
	UpdateRetentionPolicyStats(ctx context.Context, arg UpdateRetentionPolicyStatsParams) error
	UpdateSiteConfig(ctx context.Context, signupsEnabled bool) (SiteConfig, error)
	UpdateUserAuthSessionTokens(ctx context.Context, arg UpdateUserAuthSessionTokensParams) (UserAuthSession, error)
	UpdateUserPanelLayoutByID(ctx context.Context, arg UpdateUserPanelLayoutByIDParams) (UserPanelLayout, error)
	UpdateUserPanelLayoutDefaults(ctx context.Context, arg UpdateUserPanelLayoutDefaultsParams) (UpdateUserPanelLayoutDefaultsRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRawLogRetentionHours(ctx context.Context, arg UpdateUserRawLogRetentionHoursParams) (User, error)
	UpdateWoWLogGroupLogType(ctx context.Context, arg UpdateWoWLogGroupLogTypeParams) error
	UpsertDataGrant(ctx context.Context, arg UpsertDataGrantParams) (DataGrant, error)
	UpsertGuild(ctx context.Context, arg UpsertGuildParams) (Guild, error)
	UpsertGuildPage(ctx context.Context, arg UpsertGuildPageParams) (GuildPage, error)
	UpsertGuildSettings(ctx context.Context, arg UpsertGuildSettingsParams) (GuildSetting, error)
	UpsertLeaderboardVersionRequirements(ctx context.Context, arg UpsertLeaderboardVersionRequirementsParams) (LeaderboardVersionRequirement, error)
	UpsertPlayers(ctx context.Context, arg []UpsertPlayersParams) *UpsertPlayersBatchResults
	UpsertRetentionPolicy(ctx context.Context, arg UpsertRetentionPolicyParams) (RetentionPolicy, error)
	UpsertRetentionPolicyByRealm(ctx context.Context, arg UpsertRetentionPolicyByRealmParams) (RetentionPolicy, error)
	UpsertRetentionRule(ctx context.Context, arg UpsertRetentionRuleParams) (RetentionRule, error)
	UpsertUserActionBarSlots(ctx context.Context, arg UpsertUserActionBarSlotsParams) (UpsertUserActionBarSlotsRow, error)
	UpsertWorldInstanceTemplate(ctx context.Context, arg UpsertWorldInstanceTemplateParams) (WorldInstanceTemplate, error)
	UpsertWorldInstanceUnit(ctx context.Context, arg UpsertWorldInstanceUnitParams) error
}

var _ sqlcQuerier = (*sqlQuerier)(nil)
