// Code generated by scripts/dbcdata (server: vanillaplus). DO NOT EDIT.

export type ExtraAttackSpell = {
  name: string;
  numExtraAttacks: number;
};

export const ExtraAttackSpells: Record<number, ExtraAttackSpell> = {
  677: { name: "zzOLDHoly Flurry II", numExtraAttacks: 1 },
  1869: { name: "zzOLDHoly Flurry III", numExtraAttacks: 2 },
  1870: { name: "zzOLDHoly Flurry IV", numExtraAttacks: 2 },
  3391: { name: "Thrash", numExtraAttacks: 2 },
  15494: { name: "Fury of Forgewright", numExtraAttacks: 2 },
  15601: { name: "Hand of Justice", numExtraAttacks: 1 },
  15642: { name: "Ironfoe", numExtraAttacks: 3 },
  16459: { name: "Sword Specialization", numExtraAttacks: 1 },
  16843: { name: "Crimson Fury", numExtraAttacks: 3 },
  18797: { name: "Flurry Axe", numExtraAttacks: 1 },
  18941: { name: "Double Attack", numExtraAttacks: 1 },
  19105: { name: "MHTest01 Effect", numExtraAttacks: 2 },
  19109: { name: "MHTest02 Effect", numExtraAttacks: 2 },
  20178: { name: "Reckoning", numExtraAttacks: 1 },
  21919: { name: "Thrash", numExtraAttacks: 1 },
  25175: { name: "Triple Attack", numExtraAttacks: 2 },
  27035: { name: "Sword Specialization (OLD)", numExtraAttacks: 1 },
  34756: { name: "Windfury Weapon", numExtraAttacks: 2 },
  35314: { name: "Corrupted Windfury", numExtraAttacks: 2 },
};
