package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"text/template"

	"github.com/Emyrk/chronicle/database/gamedb/dbcdb"
	"github.com/Gophercraft/core/format/dbc/dbdefs"

	"github.com/coder/serpent"
)

func StaticPopulateCmd() *serpent.Command {
	var outputDir string
	var dbcPath string
	var server string
	return &serpent.Command{
		Use:   "static",
		Short: "Generate static Go code from DBC data.",
		Options: serpent.OptionSet{
			{
				Name:          "output-dir",
				Description:   "Output directory for generated files. Defaults to stdout.",
				Flag:          "output-dir",
				FlagShorthand: "o",
				Value:         serpent.StringOf(&outputDir),
			},
			DBCOption(&dbcPath),
			ServerOption(&server),
		},
		Handler: func(inv *serpent.Invocation) error {
			resolved, err := ResolveDBCPath(dbcPath, server)
			if err != nil {
				return err
			}
			wc, err := dbcdb.New(resolved)
			if err != nil {
				return fmt.Errorf("(static) open wow client: %w", err)
			}

			// Generate cast times
			if err := generateCastTimes(wc, outputDir, inv.Stdout, server); err != nil {
				return fmt.Errorf("generate cast times: %w", err)
			}

			// Generate spell icons
			if err := generateSpellIcons(wc, outputDir, inv.Stdout, server); err != nil {
				return fmt.Errorf("generate spell icons: %w", err)
			}

			// Generate spell durations
			if err := generateSpellDurations(wc, outputDir, inv.Stdout, server); err != nil {
				return fmt.Errorf("generate spell durations: %w", err)
			}

			// Generate spell ranges
			if err := generateSpellRanges(wc, outputDir, inv.Stdout, server); err != nil {
				return fmt.Errorf("generate spell ranges: %w", err)
			}

			// Generate spell categories
			if err := generateSpellCategories(wc, outputDir, inv.Stdout, server); err != nil {
				return fmt.Errorf("generate spell categories: %w", err)
			}

			// Generate spell radii
			if err := generateSpellRadii(wc, outputDir, inv.Stdout, server); err != nil {
				return fmt.Errorf("generate spell radii: %w", err)
			}

			// Generate spell focus objects
			if err := generateSpellFocusObjects(wc, outputDir, inv.Stdout, server); err != nil {
				return fmt.Errorf("generate spell focus objects: %w", err)
			}

			return nil
		},
	}
}

func generateCastTimes(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer, server string) error {
	sct, err := wc.SpellCastTimes()
	if err != nil {
		return fmt.Errorf("read spell cast times: %w", err)
	}

	var entries []dbdefs.Ent_SpellCastTimes
	err = sct.Range(func(cursor *dbdefs.Ent_SpellCastTimes) bool {
		entries = append(entries, *cursor)
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell cast times: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "casttimes.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return castTimesTemplate.Execute(out, serverData{Server: server, Entries: entries})
}

type spellIconEntry struct {
	ID              int32
	TextureFilename string
}

func generateSpellIcons(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer, server string) error {
	icons, err := wc.SpellIcons()
	if err != nil {
		return fmt.Errorf("read spell icons: %w", err)
	}

	var entries []spellIconEntry
	err = icons.Range(func(cursor *dbdefs.Ent_SpellIcon) bool {
		entries = append(entries, spellIconEntry{
			ID:              cursor.ID,
			TextureFilename: cutIconPrefix(cursor.TextureFilename),
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell icons: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellicons.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellIconsTemplate.Execute(out, serverData{Server: server, Entries: entries})
}

// serverData wraps template data with the server package name.
type serverData struct {
	Server  string
	Entries any
}

// outputWriter returns a writer for the given filename.
// If outputDir is empty, returns stdout.
// The cleanup function must be called to close any opened file.
func outputWriter(outputDir, filename string, stdout io.Writer) (io.Writer, func(), error) {
	if outputDir == "" {
		return stdout, func() {}, nil
	}

	path := filepath.Join(outputDir, filename)
	f, err := os.Create(path)
	if err != nil {
		return nil, nil, fmt.Errorf("create %s: %w", path, err)
	}
	// nolint:errcheck
	return f, func() { f.Close() }, nil
}

var castTimesTemplate = template.Must(template.New("casttimes").Parse(`// Code generated by scripts/dbcdata (server: {{.Server}}). DO NOT EDIT.

package {{.Server}}

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellCastTimes = map[int32]dbcmem.SpellCastTime{
{{- range .Entries}}
		{{.ID}}: {ID: {{.ID}}, Base: {{.Base}}, PerLevel: {{.PerLevel}}, Minimum: {{.Minimum}}},
{{- end}}
	}
}
`))

var spellIconsTemplate = template.Must(template.New("spellicons").Parse(`// Code generated by scripts/dbcdata (server: {{.Server}}). DO NOT EDIT.

package {{.Server}}

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellIcons = map[int32]dbcmem.SpellIcon{
{{- range .Entries}}
		{{.ID}}: {ID: {{.ID}}, TextureFilename: {{printf "%q" .TextureFilename}}},
{{- end}}
	}
}
`))

func generateSpellDurations(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer, server string) error {
	durations, err := wc.SpellDuration()
	if err != nil {
		return fmt.Errorf("read spell durations: %w", err)
	}

	var entries []dbdefs.Ent_SpellDuration
	err = durations.Range(func(cursor *dbdefs.Ent_SpellDuration) bool {
		entries = append(entries, *cursor)
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell durations: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellduration.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellDurationTemplate.Execute(out, serverData{Server: server, Entries: entries})
}

var spellDurationTemplate = template.Must(template.New("spellduration").Parse(`// Code generated by scripts/dbcdata (server: {{.Server}}). DO NOT EDIT.

package {{.Server}}

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellDurations = map[int32]dbcmem.SpellDuration{
{{- range .Entries}}
		{{.ID}}: {ID: {{.ID}}, Duration: {{.Duration}}, DurationPerLevel: {{.DurationPerLevel}}, MaxDuration: {{.MaxDuration}}},
{{- end}}
	}
}
`))

type spellRangeEntry struct {
	ID       int32
	RangeMin float32
	RangeMax float32
	Flags    int32
	Name     string
}

func generateSpellRanges(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer, server string) error {
	ranges, err := wc.SpellRange()
	if err != nil {
		return fmt.Errorf("read spell ranges: %w", err)
	}

	var entries []spellRangeEntry
	err = ranges.Range(func(cursor *dbdefs.Ent_SpellRange) bool {
		// RangeMin/RangeMax are slices with [0]=friendly, [1]=hostile
		// We take the hostile range (index 1) as the primary value
		var rangeMin, rangeMax float32
		if len(cursor.RangeMin) > 1 {
			rangeMin = cursor.RangeMin[1]
		} else if len(cursor.RangeMin) > 0 {
			rangeMin = cursor.RangeMin[0]
		}
		if len(cursor.RangeMax) > 1 {
			rangeMax = cursor.RangeMax[1]
		} else if len(cursor.RangeMax) > 0 {
			rangeMax = cursor.RangeMax[0]
		}

		entries = append(entries, spellRangeEntry{
			ID:       cursor.ID,
			RangeMin: rangeMin,
			RangeMax: rangeMax,
			Flags:    cursor.Flags,
			Name:     cursor.DisplayName_lang.String(),
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell ranges: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellrange.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellRangeTemplate.Execute(out, serverData{Server: server, Entries: entries})
}

var spellRangeTemplate = template.Must(template.New("spellrange").Parse(`// Code generated by scripts/dbcdata (server: {{.Server}}). DO NOT EDIT.

package {{.Server}}

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellRanges = map[int32]dbcmem.SpellRange{
{{- range .Entries}}
		{{.ID}}: {ID: {{.ID}}, RangeMin: {{.RangeMin}}, RangeMax: {{.RangeMax}}, Flags: {{.Flags}}, Name: {{printf "%q" .Name}}},
{{- end}}
	}
}
`))

type spellCategoryEntry struct {
	ID                 int32
	Flags              int32
	UsesPerWeek        int32
	Name               string
	MaxCharges         int32
	ChargeRecoveryTime int32
	TypeMask           int32
}

func generateSpellCategories(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer, server string) error {
	categories, err := wc.SpellCategory()
	if err != nil {
		return fmt.Errorf("read spell categories: %w", err)
	}

	var entries []spellCategoryEntry
	err = categories.Range(func(cursor *dbdefs.Ent_SpellCategory) bool {
		entries = append(entries, spellCategoryEntry{
			ID:                 cursor.ID,
			Flags:              cursor.Flags,
			UsesPerWeek:        cursor.UsesPerWeek,
			Name:               cursor.Name_lang.String(),
			MaxCharges:         cursor.MaxCharges,
			ChargeRecoveryTime: cursor.ChargeRecoveryTime,
			TypeMask:           cursor.TypeMask,
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell categories: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellcategory.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellCategoryTemplate.Execute(out, serverData{Server: server, Entries: entries})
}

var spellCategoryTemplate = template.Must(template.New("spellcategory").Parse(`// Code generated by scripts/dbcdata (server: {{.Server}}). DO NOT EDIT.

package {{.Server}}

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellCategories = map[int32]dbcmem.SpellCategory{
{{- range .Entries}}
		{{.ID}}: {ID: {{.ID}}, Flags: {{.Flags}}, UsesPerWeek: {{.UsesPerWeek}}, Name: {{printf "%q" .Name}}, MaxCharges: {{.MaxCharges}}, ChargeRecoveryTime: {{.ChargeRecoveryTime}}, TypeMask: {{.TypeMask}}},
{{- end}}
	}
}
`))

func generateSpellRadii(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer, server string) error {
	radii, err := wc.SpellRadius()
	if err != nil {
		return fmt.Errorf("read spell radii: %w", err)
	}

	var entries []dbdefs.Ent_SpellRadius
	err = radii.Range(func(cursor *dbdefs.Ent_SpellRadius) bool {
		entries = append(entries, *cursor)
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell radii: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellradius.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellRadiusTemplate.Execute(out, serverData{Server: server, Entries: entries})
}

var spellRadiusTemplate = template.Must(template.New("spellradius").Parse(`// Code generated by scripts/dbcdata (server: {{.Server}}). DO NOT EDIT.

package {{.Server}}

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellRadii = map[int32]dbcmem.SpellRadius{
{{- range .Entries}}
		{{.ID}}: {ID: {{.ID}}, Radius: {{.Radius}}, RadiusPerLevel: {{.RadiusPerLevel}}, RadiusMin: {{.RadiusMin}}, RadiusMax: {{.RadiusMax}}},
{{- end}}
	}
}
`))

type spellFocusObjectEntry struct {
	ID   int32
	Name string
}

func generateSpellFocusObjects(wc *dbcdb.WoWClient, outputDir string, stdout io.Writer, server string) error {
	focusObjects, err := wc.SpellFocusObject()
	if err != nil {
		return fmt.Errorf("read spell focus objects: %w", err)
	}

	var entries []spellFocusObjectEntry
	err = focusObjects.Range(func(cursor *dbdefs.Ent_SpellFocusObject) bool {
		entries = append(entries, spellFocusObjectEntry{
			ID:   cursor.ID,
			Name: cursor.Name_lang.String(),
		})
		return true
	})
	if err != nil {
		return fmt.Errorf("iterate spell focus objects: %w", err)
	}

	out, cleanup, err := outputWriter(outputDir, "spellfocusobject.go", stdout)
	if err != nil {
		return err
	}
	defer cleanup()

	return spellFocusObjectTemplate.Execute(out, serverData{Server: server, Entries: entries})
}

var spellFocusObjectTemplate = template.Must(template.New("spellfocusobject").Parse(`// Code generated by scripts/dbcdata (server: {{.Server}}). DO NOT EDIT.

package {{.Server}}

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellFocusObjects = map[int32]dbcmem.SpellFocusObject{
{{- range .Entries}}
		{{.ID}}: {ID: {{.ID}}, Name: {{printf "%q" .Name}}},
{{- end}}
	}
}
`))
