// Code generated by scripts/dbcdata (server: octowow). DO NOT EDIT.

package octowow

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.ExtraAttackSpells = map[int32]dbcmem.ExtraAttackSpell{
		677: {Name: "Holy Flurry II", NumExtraAttacks: 1},
		1869: {Name: "Holy Flurry III", NumExtraAttacks: 2},
		1870: {Name: "Holy Flurry IV", NumExtraAttacks: 2},
		3391: {Name: "Thrash", NumExtraAttacks: 2},
		8233: {Name: "Windfury Weapon", NumExtraAttacks: 2},
		8236: {Name: "Windfury Weapon", NumExtraAttacks: 2},
		8516: {Name: "Windfury Totem", NumExtraAttacks: 1},
		10484: {Name: "Windfury Weapon", NumExtraAttacks: 2},
		10608: {Name: "Windfury Totem", NumExtraAttacks: 1},
		10610: {Name: "Windfury Totem", NumExtraAttacks: 1},
		15494: {Name: "Fury of Forgewright", NumExtraAttacks: 2},
		15601: {Name: "Hand of Justice", NumExtraAttacks: 1},
		15642: {Name: "Ironfoe", NumExtraAttacks: 3},
		16361: {Name: "Windfury Weapon", NumExtraAttacks: 2},
		16459: {Name: "Sword Specialization", NumExtraAttacks: 1},
		16843: {Name: "Crimson Fury", NumExtraAttacks: 3},
		18797: {Name: "Flurry Axe", NumExtraAttacks: 1},
		18941: {Name: "Double Attack", NumExtraAttacks: 1},
		19105: {Name: "MHTest01 Effect", NumExtraAttacks: 2},
		19109: {Name: "MHTest02 Effect", NumExtraAttacks: 2},
		20178: {Name: "Reckoning", NumExtraAttacks: 1},
		21919: {Name: "Thrash", NumExtraAttacks: 1},
		25175: {Name: "Triple Attack", NumExtraAttacks: 2},
		27035: {Name: "Sword Specialization (OLD)", NumExtraAttacks: 1},
		49369: {Name: "Rage of the Mountain", NumExtraAttacks: 1},
		51368: {Name: "Windfury Totem", NumExtraAttacks: 1},
		52634: {Name: "Hack and Slash", NumExtraAttacks: 1},
		52732: {Name: "Timeless Strike", NumExtraAttacks: 1},
		58123: {Name: "Maddened Strikes", NumExtraAttacks: 1},
	}
}
