// Code generated by scripts/dbcdata (server: octowow). DO NOT EDIT.

package octowow

import "github.com/Emyrk/chronicle/database/gamedb/chrondbc/dbcmem"

func init() {
	dbcmem.SpellRadii = map[int32]dbcmem.SpellRadius{
		7: {ID: 7, Radius: 2, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 2},
		8: {ID: 8, Radius: 5, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 5},
		9: {ID: 9, Radius: 20, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 20},
		10: {ID: 10, Radius: 30, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 30},
		11: {ID: 11, Radius: 45, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 45},
		12: {ID: 12, Radius: 100, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 100},
		13: {ID: 13, Radius: 10, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 10},
		14: {ID: 14, Radius: 8, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 8},
		15: {ID: 15, Radius: 3, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 3},
		16: {ID: 16, Radius: 1, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 1},
		17: {ID: 17, Radius: 13, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 13},
		18: {ID: 18, Radius: 15, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 15},
		19: {ID: 19, Radius: 18, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 18},
		20: {ID: 20, Radius: 25, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 25},
		21: {ID: 21, Radius: 35, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 35},
		22: {ID: 22, Radius: 200, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 200},
		23: {ID: 23, Radius: 40, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 40},
		24: {ID: 24, Radius: 65, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 65},
		25: {ID: 25, Radius: 70, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 70},
		26: {ID: 26, Radius: 4, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 4},
		27: {ID: 27, Radius: 50, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 50},
		28: {ID: 28, Radius: 50000, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 50000},
		29: {ID: 29, Radius: 6, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 6},
		31: {ID: 31, Radius: 80, RadiusPerLevel: 0, RadiusMin: 0, RadiusMax: 80},
	}
}
